function resampled_eeg_segment_data = resample_eeg_segments( ...
    eeg_segment_data, matched_segments, edf_input, plot_sanity_check)
%RESAMPLE_EEG_SEGMENTS Resample HD-EEG segments onto the EDF scalp clock.
%   The EDF time axis is the reference. Each segment's effective HD-EEG
%   sampling rate is calculated from its EEG sample span and its duration
%   on the EDF clock, then the data are resampled to EDF_FS with an
%   antialiasing filter.
%   RESAMPLE_EEG_SEGMENTS(..., PLOT_SANITY_CHECK) creates a 5-by-2 trace
%   comparison and a Welch-spectrum figure for each matched segment.

if nargin < 4
    plot_sanity_check = false;
end

edf_Fs = edf_input.Fs;
edf_trigger_Fs = edf_input.trigger_Fs;
edf_eeg_channel_names = string(edf_input.edf_eeg_channel_names);

n_segments = height(matched_segments);
assert(numel(eeg_segment_data) == n_segments, ...
    'resample_eeg_segments:SegmentCountMismatch', ...
    'The EEG cell array must contain one entry per matched segment.')

scalp_samples_per_trigger_sample = edf_Fs / edf_trigger_Fs;
ratio_tolerance = 10 * eps(max(abs( ...
    scalp_samples_per_trigger_sample), 1));
assert(abs(scalp_samples_per_trigger_sample - ...
    round(scalp_samples_per_trigger_sample)) <= ratio_tolerance, ...
    'resample_eeg_segments:NonintegerEdfRateRatio', ...
    ['The EDF scalp sampling rate must be an integer multiple of the ' ...
     'EDF trigger sampling rate.'])

resampled_eeg_segment_data = cell(n_segments, 1);

for segment_i = 1:n_segments
    assert(size(eeg_segment_data{segment_i}, 1) == ...
        numel(edf_eeg_channel_names), ...
        'resample_eeg_segments:ChannelCountMismatch', ...
        ['EEG segment %d must contain one row per EDF EEG channel ' ...
         'name.'], segment_i)

    eeg_sample_span = matched_segments.eeg_end_sample(segment_i) - ...
        matched_segments.eeg_start_sample(segment_i);
    assert(size(eeg_segment_data{segment_i}, 2) == eeg_sample_span + 1, ...
        'resample_eeg_segments:UnexpectedEegSegmentLength', ...
        'EEG segment %d does not match its reported sample bounds.', ...
        segment_i)

    edf_trigger_sample_span = ...
        matched_segments.edf_end_sample(segment_i) - ...
        matched_segments.edf_start_sample(segment_i);
    edf_duration_sec = edf_trigger_sample_span / edf_trigger_Fs;
    effective_hd_eeg_Fs = eeg_sample_span / edf_duration_sec;

    target_sample_span = edf_trigger_sample_span * ...
        scalp_samples_per_trigger_sample;
    target_span_tolerance = 10 * eps(max(abs(target_sample_span), 1));
    assert(abs(target_sample_span - round(target_sample_span)) <= ...
        target_span_tolerance, ...
        'resample_eeg_segments:NonintegerTargetSampleSpan', ...
        'EDF segment %d does not map to an integer scalp sample span.', ...
        segment_i)
    expected_sample_count = round(target_sample_span) + 1;

    input_time_sec = (0:eeg_sample_span)' / effective_hd_eeg_Fs;
    input_time_sec(end) = input_time_sec(end) + ...
        10 * eps(max(edf_duration_sec, 1));

    % RESAMPLE first interpolates to an intermediate grid at
    % intermediate_factor * edf_Fs, then applies its
    % polyphase antialiasing filter. The factor keeps that intermediate
    % grid at or above the effective HD-EEG sampling rate.
    intermediate_factor = ceil(effective_hd_eeg_Fs / edf_Fs);
    resampled_segment = resample( ...
        eeg_segment_data{segment_i}', input_time_sec, ...
        edf_Fs, 1, intermediate_factor);

    assert(size(resampled_segment, 1) == expected_sample_count, ...
        'resample_eeg_segments:UnexpectedResampledLength', ...
        ['Resampled EEG segment %d contains %d samples; the matched EDF ' ...
         'scalp interval requires %d samples.'], ...
        segment_i, size(resampled_segment, 1), expected_sample_count)
    resampled_eeg_segment_data{segment_i} = resampled_segment';

    if plot_sanity_check
        output_time_sec = (0:(expected_sample_count - 1))' / edf_Fs;
        plot_resampling_sanity_checks( ...
            eeg_segment_data{segment_i}, ...
            resampled_eeg_segment_data{segment_i}, ...
            input_time_sec, output_time_sec, ...
            edf_eeg_channel_names, edf_Fs, segment_i)
    end
end

assert(numel(resampled_eeg_segment_data) == height(matched_segments), ...
    'Resampling did not return one HD-EEG cell per matched segment.')

end

function plot_resampling_sanity_checks( ...
    original_segment, resampled_segment, ...
    original_time_sec, resampled_time_sec, ...
    edf_eeg_channel_names, edf_Fs, segment_i)

plot_channel_names = [ ...
    "Fp1", "Fp2", "F3", "F4", "C3", ...
    "C4", "O1", "O2", "M1", "M2"];
[has_channel, channel_index] = ismember( ...
    lower(plot_channel_names), lower(edf_eeg_channel_names));
if ~all(has_channel)
    missing_names = strjoin(plot_channel_names(~has_channel), ', ');
    error('resample_eeg_segments:MissingPlotChannel', ...
        'Required sanity-plot channel(s) not found: %s.', missing_names)
end

plot_time_trace_comparison( ...
    original_segment(channel_index, :), ...
    resampled_segment(channel_index, :), ...
    original_time_sec, resampled_time_sec, ...
    plot_channel_names, segment_i)
plot_welch_spectra( ...
    resampled_segment(channel_index, :), ...
    plot_channel_names, edf_Fs, segment_i)

end

function plot_time_trace_comparison( ...
    original_segment, resampled_segment, ...
    original_time_sec, resampled_time_sec, channel_names, segment_i)

trace_duration_sec = min(30, resampled_time_sec(end));
use_original = original_time_sec <= trace_duration_sec;
use_resampled = resampled_time_sec <= trace_duration_sec;
original_color = [0, 0.4470, 0.7410];
resampled_color = [0.8500, 0.3250, 0.0980];

figure_handle = figure( ...
    'Name', sprintf('Resampling trace comparison - segment %d', segment_i), ...
    'Tag', 'resample_time_trace_comparison', ...
    'Color', 'w');
axes_handles = gobjects(numel(channel_names), 1);

for channel_i = 1:numel(channel_names)
    axes_handles(channel_i) = subplot( ...
        5, 2, channel_i, 'Parent', figure_handle);
    plot(axes_handles(channel_i), ...
        original_time_sec(use_original), ...
        original_segment(channel_i, use_original), ...
        'Color', original_color, 'LineWidth', 1.25, ...
        'DisplayName', 'Original')
    hold(axes_handles(channel_i), 'on')
    plot(axes_handles(channel_i), ...
        resampled_time_sec(use_resampled), ...
        resampled_segment(channel_i, use_resampled), ...
        'Color', resampled_color, 'LineWidth', 0.75, ...
        'DisplayName', 'Resampled')
    hold(axes_handles(channel_i), 'off')
    title(axes_handles(channel_i), channel_names(channel_i))
    set(axes_handles(channel_i), 'FontSize', 10)
    grid(axes_handles(channel_i), 'on')

    if mod(channel_i, 2) == 1
        ylabel(axes_handles(channel_i), 'Amplitude')
    end
    if channel_i >= 9
        xlabel(axes_handles(channel_i), 'EDF time (sec)')
    end
end

legend(axes_handles(1), 'show', 'Location', 'best')
linkaxes(axes_handles, 'x')
xlim(axes_handles(1), [0, trace_duration_sec])
sgtitle(figure_handle, sprintf( ...
    'Original and resampled HD-EEG: segment %d, first %.1f sec', ...
    segment_i, trace_duration_sec), 'FontSize', 16)

end

function plot_welch_spectra( ...
    resampled_segment, channel_names, edf_Fs, segment_i)

window_samples = min(round(4 * edf_Fs), size(resampled_segment, 2));
welch_window = hamming(window_samples, 'periodic');
overlap_samples = floor(window_samples / 2);
nfft = max(256, 2 ^ nextpow2(window_samples));
line_colors = lines(numel(channel_names));

figure_handle = figure( ...
    'Name', sprintf('Resampled Welch spectra - segment %d', segment_i), ...
    'Tag', 'resample_welch_spectra', ...
    'Color', 'w');
ax = axes('Parent', figure_handle, 'Tag', 'resample_welch_spectrum_axes');
hold(ax, 'on')

for channel_i = 1:numel(channel_names)
    [power_density, frequency] = pwelch( ...
        double(resampled_segment(channel_i, :)), ...
        welch_window, overlap_samples, nfft, edf_Fs);
    plot(ax, frequency, ...
        10 * log10(max(power_density, realmin('double'))), ...
        'Color', line_colors(channel_i, :), ...
        'LineWidth', 1, ...
        'DisplayName', channel_names(channel_i))
end

hold(ax, 'off')
set(ax, 'FontSize', 14)
xlim(ax, [0, edf_Fs / 2])
xlabel(ax, 'Frequency (Hz)')
ylabel(ax, 'Power/frequency (dB/Hz)')
title(ax, sprintf( ...
    'Welch spectra of resampled HD-EEG: segment %d', segment_i), ...
    'FontSize', 18)
legend(ax, 'show', 'Location', 'best', 'NumColumns', 2)
grid(ax, 'on')

end
