function tests = test_sanity_check_EOG
tests = functiontests(localfunctions);
end

function setupOnce(~)
project_path = fileparts(fileparts(mfilename('fullpath')));
addpath(project_path)
addpath(fullfile(project_path, 'helper_functions'))
end

function testPlotsHdAndReconstructedClinicalEdfEog(testCase)
[aligned_eeg_data, aligned_eeg_channel_names, ...
    signalHeader_all, signalCell_all, edf_Fs] = make_fixture;
signalCell_all = signalCell_all(:);
signalCell_before = signalCell_all;

original_visibility = get(groot, 'defaultFigureVisible');
visibility_cleanup = onCleanup(@() set( ...
    groot, 'defaultFigureVisible', original_visibility));
set(groot, 'defaultFigureVisible', 'off')

figure_handle = sanity_check_EOG( ...
    aligned_eeg_data, aligned_eeg_channel_names, ...
    signalHeader_all, signalCell_all, edf_Fs);
figure_cleanup = onCleanup(@() delete(figure_handle));

verifyEmpty(testCase, figure_handle.Name)
verifyEmpty(testCase, figure_handle.Tag)
axes_handles = findall( ...
    figure_handle, 'Type', 'axes', ...
    'Tag', 'sanity_check_EOG_axes');
line_handles = findall(figure_handle, 'Type', 'line');
verifyNumElements(testCase, axes_handles, 4)
verifyNumElements(testCase, line_handles, 4)
for axes_i = 1:numel(axes_handles)
    verifyEqual(testCase, ...
        char(axes_handles(axes_i).InteractionOptions.DatatipsSupported), ...
        'off')
    verifyEqual(testCase, ...
        char(axes_handles(axes_i).InteractionOptions.ZoomSupported), 'on')
end

expected_time_hours = ...
    (0:(size(aligned_eeg_data, 2) - 1)) / (edf_Fs * 3600);
veogl_index = strcmp(aligned_eeg_channel_names, 'VEOGL');
m2_index = strcmp(aligned_eeg_channel_names, 'M2');
expected_hd_eog = ...
    aligned_eeg_data(veogl_index, :) - aligned_eeg_data(m2_index, :);
verify_trace(testCase, figure_handle, ...
    'HD-EEG VEOGL:M2', expected_time_hours, expected_hd_eog)

e1_data = get_edf_signal( ...
    signalHeader_all, signalCell_all, 'E1');
e2_data = get_edf_signal( ...
    signalHeader_all, signalCell_all, 'E2');
m1_data = get_edf_signal( ...
    signalHeader_all, signalCell_all, 'M1');
m2_data = get_edf_signal( ...
    signalHeader_all, signalCell_all, 'M2');
verify_trace(testCase, figure_handle, ...
    'Clinical EDF E2:M1', expected_time_hours, e2_data - m1_data)
verify_trace(testCase, figure_handle, ...
    'Clinical EDF E1:M2', expected_time_hours, e1_data - m2_data)
verify_trace(testCase, figure_handle, ...
    'Clinical EDF E2:M2', expected_time_hours, e2_data - m2_data)

stored_montage_names = {'E2:M1', 'E1:M2', 'E2:M2'};
for channel_i = 1:numel(stored_montage_names)
    trace = findall(figure_handle, 'Type', 'line', ...
        'DisplayName', ['Clinical EDF ' stored_montage_names{channel_i}]);
    stored_data = get_edf_signal( ...
        signalHeader_all, signalCell_all, ...
        stored_montage_names{channel_i});
    verifyNotEqual(testCase, trace.YData, stored_data)
end

verifyEqual(testCase, signalCell_all, signalCell_before)
end

function testMissingStoredMontageRowsAreIrrelevant(testCase)
[aligned_eeg_data, aligned_eeg_channel_names, ...
    signalHeader_all, signalCell_all, edf_Fs] = make_fixture;
stored_montage_names = {'E2:M1', 'E1:M2', 'E2:M2'};
remove_index = ismember( ...
    {signalHeader_all.signal_labels}, stored_montage_names);
signalHeader_all(remove_index) = [];
signalCell_all(remove_index) = [];

original_visibility = get(groot, 'defaultFigureVisible');
visibility_cleanup = onCleanup(@() set( ...
    groot, 'defaultFigureVisible', original_visibility));
set(groot, 'defaultFigureVisible', 'off')

figure_handle = sanity_check_EOG( ...
    aligned_eeg_data, aligned_eeg_channel_names, ...
    signalHeader_all, signalCell_all, edf_Fs);
figure_cleanup = onCleanup(@() delete(figure_handle));

e1_data = get_edf_signal( ...
    signalHeader_all, signalCell_all, 'E1');
e2_data = get_edf_signal( ...
    signalHeader_all, signalCell_all, 'E2');
m1_data = get_edf_signal( ...
    signalHeader_all, signalCell_all, 'M1');
m2_data = get_edf_signal( ...
    signalHeader_all, signalCell_all, 'M2');
expected_time_hours = ...
    (0:(size(aligned_eeg_data, 2) - 1)) / (edf_Fs * 3600);
verify_trace(testCase, figure_handle, ...
    'Clinical EDF E2:M1', expected_time_hours, e2_data - m1_data)
verify_trace(testCase, figure_handle, ...
    'Clinical EDF E1:M2', expected_time_hours, e1_data - m2_data)
verify_trace(testCase, figure_handle, ...
    'Clinical EDF E2:M2', expected_time_hours, e2_data - m2_data)
end

function testMissingDirectChannelFails(testCase)
[aligned_eeg_data, aligned_eeg_channel_names, ...
    signalHeader_all, signalCell_all, edf_Fs] = make_fixture;
missing_index = strcmp( ...
    {signalHeader_all.signal_labels}, 'E2');
signalHeader_all(missing_index) = [];
signalCell_all(missing_index) = [];

verifyError(testCase, @() sanity_check_EOG( ...
    aligned_eeg_data, aligned_eeg_channel_names, ...
    signalHeader_all, signalCell_all, edf_Fs), ...
    'sanity_check_EOG:MissingDirectChannel')
end

function testDuplicateDirectChannelFails(testCase)
[aligned_eeg_data, aligned_eeg_channel_names, ...
    signalHeader_all, signalCell_all, edf_Fs] = make_fixture;
duplicate_index = strcmp( ...
    {signalHeader_all.signal_labels}, 'M1');
signalHeader_all(end + 1) = signalHeader_all(duplicate_index);
signalCell_all{end + 1} = signalCell_all{duplicate_index};

verifyError(testCase, @() sanity_check_EOG( ...
    aligned_eeg_data, aligned_eeg_channel_names, ...
    signalHeader_all, signalCell_all, edf_Fs), ...
    'sanity_check_EOG:DuplicateDirectChannel')
end

function testDirectSignalSampleCountMismatchFails(testCase)
[aligned_eeg_data, aligned_eeg_channel_names, ...
    signalHeader_all, signalCell_all, edf_Fs] = make_fixture;
short_index = strcmp({signalHeader_all.signal_labels}, 'M2');
signalCell_all{short_index} = signalCell_all{short_index}(1:end-1);

verifyError(testCase, @() sanity_check_EOG( ...
    aligned_eeg_data, aligned_eeg_channel_names, ...
    signalHeader_all, signalCell_all, edf_Fs), ...
    'sanity_check_EOG:SampleCountMismatch')
end

function testNonfiniteDirectSignalFails(testCase)
[aligned_eeg_data, aligned_eeg_channel_names, ...
    signalHeader_all, signalCell_all, edf_Fs] = make_fixture;
invalid_index = strcmp({signalHeader_all.signal_labels}, 'E1');
signalCell_all{invalid_index}(1) = NaN;

verifyError(testCase, @() sanity_check_EOG( ...
    aligned_eeg_data, aligned_eeg_channel_names, ...
    signalHeader_all, signalCell_all, edf_Fs), ...
    'sanity_check_EOG:InvalidDirectSignal')
end

function testDirectSamplingRateMismatchFails(testCase)
[aligned_eeg_data, aligned_eeg_channel_names, ...
    signalHeader_all, signalCell_all, edf_Fs] = make_fixture;
m2_index = strcmp({signalHeader_all.signal_labels}, 'M2');
signalHeader_all(m2_index).samples_in_record = edf_Fs / 2;

verifyError(testCase, @() sanity_check_EOG( ...
    aligned_eeg_data, aligned_eeg_channel_names, ...
    signalHeader_all, signalCell_all, edf_Fs), ...
    'sanity_check_EOG:DirectSamplingRateMismatch')
end

function verify_trace( ...
    testCase, figure_handle, display_name, expected_x, expected_y)

line_handle = findall( ...
    figure_handle, 'Type', 'line', 'DisplayName', display_name);
verifyNumElements(testCase, line_handle, 1)
verifyEqual(testCase, line_handle.XData, expected_x, 'AbsTol', 1e-12)
verifyEqual(testCase, line_handle.YData, ...
    double(expected_y(:).'), 'AbsTol', 1e-12)

end

function signal_data = get_edf_signal( ...
    signalHeader_all, signalCell_all, channel_name)

signal_index = strcmp( ...
    {signalHeader_all.signal_labels}, channel_name);
signal_data = double(signalCell_all{signal_index}(:).');

end

function [aligned_eeg_data, aligned_eeg_channel_names, ...
    signalHeader_all, signalCell_all, edf_Fs] = make_fixture

aligned_eeg_channel_names = {'Fp1', 'VEOGL', 'M2'};
aligned_eeg_data = [ ...
    20:25; ...
    10:15; ...
    1:6];
edf_Fs = 2;
signal_labels = { ...
    'Noise', 'E1:M2', 'E1', 'M2', ...
    'E2:M2', 'E2', 'M1', 'E2:M1'};
for channel_i = numel(signal_labels):-1:1
    signalHeader_all(channel_i).signal_labels = ...
        signal_labels{channel_i};
    signalHeader_all(channel_i).samples_in_record = edf_Fs;
end
signalCell_all = { ...
    [91; 92], ...
    [901; 902; 903; 904; 905; 906], ...
    [31; 33; 36; 40; 45; 51], ...
    [11; 14; 18; 23; 29; 36], ...
    [801 802 803 804 805 806], ...
    single([21 25 30 36 43 51]), ...
    int16([1 3 6 10 15 21]), ...
    [701 702 703 704 705 706]};

end
