function tests = test_substitute_eeg_data
tests = functiontests(localfunctions);
end

function setupOnce(~)
project_path = fileparts(fileparts(mfilename('fullpath')));
addpath(project_path)
addpath(fullfile(project_path, 'helper_functions'))
end

function testNormalPathUsesClinicalMastoidCompensation(testCase)
[aligned_eeg_data, edf_eeg_channel_names, aligned_eeg_channel_names, ...
    signalHeader_all, signalCell_all, matched_sample_mask] = make_fixture;
signalCell_before = signalCell_all;

[report_output, signalCell_final, figure_handle, percent_outside_bounds] = ...
    capture_substitute_eeg_data( ...
    aligned_eeg_data, aligned_eeg_channel_names, edf_eeg_channel_names, ...
    signalHeader_all, signalCell_all, false, matched_sample_mask, false);

signal_labels = {signalHeader_all.signal_labels};
psg_eeg_channel_names = canonical_psg_eeg_channel_names;
reference_channel_names = reference_for_psg_eeg_channels( ...
    psg_eeg_channel_names);
for channel_i = 1:numel(psg_eeg_channel_names)
    active_index = strcmp( ...
        aligned_eeg_channel_names, psg_eeg_channel_names{channel_i});
    aligned_reference_index = strcmp( ...
        aligned_eeg_channel_names, reference_channel_names{channel_i});
    clinical_reference_index = strcmp( ...
        signal_labels, reference_channel_names{channel_i});
    edf_index = strcmp(signal_labels, psg_eeg_channel_names{channel_i});
    expected = ...
        aligned_eeg_data(active_index, :) - ...
        aligned_eeg_data(aligned_reference_index, :) + ...
        reshape(signalCell_all{clinical_reference_index}, 1, []);

    verifyEqual(testCase, signalCell_final{edf_index}, ...
        reshape(expected, size(signalCell_all{edf_index})))
    verifySize(testCase, signalCell_final{edf_index}, ...
        size(signalCell_all{edf_index}))
end

preserved_direct_names = {'M1', 'M2', 'E1', 'E2'};
for channel_i = 1:numel(preserved_direct_names)
    edf_index = strcmp(signal_labels, preserved_direct_names{channel_i});
    verifyEqual(testCase, signalCell_final{edf_index}, ...
        signalCell_all{edf_index})
    verifyClass(testCase, signalCell_final{edf_index}, ...
        class(signalCell_all{edf_index}))
end
verify_unrelated_cells_unchanged( ...
    testCase, signal_labels, signalCell_before, signalCell_final, ...
    psg_eeg_channel_names)
verifyEqual(testCase, signalCell_all, signalCell_before)
verifyEmpty(testCase, figure_handle)
verifyEqual(testCase, percent_outside_bounds, zeros(12, 1))

expected_derivations = [ ...
    "Aligned Fp1 - Aligned M2 + Clinical M2"; ...
    "Aligned Fp2 - Aligned M1 + Clinical M1"; ...
    "Aligned F3 - Aligned M2 + Clinical M2"; ...
    "Aligned F4 - Aligned M1 + Clinical M1"; ...
    "Aligned C3 - Aligned M2 + Clinical M2"; ...
    "Aligned C4 - Aligned M1 + Clinical M1"; ...
    "Aligned O1 - Aligned M2 + Clinical M2"; ...
    "Aligned O2 - Aligned M1 + Clinical M1"; ...
    "Clinical M1"; ...
    "Clinical M2"; ...
    "Clinical E1"; ...
    "Clinical E2"];
verify_report_rows(testCase, report_output, expected_derivations)
end

function testFaultyPathUsesOnlyAlignedHdSources(testCase)
[aligned_eeg_data, edf_eeg_channel_names, aligned_eeg_channel_names, ...
    signalHeader_all, signalCell_all, matched_sample_mask] = make_fixture;
signalCell_before = signalCell_all;

[report_output, signalCell_final, figure_handle, percent_outside_bounds] = ...
    capture_substitute_eeg_data( ...
    aligned_eeg_data, aligned_eeg_channel_names, edf_eeg_channel_names, ...
    signalHeader_all, signalCell_all, true, matched_sample_mask, false);

signal_labels = {signalHeader_all.signal_labels};
psg_eeg_channel_names = canonical_psg_eeg_channel_names;
for channel_i = 1:numel(psg_eeg_channel_names)
    aligned_index = strcmp( ...
        aligned_eeg_channel_names, psg_eeg_channel_names{channel_i});
    edf_index = strcmp(signal_labels, psg_eeg_channel_names{channel_i});
    verifyEqual(testCase, signalCell_final{edf_index}, ...
        reshape(aligned_eeg_data(aligned_index, :), ...
        size(signalCell_all{edf_index})))
    verifySize(testCase, signalCell_final{edf_index}, ...
        size(signalCell_all{edf_index}))
end

replacement_target_names = {'M1', 'M2', 'E1', 'E2'};
replacement_source_names = {'M1', 'M2', 'VEOGL', 'Fp2'};
for channel_i = 1:numel(replacement_target_names)
    aligned_index = strcmp( ...
        aligned_eeg_channel_names, replacement_source_names{channel_i});
    edf_index = strcmp(signal_labels, replacement_target_names{channel_i});
    verifyEqual(testCase, signalCell_final{edf_index}, ...
        reshape(aligned_eeg_data(aligned_index, :), ...
        size(signalCell_all{edf_index})))
    verifySize(testCase, signalCell_final{edf_index}, ...
        size(signalCell_all{edf_index}))
end
verify_unrelated_cells_unchanged( ...
    testCase, signal_labels, signalCell_before, signalCell_final, ...
    canonical_direct_channel_names)
verifyEqual(testCase, signalCell_all, signalCell_before)
verifyEmpty(testCase, figure_handle)
verifyEqual(testCase, percent_outside_bounds, zeros(12, 1))

expected_derivations = [ ...
    "Aligned Fp1"; ...
    "Aligned Fp2"; ...
    "Aligned F3"; ...
    "Aligned F4"; ...
    "Aligned C3"; ...
    "Aligned C4"; ...
    "Aligned O1"; ...
    "Aligned O2"; ...
    "Aligned M1"; ...
    "Aligned M2"; ...
    "Aligned VEOGL"; ...
    "Aligned Fp2"];
verify_report_rows(testCase, report_output, expected_derivations)
end

function testBoundsUseOnlyMatchedSamplesAndRemainUnrounded(testCase)
[aligned_eeg_data, edf_eeg_channel_names, aligned_eeg_channel_names, ...
    signalHeader_all, signalCell_all] = make_fixture(153);
matched_sample_mask = [true(1, 150), false(1, 3)];
aligned_eeg_data(:) = 0;
c3_index = strcmp(aligned_eeg_channel_names, 'C3');
f3_index = strcmp(aligned_eeg_channel_names, 'F3');
aligned_eeg_data(c3_index, 1:3) = [-1465, 1465, 1466];
aligned_eeg_data(c3_index, 151:153) = [5000, -5000, 0];
aligned_eeg_data(f3_index, 1:2) = [-1465, 1465];
aligned_eeg_data(f3_index, 151:153) = [5000, -5000, 0];

[report_output, signalCell_final, figure_handle, percent_outside_bounds] = ...
    capture_substitute_eeg_data( ...
    aligned_eeg_data, aligned_eeg_channel_names, edf_eeg_channel_names, ...
    signalHeader_all, signalCell_all, true, matched_sample_mask, false);

verifyEmpty(testCase, figure_handle)
verifyEqual(testCase, percent_outside_bounds(5), 100 / 150, ...
    'AbsTol', 1e-12)
verifyGreaterThan(testCase, ...
    abs(percent_outside_bounds(5) - ...
    round(percent_outside_bounds(5), 3)), 1e-4)
verifyEqual(testCase, percent_outside_bounds(3), 0)
verifyEqual(testCase, percent_outside_bounds([1:2 4 6:12]), zeros(10, 1))
verifyTrue(testCase, contains(report_output, '0.667'))
verifyTrue(testCase, contains(report_output, ...
    'matched samples only: 150/153, 98.039% coverage'))

signal_labels = {signalHeader_all.signal_labels};
c3_edf_index = strcmp(signal_labels, 'C3');
f3_edf_index = strcmp(signal_labels, 'F3');
verifyEqual(testCase, reshape(signalCell_final{c3_edf_index}, 1, []), ...
    aligned_eeg_data(c3_index, :))
verifyEqual(testCase, reshape(signalCell_final{f3_edf_index}, 1, []), ...
    aligned_eeg_data(f3_index, :))
end

function testMoreThanOnePercentOutsideBoundsFailsInsideHelper(testCase)
[aligned_eeg_data, edf_eeg_channel_names, aligned_eeg_channel_names, ...
    signalHeader_all, signalCell_all, matched_sample_mask] = ...
    make_fixture(100);
aligned_eeg_data(:) = 0;
c3_index = strcmp(aligned_eeg_channel_names, 'C3');
aligned_eeg_data(c3_index, 1:2) = 1466;

original_visibility = get(groot, 'defaultFigureVisible');
visibility_cleanup = onCleanup(@() set( ...
    groot, 'defaultFigureVisible', original_visibility));
set(groot, 'defaultFigureVisible', 'off')
figures_before = findall(groot, 'Type', 'figure');
caught_identifier = '';
caught_message = '';
try
    substitute_eeg_data( ...
        aligned_eeg_data, aligned_eeg_channel_names, ...
        edf_eeg_channel_names, signalHeader_all, signalCell_all, ...
        true, matched_sample_mask, true);
catch caught_error
    caught_identifier = caught_error.identifier;
    caught_message = caught_error.message;
end

verifyEqual(testCase, caught_identifier, ...
    'substitute_eeg_data:OutputOutsidePhysicalBounds')
verifyTrue(testCase, contains(caught_message, 'C3=2.000000%'))
verifyEqual(testCase, findall(groot, 'Type', 'figure'), figures_before)
end

function testExactlyOnePercentOutsideBoundsIsAllowed(testCase)
[aligned_eeg_data, edf_eeg_channel_names, aligned_eeg_channel_names, ...
    signalHeader_all, signalCell_all, matched_sample_mask] = ...
    make_fixture(100);
aligned_eeg_data(:) = 0;
c3_index = strcmp(aligned_eeg_channel_names, 'C3');
aligned_eeg_data(c3_index, 1) = 1466;

[~, ~, figure_handle, percent_outside_bounds] = ...
    capture_substitute_eeg_data( ...
    aligned_eeg_data, aligned_eeg_channel_names, edf_eeg_channel_names, ...
    signalHeader_all, signalCell_all, true, matched_sample_mask, false);

verifyEmpty(testCase, figure_handle)
verifyEqual(testCase, percent_outside_bounds(5), 1)
end

function testSanityPlotUsesAllFinalSamplesAndTwelveChannels(testCase)
[aligned_eeg_data, edf_eeg_channel_names, aligned_eeg_channel_names, ...
    signalHeader_all, signalCell_all, matched_sample_mask] = make_fixture;

original_visibility = get(groot, 'defaultFigureVisible');
visibility_cleanup = onCleanup(@() set( ...
    groot, 'defaultFigureVisible', original_visibility));
set(groot, 'defaultFigureVisible', 'off')
figures_before = findall(groot, 'Type', 'figure');

[~, ~, suppressed_figure] = capture_substitute_eeg_data( ...
    aligned_eeg_data, aligned_eeg_channel_names, edf_eeg_channel_names, ...
    signalHeader_all, signalCell_all, true, matched_sample_mask, false);
verifyEmpty(testCase, suppressed_figure)
verifyEqual(testCase, findall(groot, 'Type', 'figure'), figures_before)

[~, signalCell_final, figure_handle] = capture_substitute_eeg_data( ...
    aligned_eeg_data, aligned_eeg_channel_names, edf_eeg_channel_names, ...
    signalHeader_all, signalCell_all, true, matched_sample_mask);
figure_cleanup = onCleanup(@() delete(figure_handle));
figures_after = findall(groot, 'Type', 'figure');
verifyEqual(testCase, setdiff(figures_after, figures_before), figure_handle)

ax = findall(figure_handle, 'Type', 'axes', ...
    'Tag', 'substitute_eeg_data_sanity_axes');
verifyNumElements(testCase, ax, 1)
verifyEqual(testCase, ...
    char(ax.InteractionOptions.DatatipsSupported), 'off')
verifyEqual(testCase, char(ax.InteractionOptions.ZoomSupported), 'on')
verifyEqual(testCase, ax.YLim, [-1965, 1965])
verifyEqual(testCase, ax.FontSize, 14)
verifyEqual(testCase, ax.Title.FontSize, 18)
verifyEqual(testCase, string(ax.XLabel.String), "EDF sample index")

direct_channel_names = canonical_direct_channel_names;
trace_lines = findall(ax, 'Type', 'line');
verifyNumElements(testCase, trace_lines, 12)
verifyEqual(testCase, sort(string({trace_lines.DisplayName})), ...
    sort(string(direct_channel_names)))
signal_labels = {signalHeader_all.signal_labels};
for channel_i = 1:numel(direct_channel_names)
    trace = findall(ax, 'Type', 'line', ...
        'DisplayName', direct_channel_names{channel_i});
    edf_index = strcmp(signal_labels, direct_channel_names{channel_i});
    verifyEqual(testCase, trace.YData, ...
        reshape(signalCell_final{edf_index}, 1, []))
    verifyNumElements(testCase, trace.YData, numel(matched_sample_mask))
end

upper_bound = findall(figure_handle, ...
    'Tag', 'substitute_eeg_data_upper_clip_bound');
lower_bound = findall(figure_handle, ...
    'Tag', 'substitute_eeg_data_lower_clip_bound');
verifyNumElements(testCase, upper_bound, 1)
verifyNumElements(testCase, lower_bound, 1)
verifyEqual(testCase, upper_bound.Value, 1465)
verifyEqual(testCase, lower_bound.Value, -1465)
verifyEqual(testCase, upper_bound.LineStyle, ':')
verifyEqual(testCase, lower_bound.LineStyle, ':')

legend_handle = findall(figure_handle, 'Type', 'legend');
verifyNumElements(testCase, legend_handle, 1)
verifyEqual(testCase, sort(string(legend_handle.String)), ...
    sort(string(direct_channel_names)))
end

function testPhysicalDimensionMustBeUv(testCase)
[aligned_eeg_data, edf_eeg_channel_names, aligned_eeg_channel_names, ...
    signalHeader_all, signalCell_all, matched_sample_mask] = make_fixture;
e1_index = strcmp({signalHeader_all.signal_labels}, 'E1');
signalHeader_all(e1_index).physical_dimension = 'mV';

verifyError(testCase, @() substitute_eeg_data( ...
    aligned_eeg_data, aligned_eeg_channel_names, edf_eeg_channel_names, ...
    signalHeader_all, signalCell_all, false, matched_sample_mask, false), ...
    'substitute_eeg_data:InvalidPhysicalDimension')
end

function testSamplesPerRecordMustBeShared(testCase)
[aligned_eeg_data, edf_eeg_channel_names, aligned_eeg_channel_names, ...
    signalHeader_all, signalCell_all, matched_sample_mask] = make_fixture;
m2_index = strcmp({signalHeader_all.signal_labels}, 'M2');
signalHeader_all(m2_index).samples_in_record = 128;

verifyError(testCase, @() substitute_eeg_data( ...
    aligned_eeg_data, aligned_eeg_channel_names, edf_eeg_channel_names, ...
    signalHeader_all, signalCell_all, false, matched_sample_mask, false), ...
    'substitute_eeg_data:InconsistentSamplingRates')
end

function testPhysicalLimitsMustBeShared(testCase)
[aligned_eeg_data, edf_eeg_channel_names, aligned_eeg_channel_names, ...
    signalHeader_all, signalCell_all, matched_sample_mask] = make_fixture;
fp1_index = strcmp({signalHeader_all.signal_labels}, 'Fp1');
signalHeader_all(fp1_index).physical_max = 1400;

verifyError(testCase, @() substitute_eeg_data( ...
    aligned_eeg_data, aligned_eeg_channel_names, edf_eeg_channel_names, ...
    signalHeader_all, signalCell_all, false, matched_sample_mask, false), ...
    'substitute_eeg_data:InconsistentPhysicalLimits')
end

function testDigitalLimitsMustBeShared(testCase)
[aligned_eeg_data, edf_eeg_channel_names, aligned_eeg_channel_names, ...
    signalHeader_all, signalCell_all, matched_sample_mask] = make_fixture;
e2_index = strcmp({signalHeader_all.signal_labels}, 'E2');
signalHeader_all(e2_index).digital_max = 2047;

verifyError(testCase, @() substitute_eeg_data( ...
    aligned_eeg_data, aligned_eeg_channel_names, edf_eeg_channel_names, ...
    signalHeader_all, signalCell_all, false, matched_sample_mask, false), ...
    'substitute_eeg_data:InconsistentDigitalLimits')
end

function testMissingAndDuplicateEdfChannelsFail(testCase)
[aligned_eeg_data, edf_eeg_channel_names, aligned_eeg_channel_names, ...
    signalHeader_all, signalCell_all, matched_sample_mask] = make_fixture;
missing_index = strcmp({signalHeader_all.signal_labels}, 'E1');
missing_headers = signalHeader_all;
missing_cells = signalCell_all;
missing_headers(missing_index) = [];
missing_cells(missing_index) = [];
verifyError(testCase, @() substitute_eeg_data( ...
    aligned_eeg_data, aligned_eeg_channel_names, edf_eeg_channel_names, ...
    missing_headers, missing_cells, false, matched_sample_mask, false), ...
    'substitute_eeg_data:MissingEdfChannel')

duplicate_index = strcmp({signalHeader_all.signal_labels}, 'M2');
duplicate_headers = signalHeader_all;
duplicate_cells = signalCell_all;
duplicate_headers(end + 1) = signalHeader_all(duplicate_index);
duplicate_cells{end + 1} = signalCell_all{duplicate_index};
verifyError(testCase, @() substitute_eeg_data( ...
    aligned_eeg_data, aligned_eeg_channel_names, edf_eeg_channel_names, ...
    duplicate_headers, duplicate_cells, false, matched_sample_mask, false), ...
    'substitute_eeg_data:DuplicateEdfChannel')
end

function testMissingAndDuplicateAlignedChannelsFail(testCase)
[aligned_eeg_data, edf_eeg_channel_names, aligned_eeg_channel_names, ...
    signalHeader_all, signalCell_all, matched_sample_mask] = make_fixture;
missing_index = strcmp(aligned_eeg_channel_names, 'VEOGL');
missing_names = aligned_eeg_channel_names;
missing_data = aligned_eeg_data;
missing_names(missing_index) = [];
missing_data(missing_index, :) = [];
verifyError(testCase, @() substitute_eeg_data( ...
    missing_data, missing_names, edf_eeg_channel_names, ...
    signalHeader_all, signalCell_all, false, matched_sample_mask, false), ...
    'substitute_eeg_data:MissingEegChannel')

duplicate_names = [aligned_eeg_channel_names, {'M1'}];
duplicate_data = [aligned_eeg_data; ...
    aligned_eeg_data(strcmp(aligned_eeg_channel_names, 'M1'), :)];
verifyError(testCase, @() substitute_eeg_data( ...
    duplicate_data, duplicate_names, edf_eeg_channel_names, ...
    signalHeader_all, signalCell_all, false, matched_sample_mask, false), ...
    'substitute_eeg_data:DuplicateAlignedEegChannel')
end

function testWrongLengthDirectSignalFails(testCase)
[aligned_eeg_data, edf_eeg_channel_names, aligned_eeg_channel_names, ...
    signalHeader_all, signalCell_all, matched_sample_mask] = make_fixture;
e2_index = strcmp({signalHeader_all.signal_labels}, 'E2');
signalCell_all{e2_index} = signalCell_all{e2_index}(1:end-1);

verifyError(testCase, @() substitute_eeg_data( ...
    aligned_eeg_data, aligned_eeg_channel_names, edf_eeg_channel_names, ...
    signalHeader_all, signalCell_all, false, matched_sample_mask, false), ...
    'substitute_eeg_data:SampleCountMismatch')
end

function testInvalidMatchedMasksFail(testCase)
[aligned_eeg_data, edf_eeg_channel_names, aligned_eeg_channel_names, ...
    signalHeader_all, signalCell_all, matched_sample_mask] = make_fixture;

verifyError(testCase, @() substitute_eeg_data( ...
    aligned_eeg_data, aligned_eeg_channel_names, edf_eeg_channel_names, ...
    signalHeader_all, signalCell_all, false, ...
    double(matched_sample_mask), false), ...
    'substitute_eeg_data:InvalidMatchedMask')
verifyError(testCase, @() substitute_eeg_data( ...
    aligned_eeg_data, aligned_eeg_channel_names, edf_eeg_channel_names, ...
    signalHeader_all, signalCell_all, false, ...
    matched_sample_mask(1:end-1), false), ...
    'substitute_eeg_data:MatchedMaskLengthMismatch')
verifyError(testCase, @() substitute_eeg_data( ...
    aligned_eeg_data, aligned_eeg_channel_names, edf_eeg_channel_names, ...
    signalHeader_all, signalCell_all, false, ...
    false(size(matched_sample_mask)), false), ...
    'substitute_eeg_data:EmptyMatchedMask')
end

function testNonfiniteFinalDirectSignalFails(testCase)
[aligned_eeg_data, edf_eeg_channel_names, aligned_eeg_channel_names, ...
    signalHeader_all, signalCell_all, matched_sample_mask] = make_fixture;
e1_index = strcmp({signalHeader_all.signal_labels}, 'E1');
signalCell_all{e1_index}(1) = NaN;

verifyError(testCase, @() substitute_eeg_data( ...
    aligned_eeg_data, aligned_eeg_channel_names, edf_eeg_channel_names, ...
    signalHeader_all, signalCell_all, false, matched_sample_mask, false), ...
    'substitute_eeg_data:NonfiniteSignalData')
end

function verify_unrelated_cells_unchanged( ...
    testCase, signal_labels, signalCell_before, signalCell_after, ...
    overwritten_channel_names)

for signal_i = 1:numel(signal_labels)
    if ~ismember(signal_labels{signal_i}, overwritten_channel_names)
        verifyEqual(testCase, signalCell_after{signal_i}, ...
            signalCell_before{signal_i})
    end
end

end

function [report_output, signalCell_final, figure_handle, ...
    percent_outside_bounds] = capture_substitute_eeg_data(varargin)

substitution_call = @() substitute_eeg_data(varargin{:}); %#ok<NASGU>
[report_output, signalCell_final, figure_handle, ...
    percent_outside_bounds] = evalc('substitution_call()');

end

function verify_report_rows(testCase, report_output, expected_derivations)

channel_names = canonical_direct_channel_names;
verifyTrue(testCase, contains(report_output, ...
    'Final output EDF channel bounds report'))
verifyTrue(testCase, contains(report_output, 'OutputDerivation'))
verifyTrue(testCase, contains(report_output, ...
    'PercentOutsideBoundsWithinMatchedSamples (%)'))
verifyFalse(testCase, contains(report_output, '<html>'))

row_position = zeros(size(channel_names));
for channel_i = 1:numel(channel_names)
    channel_pattern = regexptranslate( ...
        'escape', ['"' channel_names{channel_i} '"']);
    derivation_pattern = regexptranslate( ...
        'escape', ['"' char(expected_derivations(channel_i)) '"']);
    row_pattern = [channel_pattern '\s+' derivation_pattern];
    row_position(channel_i) = regexp( ...
        report_output, row_pattern, 'once');
    verifyNotEmpty(testCase, row_position(channel_i))
end
verifyGreaterThan(testCase, diff(row_position), zeros(1, 11))

end

function channel_names = canonical_psg_eeg_channel_names

channel_names = { ...
    'Fp1', 'Fp2', 'F3', 'F4', 'C3', 'C4', 'O1', 'O2'};

end

function channel_names = canonical_direct_channel_names

channel_names = [ ...
    canonical_psg_eeg_channel_names, {'M1', 'M2', 'E1', 'E2'}];

end

function reference_channel_names = reference_for_psg_eeg_channels( ...
    psg_eeg_channel_names)

reference_rule_active_names = { ...
    'Fp1', 'Fp2', 'F3', 'F4', 'C3', 'C4', 'O1', 'O2'};
reference_rule_mastoid_names = { ...
    'M2', 'M1', 'M2', 'M1', 'M2', 'M1', 'M2', 'M1'};
[~, reference_rule_index] = ismember( ...
    psg_eeg_channel_names, reference_rule_active_names);
reference_channel_names = ...
    reference_rule_mastoid_names(reference_rule_index);

end

function [aligned_eeg_data, edf_eeg_channel_names, ...
    aligned_eeg_channel_names, signalHeader_all, signalCell_all, ...
    matched_sample_mask] = make_fixture(n_samples)

if nargin < 1
    n_samples = 6;
end

edf_eeg_channel_names = { ...
    'Fp1', 'C4', 'O1', 'F3', 'Fp2', 'O2', 'F4', 'C3'};
aligned_eeg_channel_names = [ ...
    {'VEOGL', 'M2'}, edf_eeg_channel_names, {'M1'}];
aligned_eeg_data = reshape( ...
    1:(numel(aligned_eeg_channel_names) * n_samples), ...
    numel(aligned_eeg_channel_names), n_samples);
matched_sample_mask = true(1, n_samples);

signal_labels = { ...
    'PAP Pres', 'E1', 'F4:M1', 'Fp1', 'E2', 'M2', ...
    'Fp2:M1', 'C3', 'M1', 'C3:M2', 'C4', 'Fp2', ...
    'O1:M2', 'O1', 'F3', 'F4', 'Fp1:M2', 'F3:M2', ...
    'C4:M1', 'O2', 'O2:M1', ...
    'E2:M1', 'E1:M2', 'E2:M2', 'EDF Annotations'};
for channel_i = numel(signal_labels):-1:1
    signalHeader_all(channel_i).signal_labels = signal_labels{channel_i};
    signalHeader_all(channel_i).physical_dimension = 'uV';
    signalHeader_all(channel_i).physical_min = -1465;
    signalHeader_all(channel_i).physical_max = 1465;
    signalHeader_all(channel_i).digital_min = -32768;
    signalHeader_all(channel_i).digital_max = 32767;
    signalHeader_all(channel_i).samples_in_record = 256;
end

signalCell_all = cell(1, numel(signal_labels));
for channel_i = 1:numel(signal_labels)
    channel_data = channel_i * 5 + (1:n_samples);
    if mod(channel_i, 2) == 0
        channel_data = channel_data.';
    end
    signalCell_all{channel_i} = channel_data;
end

signalCell_all{strcmp(signal_labels, 'PAP Pres')} = single([10; 20]);
signalCell_all{strcmp(signal_labels, 'E1')} = 101:(100 + n_samples);
signalCell_all{strcmp(signal_labels, 'E2')} = ...
    single((201:(200 + n_samples)).');
signalCell_all{strcmp(signal_labels, 'M1')} = ...
    (51:(50 + n_samples)).';
signalCell_all{strcmp(signal_labels, 'M2')} = ...
    (-50:(-51 + n_samples)).';
signalCell_all{end} = uint8([1, 2, 3]);

for channel_i = 1:numel(edf_eeg_channel_names)
    edf_index = strcmp( ...
        signal_labels, edf_eeg_channel_names{channel_i});
    target_data = 100 * channel_i + (1:n_samples);
    if mod(channel_i, 2) == 1
        target_data = target_data.';
    end
    signalCell_all{edf_index} = target_data;
end

end
