function tests = test_substitute_eeg_data
tests = functiontests(localfunctions);
end

function setupOnce(~)
project_path = fileparts(fileparts(mfilename('fullpath')));
addpath(project_path)
addpath(fullfile(project_path, 'helper_functions'))
end

function testSubstitutesOnlyEightGroundedScalpChannelsByName(testCase)
[final_eeg_data, edf_eeg_channel_names, aligned_eeg_channel_names, ...
    signalHeader_all, signalCell_all] = make_fixture;

signalCell_final = substitute_eeg_data( ...
    final_eeg_data, aligned_eeg_channel_names, ...
    edf_eeg_channel_names, ...
    signalHeader_all, signalCell_all, false);

signal_labels = {signalHeader_all.signal_labels};
reference_channel_names = reference_for_scalp_channels( ...
    edf_eeg_channel_names);

for channel_i = 1:numel(edf_eeg_channel_names)
    active_index = strcmp( ...
        aligned_eeg_channel_names, edf_eeg_channel_names{channel_i});
    reference_index = strcmp( ...
        aligned_eeg_channel_names, reference_channel_names{channel_i});
    clinical_reference_index = strcmp( ...
        signal_labels, reference_channel_names{channel_i});
    edf_index = strcmp( ...
        signal_labels, edf_eeg_channel_names{channel_i});
    expected = ...
        final_eeg_data(active_index, :) - ...
        final_eeg_data(reference_index, :) + ...
        reshape(signalCell_all{clinical_reference_index}, 1, []);

    verifyEqual(testCase, signalCell_final{edf_index}, ...
        reshape(expected, size(signalCell_all{edf_index})))
    verifyClass(testCase, signalCell_final{edf_index}, 'double')
end

preserved_channel_names = { ...
    'E1', 'E2', 'M1', 'M2', ...
    'Fp1:M2', 'Fp2:M1', 'F3:M2', 'F4:M1', ...
    'C3:M2', 'C4:M1', 'O1:M2', 'O2:M1', ...
    'E2:M1', 'E1:M2', 'E2:M2'};
verifyTrue(testCase, all(ismember( ...
    preserved_channel_names, signal_labels)))

for channel_i = 1:numel(signal_labels)
    if ~ismember(signal_labels{channel_i}, edf_eeg_channel_names)
        verifyEqual(testCase, signalCell_final{channel_i}, ...
            signalCell_all{channel_i})
    end
end
verifySize(testCase, signalCell_final, size(signalCell_all))
end

function testReportsStrictOutsideBoundPercentagesWithoutClamping(testCase)
[final_eeg_data, edf_eeg_channel_names, aligned_eeg_channel_names, ...
    signalHeader_all, signalCell_all] = make_fixture(7);

for channel_i = 1:numel(signalHeader_all)
    signalHeader_all(channel_i).physical_min = -1700;
    signalHeader_all(channel_i).physical_max = 1750;
end
final_eeg_data(:) = 0;
signal_labels = {signalHeader_all.signal_labels};
final_eeg_data(strcmp(aligned_eeg_channel_names, 'M1'), :) = 100;
final_eeg_data(strcmp(aligned_eeg_channel_names, 'M2'), :) = -200;
signalCell_all{strcmp(signal_labels, 'M1')} = 500 * ones(7, 1);
signalCell_all{strcmp(signal_labels, 'M2')} = -700 * ones(7, 1);
expected_percent = round((0:7)' * 100 / 7, 3);
expected_output = zeros(8, 7);
reference_channel_names = reference_for_scalp_channels( ...
    edf_eeg_channel_names);

for channel_i = 1:numel(edf_eeg_channel_names)
    n_outside = channel_i - 1;
    channel_data = zeros(1, 7);
    if n_outside == 0
        channel_data(1:2) = [-1700, 1750];
    else
        channel_data(1:n_outside) = 1751;
        channel_data(1) = -1701;
    end
    active_index = strcmp( ...
        aligned_eeg_channel_names, edf_eeg_channel_names{channel_i});
    aligned_reference_index = strcmp( ...
        aligned_eeg_channel_names, reference_channel_names{channel_i});
    clinical_reference_index = strcmp( ...
        signal_labels, reference_channel_names{channel_i});
    final_eeg_data(active_index, :) = ...
        channel_data + ...
        final_eeg_data(aligned_reference_index, :) - ...
        reshape(signalCell_all{clinical_reference_index}, 1, []);
    expected_output(channel_i, :) = channel_data;
end
fp1_active_index = strcmp(aligned_eeg_channel_names, 'Fp1');
verifyEqual(testCase, sum( ...
    final_eeg_data(fp1_active_index, :) < -1700 | ...
    final_eeg_data(fp1_active_index, :) > 1750), 1)

[report_output, signalCell_final] = evalc([ ...
    'substitute_eeg_data(final_eeg_data, ' ...
    'aligned_eeg_channel_names, edf_eeg_channel_names, ' ...
    'signalHeader_all, signalCell_all, false)']);

for channel_i = 1:numel(edf_eeg_channel_names)
    report_pattern = sprintf( ...
        '"%s"\\s+"%s"\\s+%g', ...
        edf_eeg_channel_names{channel_i}, ...
        [edf_eeg_channel_names{channel_i} ':' ...
         reference_channel_names{channel_i}], ...
        expected_percent(channel_i));
    verifyNotEmpty(testCase, regexp( ...
        report_output, report_pattern, 'once'))

    edf_index = strcmp( ...
        signal_labels, edf_eeg_channel_names{channel_i});
    verifyEqual(testCase, ...
        reshape(signalCell_final{edf_index}, 1, []), ...
        expected_output(channel_i, :))
end
verifyTrue(testCase, contains(report_output, ...
    'EDF scalp substitution clipping report (-1700 to 1750 uV)'))
verifyTrue(testCase, contains(report_output, ...
    'PercentOutsideBounds (%)'))
verifyEqual(testCase, ...
    signalCell_final{strcmp(signal_labels, 'M1')}, ...
    signalCell_all{strcmp(signal_labels, 'M1')})
verifyEqual(testCase, ...
    signalCell_final{strcmp(signal_labels, 'M2')}, ...
    signalCell_all{strcmp(signal_labels, 'M2')})
end

function testSanityPlotDefaultsOnAndFalseSuppressesIt(testCase)
[final_eeg_data, edf_eeg_channel_names, aligned_eeg_channel_names, ...
    signalHeader_all, signalCell_all] = make_fixture;

original_visibility = get(groot, 'defaultFigureVisible');
visibility_cleanup = onCleanup(@() set( ...
    groot, 'defaultFigureVisible', original_visibility));
set(groot, 'defaultFigureVisible', 'off')
figures_before = findall(groot, 'Type', 'figure');

substitute_eeg_data( ...
    final_eeg_data, aligned_eeg_channel_names, ...
    edf_eeg_channel_names, ...
    signalHeader_all, signalCell_all, false);
verifyEqual(testCase, ...
    findall(groot, 'Type', 'figure'), figures_before)

signalCell_final = substitute_eeg_data( ...
    final_eeg_data, aligned_eeg_channel_names, ...
    edf_eeg_channel_names, ...
    signalHeader_all, signalCell_all);
figures_after = findall(groot, 'Type', 'figure');
new_figures = setdiff(figures_after, figures_before);
figure_cleanup = onCleanup(@() delete(new_figures));
figure_handle = new_figures;

verifyNumElements(testCase, new_figures, 1)
verifyNumElements(testCase, figure_handle, 1)
verifyEmpty(testCase, figure_handle.Name)
verifyEmpty(testCase, figure_handle.Tag)
ax = findall(figure_handle, 'Type', 'axes', ...
    'Tag', 'substitute_eeg_data_sanity_axes');
verifyNumElements(testCase, ax, 1)
verifyEqual(testCase, ...
    char(ax.InteractionOptions.DatatipsSupported), 'off')
verifyEqual(testCase, ...
    char(ax.InteractionOptions.ZoomSupported), 'on')
verifyEqual(testCase, ax.YLim, [-2300, 2300])
verifyEqual(testCase, ax.FontSize, 14)
verifyEqual(testCase, ax.Title.FontSize, 18)
verifyEqual(testCase, string(ax.XLabel.String), "EDF sample index")

trace_lines = findall(ax, 'Type', 'line');
verifyNumElements(testCase, trace_lines, 8)
verifyEqual(testCase, ...
    sort(string({trace_lines.DisplayName})), ...
    sort(string(edf_eeg_channel_names)))
signal_labels = {signalHeader_all.signal_labels};
for channel_i = 1:numel(edf_eeg_channel_names)
    trace = findall(ax, 'Type', 'line', ...
        'DisplayName', edf_eeg_channel_names{channel_i});
    edf_index = strcmp( ...
        signal_labels, edf_eeg_channel_names{channel_i});
    verifyEqual(testCase, trace.YData, ...
        reshape(signalCell_final{edf_index}, 1, []))
end

upper_bound = findall(figure_handle, ...
    'Tag', 'substitute_eeg_data_upper_clip_bound');
lower_bound = findall(figure_handle, ...
    'Tag', 'substitute_eeg_data_lower_clip_bound');
verifyNumElements(testCase, upper_bound, 1)
verifyNumElements(testCase, lower_bound, 1)
verifyEqual(testCase, upper_bound.Value, 1800)
verifyEqual(testCase, lower_bound.Value, -1800)
verifyEqual(testCase, upper_bound.LineStyle, ':')
verifyEqual(testCase, lower_bound.LineStyle, ':')

legend_handle = findall(figure_handle, 'Type', 'legend');
verifyNumElements(testCase, legend_handle, 1)
verifyEqual(testCase, ...
    sort(string(legend_handle.String)), ...
    sort(string(edf_eeg_channel_names)))
end

function testChannelCountMismatchFails(testCase)
[final_eeg_data, edf_eeg_channel_names, aligned_eeg_channel_names, ...
    signalHeader_all, signalCell_all] = make_fixture;

verifyError(testCase, @() substitute_eeg_data( ...
    final_eeg_data(1:end-1, :), aligned_eeg_channel_names, ...
    edf_eeg_channel_names, ...
    signalHeader_all, signalCell_all, false), ...
    'substitute_eeg_data:ChannelCountMismatch')
end

function testMissingAlignedMastoidFails(testCase)
[final_eeg_data, edf_eeg_channel_names, aligned_eeg_channel_names, ...
    signalHeader_all, signalCell_all] = make_fixture;
missing_index = strcmp(aligned_eeg_channel_names, 'M2');
aligned_eeg_channel_names(missing_index) = [];
final_eeg_data(missing_index, :) = [];

verifyError(testCase, @() substitute_eeg_data( ...
    final_eeg_data, aligned_eeg_channel_names, edf_eeg_channel_names, ...
    signalHeader_all, signalCell_all, false), ...
    'substitute_eeg_data:MissingEegChannel')
end

function testMissingAlignedScalpChannelFails(testCase)
[final_eeg_data, edf_eeg_channel_names, aligned_eeg_channel_names, ...
    signalHeader_all, signalCell_all] = make_fixture;
missing_index = strcmp(aligned_eeg_channel_names, 'Fp1');
aligned_eeg_channel_names(missing_index) = [];
final_eeg_data(missing_index, :) = [];

verifyError(testCase, @() substitute_eeg_data( ...
    final_eeg_data, aligned_eeg_channel_names, edf_eeg_channel_names, ...
    signalHeader_all, signalCell_all, false), ...
    'substitute_eeg_data:MissingEegChannel')
end

function testMissingGroundedEdfChannelFails(testCase)
[final_eeg_data, edf_eeg_channel_names, aligned_eeg_channel_names, ...
    signalHeader_all, signalCell_all] = make_fixture;
missing_index = strcmp({signalHeader_all.signal_labels}, 'Fp1');
signalHeader_all(missing_index) = [];
signalCell_all(missing_index) = [];

verifyError(testCase, @() substitute_eeg_data( ...
    final_eeg_data, aligned_eeg_channel_names, edf_eeg_channel_names, ...
    signalHeader_all, signalCell_all, false), ...
    'substitute_eeg_data:MissingEdfChannel')
end

function testMissingClinicalMastoidFails(testCase)
[final_eeg_data, edf_eeg_channel_names, aligned_eeg_channel_names, ...
    signalHeader_all, signalCell_all] = make_fixture;
missing_index = strcmp({signalHeader_all.signal_labels}, 'M2');
signalHeader_all(missing_index) = [];
signalCell_all(missing_index) = [];

verifyError(testCase, @() substitute_eeg_data( ...
    final_eeg_data, aligned_eeg_channel_names, edf_eeg_channel_names, ...
    signalHeader_all, signalCell_all, false), ...
    'substitute_eeg_data:MissingEdfChannel')
end

function testDuplicateGroundedEdfChannelFails(testCase)
[final_eeg_data, edf_eeg_channel_names, aligned_eeg_channel_names, ...
    signalHeader_all, signalCell_all] = make_fixture;
duplicate_index = strcmp({signalHeader_all.signal_labels}, 'Fp1');
signalHeader_all(end + 1) = signalHeader_all(duplicate_index);
signalCell_all{end + 1} = signalCell_all{duplicate_index};

verifyError(testCase, @() substitute_eeg_data( ...
    final_eeg_data, aligned_eeg_channel_names, edf_eeg_channel_names, ...
    signalHeader_all, signalCell_all, false), ...
    'substitute_eeg_data:DuplicateEdfChannel')
end

function testDuplicateClinicalMastoidFails(testCase)
[final_eeg_data, edf_eeg_channel_names, aligned_eeg_channel_names, ...
    signalHeader_all, signalCell_all] = make_fixture;
duplicate_index = strcmp({signalHeader_all.signal_labels}, 'M2');
signalHeader_all(end + 1) = signalHeader_all(duplicate_index);
signalCell_all{end + 1} = signalCell_all{duplicate_index};

verifyError(testCase, @() substitute_eeg_data( ...
    final_eeg_data, aligned_eeg_channel_names, edf_eeg_channel_names, ...
    signalHeader_all, signalCell_all, false), ...
    'substitute_eeg_data:DuplicateEdfChannel')
end

function testClinicalMastoidSampleCountMismatchFails(testCase)
[final_eeg_data, edf_eeg_channel_names, aligned_eeg_channel_names, ...
    signalHeader_all, signalCell_all] = make_fixture;
short_index = strcmp({signalHeader_all.signal_labels}, 'M2');
signalCell_all{short_index} = signalCell_all{short_index}(1:end-1);

verifyError(testCase, @() substitute_eeg_data( ...
    final_eeg_data, aligned_eeg_channel_names, edf_eeg_channel_names, ...
    signalHeader_all, signalCell_all, false), ...
    'substitute_eeg_data:SampleCountMismatch')
end

function testInconsistentPhysicalLimitsFail(testCase)
[final_eeg_data, edf_eeg_channel_names, aligned_eeg_channel_names, ...
    signalHeader_all, signalCell_all] = make_fixture;
fp1_index = strcmp({signalHeader_all.signal_labels}, 'Fp1');
signalHeader_all(fp1_index).physical_max = 1700;

verifyError(testCase, @() substitute_eeg_data( ...
    final_eeg_data, aligned_eeg_channel_names, edf_eeg_channel_names, ...
    signalHeader_all, signalCell_all, false), ...
    'substitute_eeg_data:InconsistentPhysicalLimits')
end

function [final_eeg_data, edf_eeg_channel_names, ...
    aligned_eeg_channel_names, ...
    signalHeader_all, signalCell_all] = make_fixture(n_samples)

if nargin < 1
    n_samples = 5;
end

edf_eeg_channel_names = { ...
    'Fp1', 'C4', 'O1', 'F3', 'Fp2', 'O2', 'F4', 'C3'};
aligned_eeg_channel_names = [ ...
    {'VEOGL', 'M2'}, edf_eeg_channel_names, {'M1'}];
final_eeg_data = reshape( ...
    1:(numel(aligned_eeg_channel_names) * n_samples), ...
    numel(aligned_eeg_channel_names), n_samples);

signal_labels = { ...
    'PAP Pres', 'E1', 'F4:M1', 'Fp1', 'E2', 'M2', ...
    'Fp2:M1', 'C3', 'M1', 'C3:M2', 'C4', 'Fp2', ...
    'O1:M2', 'O1', 'F3', 'F4', 'Fp1:M2', 'F3:M2', ...
    'C4:M1', 'O2', 'O2:M1', ...
    'E2:M1', 'E1:M2', 'E2:M2', 'EDF Annotations'};
for channel_i = numel(signal_labels):-1:1
    signalHeader_all(channel_i).signal_labels = signal_labels{channel_i};
    signalHeader_all(channel_i).physical_min = -1800;
    signalHeader_all(channel_i).physical_max = 1800;
    signalHeader_all(channel_i).digital_min = -32768;
    signalHeader_all(channel_i).digital_max = 32767;
end

signalCell_all = cell(1, numel(signal_labels));
for channel_i = 1:numel(signal_labels)
    channel_data = -(channel_i * 100 + (1:n_samples));
    if mod(channel_i, 2) == 0
        channel_data = channel_data.';
    end
    signalCell_all{channel_i} = channel_data;
end

signalCell_all{strcmp(signal_labels, 'PAP Pres')} = single([10; 20]);
signalCell_all{strcmp(signal_labels, 'E1')} = ...
    int16(101:(100 + n_samples));
signalCell_all{strcmp(signal_labels, 'E2')} = ...
    single((201:(200 + n_samples)).');
signalCell_all{strcmp(signal_labels, 'M1')} = ...
    (100:100:(100 * n_samples)).';
signalCell_all{strcmp(signal_labels, 'M2')} = ...
    (-50:10:(-50 + 10 * (n_samples - 1))).';
signalCell_all{end} = uint8([1, 2, 3]);

for channel_i = 1:numel(edf_eeg_channel_names)
    edf_index = strcmp( ...
        signal_labels, edf_eeg_channel_names{channel_i});
    target_data = 1000 * channel_i + (1:n_samples);
    if mod(channel_i, 2) == 1
        target_data = target_data.';
    end
    signalCell_all{edf_index} = target_data;
end

end

function reference_channel_names = reference_for_scalp_channels( ...
    scalp_channel_names)

reference_rule_active_names = { ...
    'Fp1', 'Fp2', 'F3', 'F4', 'C3', 'C4', 'O1', 'O2'};
reference_rule_mastoid_names = { ...
    'M2', 'M1', 'M2', 'M1', 'M2', 'M1', 'M2', 'M1'};
[~, reference_rule_index] = ismember( ...
    scalp_channel_names, reference_rule_active_names);
reference_channel_names = ...
    reference_rule_mastoid_names(reference_rule_index);

end
