function tests = test_substitute_eeg_data
tests = functiontests(localfunctions);
end

function setupOnce(~)
project_path = fileparts(fileparts(mfilename('fullpath')));
addpath(project_path)
addpath(fullfile(project_path, 'helper_functions'))
end

function testSubstitutesDirectAndReferencedChannelsByName(testCase)
[final_eeg_data, edf_eeg_channel_names, aligned_eeg_channel_names, ...
    signalHeader_all, signalCell_all] = make_fixture;

signalCell_final = substitute_eeg_data( ...
    final_eeg_data, edf_eeg_channel_names, aligned_eeg_channel_names, ...
    signalHeader_all, signalCell_all);

signal_labels = {signalHeader_all.signal_labels};
for channel_i = 1:numel(edf_eeg_channel_names)
    aligned_index = find(strcmp( ...
        aligned_eeg_channel_names, edf_eeg_channel_names{channel_i}));
    edf_index = find(strcmp( ...
        signal_labels, edf_eeg_channel_names{channel_i}));
    verifyEqual(testCase, signalCell_final{edf_index}, ...
        final_eeg_data(aligned_index, :).')
    verifyClass(testCase, signalCell_final{edf_index}, 'single')
end

referenced_channel_names = { ...
    'Fp1:M2', 'Fp2:M1', 'F3:M2', 'F4:M1', ...
    'C3:M2', 'C4:M1', 'O1:M2', 'O2:M1'};
active_channel_names = { ...
    'Fp1', 'Fp2', 'F3', 'F4', 'C3', 'C4', 'O1', 'O2'};
reference_channel_names = { ...
    'M2', 'M1', 'M2', 'M1', 'M2', 'M1', 'M2', 'M1'};

for channel_i = 1:numel(referenced_channel_names)
    active_index = find(strcmp( ...
        aligned_eeg_channel_names, active_channel_names{channel_i}));
    reference_index = find(strcmp( ...
        aligned_eeg_channel_names, reference_channel_names{channel_i}));
    edf_index = find(strcmp( ...
        signal_labels, referenced_channel_names{channel_i}));
    expected = final_eeg_data(active_index, :) - ...
        final_eeg_data(reference_index, :);
    verifyEqual(testCase, signalCell_final{edf_index}, expected.')
    verifyClass(testCase, signalCell_final{edf_index}, 'single')
end

verifyEqual(testCase, signalCell_final{1}, signalCell_all{1})
verifyEqual(testCase, signalCell_final{end}, signalCell_all{end})
unchanged_eog_channel_names = {'E2:M1', 'E1:M2', 'E2:M2'};
for channel_i = 1:numel(unchanged_eog_channel_names)
    edf_index = find(strcmp( ...
        signal_labels, unchanged_eog_channel_names{channel_i}));
    verifyEqual(testCase, signalCell_final{edf_index}, ...
        signalCell_all{edf_index})
end
verifySize(testCase, signalCell_final, size(signalCell_all))
end

function testChannelCountMismatchFails(testCase)
[final_eeg_data, edf_eeg_channel_names, aligned_eeg_channel_names, ...
    signalHeader_all, signalCell_all] = make_fixture;

verifyError(testCase, @() substitute_eeg_data( ...
    final_eeg_data(1:end-1, :), edf_eeg_channel_names, ...
    aligned_eeg_channel_names, ...
    signalHeader_all, signalCell_all), ...
    'substitute_eeg_data:ChannelCountMismatch')
end

function testMissingSourceChannelFails(testCase)
[final_eeg_data, edf_eeg_channel_names, aligned_eeg_channel_names, ...
    signalHeader_all, signalCell_all] = make_fixture;
edf_eeg_channel_names{strcmp(edf_eeg_channel_names, 'M2')} = 'E1';
aligned_eeg_channel_names{strcmp( ...
    aligned_eeg_channel_names, 'M2')} = 'E1';

verifyError(testCase, @() substitute_eeg_data( ...
    final_eeg_data, edf_eeg_channel_names, aligned_eeg_channel_names, ...
    signalHeader_all, signalCell_all), ...
    'substitute_eeg_data:MissingEegChannel')
end

function testMissingEdfChannelInAlignedDataFails(testCase)
[final_eeg_data, edf_eeg_channel_names, aligned_eeg_channel_names, ...
    signalHeader_all, signalCell_all] = make_fixture;
missing_index = strcmp(aligned_eeg_channel_names, 'M2');
aligned_eeg_channel_names(missing_index) = [];
final_eeg_data(missing_index, :) = [];

verifyError(testCase, @() substitute_eeg_data( ...
    final_eeg_data, edf_eeg_channel_names, aligned_eeg_channel_names, ...
    signalHeader_all, signalCell_all), ...
    '')
end

function testMissingEdfChannelFails(testCase)
[final_eeg_data, edf_eeg_channel_names, aligned_eeg_channel_names, ...
    signalHeader_all, signalCell_all] = make_fixture;
missing_index = strcmp({signalHeader_all.signal_labels}, 'Fp1:M2');
signalHeader_all(missing_index) = [];
signalCell_all(missing_index) = [];

verifyError(testCase, @() substitute_eeg_data( ...
    final_eeg_data, edf_eeg_channel_names, aligned_eeg_channel_names, ...
    signalHeader_all, signalCell_all), ...
    'substitute_eeg_data:MissingEdfChannel')
end

function testDuplicateEdfChannelFails(testCase)
[final_eeg_data, edf_eeg_channel_names, aligned_eeg_channel_names, ...
    signalHeader_all, signalCell_all] = make_fixture;
duplicate_index = strcmp({signalHeader_all.signal_labels}, 'Fp1:M2');
signalHeader_all(end + 1) = signalHeader_all(duplicate_index);
signalCell_all{end + 1} = signalCell_all{duplicate_index};

verifyError(testCase, @() substitute_eeg_data( ...
    final_eeg_data, edf_eeg_channel_names, aligned_eeg_channel_names, ...
    signalHeader_all, signalCell_all), ...
    'substitute_eeg_data:DuplicateEdfChannel')
end

function testSampleCountMismatchFails(testCase)
[final_eeg_data, edf_eeg_channel_names, aligned_eeg_channel_names, ...
    signalHeader_all, signalCell_all] = make_fixture;
short_index = strcmp({signalHeader_all.signal_labels}, 'C3:M2');
signalCell_all{short_index} = signalCell_all{short_index}(1:end-1);

verifyError(testCase, @() substitute_eeg_data( ...
    final_eeg_data, edf_eeg_channel_names, aligned_eeg_channel_names, ...
    signalHeader_all, signalCell_all), ...
    'substitute_eeg_data:SampleCountMismatch')
end

function [final_eeg_data, edf_eeg_channel_names, ...
    aligned_eeg_channel_names, ...
    signalHeader_all, signalCell_all] = make_fixture
edf_eeg_channel_names = { ...
    'M2', 'Fp1', 'C4', 'O1', 'F3', ...
    'M1', 'Fp2', 'O2', 'F4', 'C3'};
aligned_eeg_channel_names = [{'VEOGL'}, edf_eeg_channel_names];
n_samples = 5;
final_eeg_data = single(reshape( ...
    1:(numel(aligned_eeg_channel_names) * n_samples), ...
    numel(aligned_eeg_channel_names), n_samples));

signal_labels = { ...
    'PAP Pres', 'E2:M1', 'E1:M2', 'E2:M2', ...
    'F4:M1', 'C4:M1', 'O2:M1', ...
    'Fp1', 'Fp2', 'C3', 'C4', 'M1', 'M2', ...
    'O1', 'O2', 'F3', 'F4', 'Fp1:M2', 'Fp2:M1', ...
    'F3:M2', 'C3:M2', 'O1:M2', 'EDF Annotations'};
for channel_i = numel(signal_labels):-1:1
    signalHeader_all(channel_i).signal_labels = signal_labels{channel_i};
end

signalCell_all = repmat( ...
    {single(-ones(n_samples, 1))}, 1, numel(signal_labels));
signalCell_all{1} = [10; 20];
signalCell_all{strcmp(signal_labels, 'E2:M1')} = ...
    double([101 102 103 104 105]);
signalCell_all{strcmp(signal_labels, 'E1:M2')} = ...
    single([201; 202; 203; 204; 205]);
signalCell_all{strcmp(signal_labels, 'E2:M2')} = ...
    int16([301 302 303 304 305]);
signalCell_all{end} = uint8([1 2 3]);
end
