function [final_eeg_data, matched_edf_sample_mask] = ...
    concatenate_eeg_segments( ...
    eeg_segment_data, matched_segments, edf_input, ...
    aligned_eeg_channel_names)
%CONCATENATE_EEG_SEGMENTS Place aligned channels on the EDF scalp timeline.
%   Unmatched samples before, between, and after the segments remain zero,
%   including auxiliary channels that will not be substituted into the EDF.
%   MATCHED_EDF_SAMPLE_MASK is a logical row vector that is true for every
%   inclusive EDF scalp-sample range occupied by a matched segment.

n_segments = height(matched_segments);
assert(n_segments > 0 && numel(eeg_segment_data) == n_segments, ...
    'concatenate_eeg_segments:SegmentCountMismatch', ...
    'The EEG cell array must contain one entry per matched segment.')

total_sample_count = edf_input.edf_eeg_total_sample_count;

assert(isscalar(total_sample_count) && isfinite(total_sample_count) && ...
    total_sample_count > 0 && total_sample_count == round(total_sample_count), ...
    'concatenate_eeg_segments:InvalidTotalSampleCount', ...
    'The total EDF scalp sample count must be a positive integer.')

scalp_samples_per_trigger_sample = edf_input.Fs / edf_input.trigger_Fs;
ratio_tolerance = 10 * eps(max(abs( ...
    scalp_samples_per_trigger_sample), 1));
assert(abs(scalp_samples_per_trigger_sample - ...
    round(scalp_samples_per_trigger_sample)) <= ratio_tolerance, ...
    'concatenate_eeg_segments:NonintegerEdfRateRatio', ...
    ['The EDF scalp sampling rate must be an integer multiple of the ' ...
     'EDF trigger sampling rate.'])
scalp_samples_per_trigger_sample = ...
    round(scalp_samples_per_trigger_sample);

n_channels = numel(aligned_eeg_channel_names);
final_eeg_data = zeros( ...
    n_channels, total_sample_count, 'like', eeg_segment_data{1});
matched_edf_sample_mask = false(1, total_sample_count);
previous_end_sample = 0;

for segment_i = 1:n_segments
    start_sample = (matched_segments.edf_start_sample(segment_i) - 1) * ...
        scalp_samples_per_trigger_sample + 1;
    end_sample = (matched_segments.edf_end_sample(segment_i) - 1) * ...
        scalp_samples_per_trigger_sample + 1;

    assert(start_sample == round(start_sample) && ...
        end_sample == round(end_sample), ...
        'concatenate_eeg_segments:NonintegerSegmentBounds', ...
        'Matched EDF segment %d does not map to integer scalp samples.', ...
        segment_i)
    start_sample = round(start_sample);
    end_sample = round(end_sample);

    assert(start_sample > previous_end_sample && ...
        end_sample >= start_sample && end_sample <= total_sample_count, ...
        'concatenate_eeg_segments:InvalidSegmentBounds', ...
        ['Matched EDF segment %d overlaps an earlier segment or falls ' ...
         'outside the full EDF scalp timeline.'], segment_i)
    assert(size(eeg_segment_data{segment_i}, 1) == n_channels && ...
        size(eeg_segment_data{segment_i}, 2) == ...
            end_sample - start_sample + 1, ...
        'concatenate_eeg_segments:UnexpectedSegmentSize', ...
        'EEG segment %d does not match its EDF scalp sample bounds.', ...
        segment_i)

    final_eeg_data(:, start_sample:end_sample) = ...
        eeg_segment_data{segment_i};
    matched_edf_sample_mask(start_sample:end_sample) = true;
    previous_end_sample = end_sample;
end

end
