function clinical_system_faulty = faulty_clinical_detection( ...
    signalHeader_all, signalCell_all, matched_sample_mask)
%FAULTY_CLINICAL_DETECTION Detect faulty clinical mastoid recordings.
%   CLINICAL_SYSTEM_FAULTY is true when the mean of the M1 and M2
%   proportions with absolute voltage at least 1000 uV is greater than 2%.
%   Only samples selected by MATCHED_SAMPLE_MASK contribute to detection.

assert(isstruct(signalHeader_all) && iscell(signalCell_all), ...
    'faulty_clinical_detection:InvalidInputTypes', ...
    'EDF signal headers must be a struct array and signals a cell array.')
assert(numel(signalHeader_all) == numel(signalCell_all), ...
    'faulty_clinical_detection:SignalCountMismatch', ...
    'The EDF signal header and signal cell counts must match.')
assert(islogical(matched_sample_mask) && ...
    isvector(matched_sample_mask) && ~isempty(matched_sample_mask), ...
    'faulty_clinical_detection:InvalidMatchedSampleMask', ...
    'The matched-sample mask must be a nonempty logical vector.')

matched_sample_mask = matched_sample_mask(:);
assert(any(matched_sample_mask), ...
    'faulty_clinical_detection:NoMatchedSamples', ...
    'The matched-sample mask must select at least one sample.')

channel_names = {'M1', 'M2'};
signal_labels = {signalHeader_all.signal_labels};
channel_index = zeros(size(channel_names));

for channel_i = 1:numel(channel_names)
    matching_index = find(strcmp(signal_labels, channel_names{channel_i}));
    if isempty(matching_index)
        error('faulty_clinical_detection:MissingEdfChannel', ...
            'Required EDF signal label not found: %s.', ...
            channel_names{channel_i})
    elseif numel(matching_index) > 1
        error('faulty_clinical_detection:DuplicateEdfChannel', ...
            'EDF signal label occurs more than once: %s.', ...
            channel_names{channel_i})
    end
    channel_index(channel_i) = matching_index;
end

total_sample_count = numel(matched_sample_mask);
matched_sample_count = nnz(matched_sample_mask);
proportion_above_threshold = zeros(size(channel_names));

for channel_i = 1:numel(channel_names)
    edf_index = channel_index(channel_i);
    channel_name = channel_names{channel_i};
    signal_header = signalHeader_all(edf_index);
    signal_data = signalCell_all{edf_index};

    valid_samples_in_record = ...
        isnumeric(signal_header.samples_in_record) && ...
        isreal(signal_header.samples_in_record) && ...
        isscalar(signal_header.samples_in_record) && ...
        isfinite(signal_header.samples_in_record) && ...
        signal_header.samples_in_record == 256;
    assert(valid_samples_in_record, ...
        'faulty_clinical_detection:InvalidSamplingRate', ...
        'EDF signal %s must contain 256 samples per data record.', ...
        channel_name)

    valid_physical_dimension = ...
        ischar(signal_header.physical_dimension) && ...
        strcmp(strtrim(signal_header.physical_dimension), 'uV');
    assert(valid_physical_dimension, ...
        'faulty_clinical_detection:InvalidPhysicalDimension', ...
        'EDF signal %s must use uV as its physical dimension.', ...
        channel_name)

    assert(isnumeric(signal_data) && isreal(signal_data) && ...
        isvector(signal_data), ...
        'faulty_clinical_detection:InvalidSignalData', ...
        'EDF signal %s must be a real numeric vector.', channel_name)
    assert(numel(signal_data) == total_sample_count, ...
        'faulty_clinical_detection:MaskLengthMismatch', ...
        ['EDF signal %s must have the same sample count as the ' ...
         'matched-sample mask.'], channel_name)

    matched_signal_data = double(signal_data(matched_sample_mask));
    assert(all(isfinite(matched_signal_data)), ...
        'faulty_clinical_detection:NonfiniteMatchedSamples', ...
        'Matched EDF samples for %s must all be finite.', channel_name)
    proportion_above_threshold(channel_i) = mean( ...
        abs(matched_signal_data) >= 1000);
end

mean_proportion = mean(proportion_above_threshold);
clinical_system_faulty = mean_proportion > 0.02;
if clinical_system_faulty
    status_text = 'FAULTY';
else
    status_text = 'NORMAL';
end

fprintf('\nClinical mastoid fault detection\n')
fprintf('Matched samples: %d\n', matched_sample_count)
fprintf('Total samples: %d\n', total_sample_count)
fprintf('Matched coverage: %.6f%%\n', ...
    100 * matched_sample_count / total_sample_count)
fprintf('M1 abs(signal) >= 1000 uV: %.6f%%\n', ...
    100 * proportion_above_threshold(1))
fprintf('M2 abs(signal) >= 1000 uV: %.6f%%\n', ...
    100 * proportion_above_threshold(2))
fprintf('Mean M1/M2 proportion: %.6f%%\n', 100 * mean_proportion)
fprintf('Status: %s\n', status_text)

end
