function [result, eeg_input, edf_input, figure_handle] = match_triggers( ...
    eeg_input, edf_input, plot_alignment)
%MATCH_TRIGGERS Match EEG/EDF trigger chunks and resolve supported gaps.
%   [RESULT, EEG_INPUT, EDF_INPUT] = MATCH_TRIGGERS(EEG_INPUT, EDF_INPUT)
%   extracts and validates each system's canonical trigger cycle before
%   matching chunks. EEG_INPUT must contain event_table and Fs; EDF_INPUT
%   must contain event_table and trigger_Fs.
%   The optional fourth output is the alignment figure handle when plotting
%   is enabled, or an empty graphics array otherwise.
%   MATCH_TRIGGERS(..., PLOT_ALIGNMENT) creates a three-panel trigger timeline
%   when PLOT_ALIGNMENT is true. The aligned EEG panel applies one shift that
%   places the initial EEG anchor on the initial EDF anchor.
%   EEG and EDF chunk indices advance independently after a discrepancy so
%   matching can resume after a short loss or one missed cycle boundary.
%   Missing-period bounds are trustworthy trigger anchors; data strictly
%   between the anchors is unsafe, while the anchor samples remain valid.
%   When EEG_INPUT.amplifier_interruptions is present, each marked bracket
%   is audited against the EDF reference. A one-interval bracket within
%   tolerance is retained; otherwise the bracket is excluded and matching
%   resumes only after a confirmed post-reconnect interval.
%   The returned event tables mark the terminal region with is_terminal
%   and its last corresponding trigger with is_terminal_alignment_anchor.
%   EDF triggers before an inferred restart alignment are marked
%   is_pre_alignment.

if nargin < 3
    plot_alignment = false;
end
figure_handle = gobjects(0);

validate_system_inputs(eeg_input, edf_input)
eeg_event_table = eeg_input.event_table;
edf_event_table = edf_input.event_table;
eeg_Fs = eeg_input.Fs;
edf_Fs = edf_input.trigger_Fs;
[startup_mode, edf_cycle_start_event_index] = ...
    classify_edf_startup(edf_input, height(edf_event_table));

% Use one shared tolerance for extracting and comparing both cycles. This
% is equivalent to two samples at the lower of the two sampling rates.
interval_tolerance_sec = 2 / min([eeg_Fs, edf_Fs]);

[eeg_canonical_cycle, eeg_repeat_count, eeg_chunk_report] = ...
    extract_canonical_cycle( ...
        eeg_event_table, eeg_Fs, interval_tolerance_sec);
[edf_canonical_cycle, edf_repeat_count, edf_chunk_report] = ...
    extract_cycle_subset( ...
        edf_event_table, edf_Fs, interval_tolerance_sec, ...
        edf_cycle_start_event_index);
validate_canonical_cycles( ...
    eeg_canonical_cycle, edf_canonical_cycle, interval_tolerance_sec);
eeg_canonical_edges = extract_canonical_edges(eeg_canonical_cycle);
edf_canonical_edges = extract_canonical_edges(edf_canonical_cycle);

eeg_input.canonical_cycle = eeg_canonical_cycle;
eeg_input.canonical_repeat_count = eeg_repeat_count;
eeg_input.chunk_report = eeg_chunk_report;
edf_input.canonical_cycle = edf_canonical_cycle;
edf_input.canonical_repeat_count = edf_repeat_count;
edf_input.chunk_report = edf_chunk_report;

validate_chunk_reports(eeg_chunk_report, edf_chunk_report)
if eeg_chunk_report.status(1) == "partial_start"
    error('match_triggers:UnexpectedEegPartialStart', ...
        ['HD-EEG must begin at an intact four-64 cycle boundary; only the ' ...
         'EDF recording supports partial-cycle late-start alignment.'])
end

result = initialize_result;
result.interval_tolerance_sec = interval_tolerance_sec;
result.startup_mode = startup_mode;
[amplifier_interruptions, has_amplifier_interruptions] = ...
    initialize_amplifier_interruptions(eeg_input);
result.amplifier_interruptions = amplifier_interruptions;
eeg_event_table.is_pre_alignment = false(height(eeg_event_table), 1);
edf_event_table.is_pre_alignment = false(height(edf_event_table), 1);
eeg_event_table.is_initial_alignment_anchor = ...
    false(height(eeg_event_table), 1);
edf_event_table.is_initial_alignment_anchor = ...
    false(height(edf_event_table), 1);
eeg_event_table.is_terminal = false(height(eeg_event_table), 1);
edf_event_table.is_terminal = false(height(edf_event_table), 1);
eeg_event_table.is_terminal_alignment_anchor = ...
    false(height(eeg_event_table), 1);
edf_event_table.is_terminal_alignment_anchor = ...
    false(height(edf_event_table), 1);

if startup_mode == "restart_at_last_validation"
    result.edf_leading_restart_inferred = true;
    result.edf_pre_alignment_event_count = ...
        edf_cycle_start_event_index - 1;
    result.initial_alignment_reason = "restart_at_last_validation";
    edf_event_table.is_pre_alignment( ...
        1:result.edf_pre_alignment_event_count) = true;
    validate_post_validation_restart( ...
        eeg_event_table, eeg_Fs, eeg_chunk_report, ...
        edf_event_table, edf_Fs, edf_chunk_report, ...
        interval_tolerance_sec);
elseif startup_mode == "normal_validation_start"
    result.initial_alignment_reason = "normal_validation_start";
end

if edf_chunk_report.status(1) == "partial_start"
    if any(startup_mode == ...
            ["normal_validation_start", "restart_at_last_validation"])
        error('match_triggers:UnexpectedPostValidationPartialStart', ...
            ['The first retained post-validation EDF trigger is not an ' ...
             'intact four-64 boundary.'])
    elseif startup_mode ~= "no_validation"
        error('match_triggers:PartialStartRequiresValidationMetadata', ...
            ['EDF validation metadata is required before a partial-cycle ' ...
             'late start can be accepted.'])
    end
    [result, eeg_initial_anchor_event_index, ...
        edf_initial_anchor_event_index] = resolve_partial_start( ...
            result, eeg_event_table, eeg_Fs, eeg_chunk_report, ...
            edf_event_table, edf_Fs, ...
            edf_chunk_report, edf_canonical_edges, ...
            interval_tolerance_sec);
    eeg_chunk_i = 2;
    edf_chunk_i = 2;
    eeg_event_table.is_pre_alignment( ...
        1:eeg_initial_anchor_event_index - 1) = true;
    result.eeg_pre_alignment_event_count = ...
        eeg_initial_anchor_event_index - 1;
elseif startup_mode == "no_validation"
    error('match_triggers:UnsupportedNoValidationStart', ...
        ['EDF contains no validation sequence and does not begin with a ' ...
         'regular-63 partial cycle. Initial alignment is unsupported.'])
else
    eeg_chunk_i = 1;
    [result, edf_chunk_i, edf_event_table] = resolve_initial_alignment( ...
        result, eeg_event_table, eeg_Fs, eeg_chunk_report, ...
        edf_event_table, edf_Fs, edf_canonical_edges, edf_chunk_report, ...
        interval_tolerance_sec);
    eeg_initial_anchor_event_index = eeg_chunk_report.start_event_index(1);
    edf_initial_anchor_event_index = ...
        edf_chunk_report.start_event_index(edf_chunk_i);
end
if has_amplifier_interruptions
    [result, amplifier_interruptions, ...
        eeg_initial_anchor_event_index, edf_initial_anchor_event_index, ...
        eeg_event_table] = resolve_leading_amplifier_interruption( ...
            result, amplifier_interruptions, ...
            eeg_initial_anchor_event_index, edf_initial_anchor_event_index, ...
            eeg_event_table, eeg_Fs, eeg_chunk_report, ...
            edf_event_table, edf_Fs, edf_chunk_report, ...
            result.initial_edf_chunk_index, ...
            interval_tolerance_sec);
    if result.startup_mode == "partial_cycle_late_start"
        amplifier_interruptions = ...
            resolve_skipped_partial_start_interruptions( ...
                amplifier_interruptions, eeg_initial_anchor_event_index, ...
                eeg_chunk_report, height(eeg_event_table));
        result.eeg_pre_alignment_event_count = ...
            eeg_initial_anchor_event_index - 1;
    end
    result.amplifier_interruptions = amplifier_interruptions;
end
eeg_event_table.is_initial_alignment_anchor( ...
    eeg_initial_anchor_event_index) = true;
edf_event_table.is_initial_alignment_anchor( ...
    edf_initial_anchor_event_index) = true;
result.eeg_initial_anchor_event_index = eeg_initial_anchor_event_index;
result.edf_initial_anchor_event_index = edf_initial_anchor_event_index;
result.eeg_initial_anchor_latency = ...
    double(eeg_event_table.latency(eeg_initial_anchor_event_index));
result.edf_initial_anchor_latency = ...
    double(edf_event_table.latency(edf_initial_anchor_event_index));
edf_input.startup_mode = result.startup_mode;
fprintf('EDF startup mode: %s\n', result.startup_mode);

while eeg_chunk_i <= height(eeg_chunk_report) && ...
        edf_chunk_i <= height(edf_chunk_report)
    if has_amplifier_interruptions
        [terminal_group_ids, amplifier_interruptions] = ...
            terminal_amplifier_groups( ...
                amplifier_interruptions, eeg_chunk_report, eeg_chunk_i, ...
                height(eeg_event_table));
        if ~isempty(terminal_group_ids)
            [result, eeg_event_table, edf_event_table, ...
                amplifier_interruptions] = ...
                align_terminal_amplifier_loss( ...
                    result, terminal_group_ids, amplifier_interruptions, ...
                    eeg_chunk_i, edf_chunk_i, ...
                    eeg_event_table, eeg_Fs, eeg_chunk_report, ...
                    edf_event_table, edf_Fs, edf_chunk_report, ...
                    interval_tolerance_sec);
            result.amplifier_interruptions = amplifier_interruptions;
            break
        end
    end

    is_terminal_region = ...
        ~eeg_chunk_report.has_next_boundary(eeg_chunk_i) || ...
        ~edf_chunk_report.has_next_boundary(edf_chunk_i);
    if has_amplifier_interruptions && is_terminal_region
        eeg_terminal_edges = extract_chunk_edges( ...
            eeg_event_table, eeg_Fs, eeg_chunk_report, eeg_chunk_i);
        edf_terminal_edges = extract_chunk_edges( ...
            edf_event_table, edf_Fs, edf_chunk_report, edf_chunk_i);
        eeg_terminal_status = eeg_chunk_report.status(eeg_chunk_i);
        edf_terminal_status = edf_chunk_report.status(edf_chunk_i);
        [result, amplifier_interruptions, marker_action] = ...
            resolve_amplifier_interruptions_in_chunk( ...
                result, amplifier_interruptions, ...
                eeg_chunk_i, edf_chunk_i, ...
                eeg_event_table, eeg_Fs, eeg_chunk_report, ...
                eeg_terminal_edges, ...
                edf_event_table, edf_chunk_report, edf_terminal_edges, ...
                eeg_terminal_status, edf_terminal_status, ...
                interval_tolerance_sec);
        result.amplifier_interruptions = amplifier_interruptions;
        if marker_action == "advance"
            [result, eeg_event_table, edf_event_table] = ...
                finalize_terminal_amplifier_relock( ...
                    result, eeg_chunk_i, edf_chunk_i, ...
                    eeg_event_table, eeg_chunk_report, ...
                    edf_event_table, edf_chunk_report);
            break
        elseif marker_action == "stop"
            break
        end
    end

    if ~eeg_chunk_report.has_next_boundary(eeg_chunk_i) || ...
            ~edf_chunk_report.has_next_boundary(edf_chunk_i)
        terminal_alignment_locked = false;
        if ~isempty(result.comparison_history)
            last_comparison = result.comparison_history(end, :);
            terminal_alignment_locked = any( ...
                last_comparison.outcome == ["match", "shared_trigger_glitch"]);

            % A matching suffix can re-lock a one-sided loss before the
            % immediately following terminal region.
            all_missing_periods_closed = ...
                ~isempty(result.missing_periods) && ...
                all(isfinite( ...
                    result.missing_periods.end_anchor_event_index));
            resolved_same_offset_loss = any( ...
                last_comparison.outcome == ...
                    ["eeg_data_loss", "edf_data_loss"]) && ...
                last_comparison.resolution_status == ...
                    "resumed_same_offset" && ...
                last_comparison.next_eeg_chunk_index == eeg_chunk_i && ...
                last_comparison.next_edf_chunk_index == edf_chunk_i && ...
                ~result.requires_relock && all_missing_periods_closed;
            terminal_alignment_locked = ...
                terminal_alignment_locked || resolved_same_offset_loss;
        end

        if ~terminal_alignment_locked
            error('match_triggers:TerminalAlignmentNotLocked', ...
                ['A matching chunk was not established immediately before ' ...
                 'the terminal region. Terminal anchors cannot be assigned.'])
        end
        [result, eeg_event_table, edf_event_table] = ...
            align_terminal_region( ...
                result, eeg_chunk_i, edf_chunk_i, ...
                eeg_event_table, eeg_Fs, eeg_chunk_report, ...
                edf_event_table, edf_Fs, edf_chunk_report, ...
                interval_tolerance_sec);
        break
    end

    eeg_edges = extract_chunk_edges( ...
        eeg_event_table, eeg_Fs, eeg_chunk_report, eeg_chunk_i);
    edf_edges = extract_chunk_edges( ...
        edf_event_table, edf_Fs, edf_chunk_report, edf_chunk_i);
    pair_matches = edges_match( ...
        eeg_edges, edf_edges, interval_tolerance_sec);

    eeg_status = eeg_chunk_report.status(eeg_chunk_i);
    edf_status = edf_chunk_report.status(edf_chunk_i);
    eeg_matches_canonical = eeg_status == "match";
    edf_matches_canonical = edf_status == "match";

    if has_amplifier_interruptions
        [result, amplifier_interruptions, marker_action] = ...
            resolve_amplifier_interruptions_in_chunk( ...
                result, amplifier_interruptions, ...
                eeg_chunk_i, edf_chunk_i, ...
                eeg_event_table, eeg_Fs, eeg_chunk_report, eeg_edges, ...
                edf_event_table, edf_chunk_report, edf_edges, ...
                eeg_status, edf_status, interval_tolerance_sec);
        result.amplifier_interruptions = amplifier_interruptions;
        if marker_action == "advance"
            eeg_chunk_i = eeg_chunk_i + 1;
            edf_chunk_i = edf_chunk_i + 1;
            continue
        elseif marker_action == "stop"
            break
        end
    end

    if eeg_matches_canonical && edf_matches_canonical
        if ~pair_matches
            error('match_triggers:MatchedChunkDisagreement', ...
                ['EEG chunk %d and EDF chunk %d both match their canonical ' ...
                 'cycles but do not match each other.'], ...
                eeg_chunk_i, edf_chunk_i)
        end

        result = close_open_missing_periods( ...
            result, eeg_chunk_i, edf_chunk_i, ...
            eeg_event_table, eeg_Fs, eeg_chunk_report, ...
            edf_event_table, edf_Fs, edf_chunk_report);
        next_eeg_chunk_i = eeg_chunk_i + 1;
        next_edf_chunk_i = edf_chunk_i + 1;
        result.comparison_history = [result.comparison_history; ...
            make_history_row( ...
                eeg_chunk_i, edf_chunk_i, eeg_status, edf_status, ...
                "match", "canonical_match", ...
                next_eeg_chunk_i, next_edf_chunk_i)];
        result.matched_chunk_count = result.matched_chunk_count + 1;
        if isnan(result.first_problem_chunk)
            result.initial_matched_chunk_count = ...
                result.initial_matched_chunk_count + 1;
        end
        eeg_chunk_i = next_eeg_chunk_i;
        edf_chunk_i = next_edf_chunk_i;
        continue
    end

    if xor(eeg_matches_canonical, edf_matches_canonical)
        if pair_matches
            error('match_triggers:StatusContradiction', ...
                ['Exactly one report marks EEG chunk %d / EDF chunk %d as ' ...
                 'canonical, but their complete interval sequences agree.'], ...
                eeg_chunk_i, edf_chunk_i)
        end

        if eeg_matches_canonical
            affected_system = "edf";
            affected_event_table = edf_event_table;
            affected_Fs = edf_Fs;
            affected_edges = edf_edges;
            affected_canonical_edges = edf_canonical_edges;
            affected_chunk_report = edf_chunk_report;
            affected_chunk_i = edf_chunk_i;
        else
            affected_system = "eeg";
            affected_event_table = eeg_event_table;
            affected_Fs = eeg_Fs;
            affected_edges = eeg_edges;
            affected_canonical_edges = eeg_canonical_edges;
            affected_chunk_report = eeg_chunk_report;
            affected_chunk_i = eeg_chunk_i;
        end

        [start_anchor_event_index, end_anchor_event_index, ...
            loss_prefix_count, loss_suffix_count] = ...
            locate_loss_anchors( ...
                affected_edges, affected_canonical_edges, ...
                interval_tolerance_sec);

        observed_trigger_count = ...
            affected_chunk_report.observed_trigger_count(affected_chunk_i);
        estimated_cycle_count = ...
            affected_chunk_report.estimated_cycle_count(affected_chunk_i);
        missing_boundary_diagnostic = ...
            affected_chunk_report.reason(affected_chunk_i) == ...
                "suspected_missing_boundary";
        canonical_trigger_count = height(affected_canonical_edges);

        if observed_trigger_count < canonical_trigger_count
            next_eeg_chunk_i = eeg_chunk_i + 1;
            next_edf_chunk_i = edf_chunk_i + 1;
            resolution_status = "resumed_same_offset";
            period_reason = "within_cycle_loss";
        elseif observed_trigger_count > canonical_trigger_count && ...
                missing_boundary_diagnostic && estimated_cycle_count == 2
            if affected_system == "eeg"
                next_eeg_chunk_i = eeg_chunk_i + 1;
                next_edf_chunk_i = edf_chunk_i + 2;
            else
                next_eeg_chunk_i = eeg_chunk_i + 2;
                next_edf_chunk_i = edf_chunk_i + 1;
            end
            resolution_status = "resumed_after_boundary_skip";
            period_reason = "suspected_missing_boundary";
        else
            next_eeg_chunk_i = NaN;
            next_edf_chunk_i = NaN;
            resolution_status = "unsupported_cycle_count_ambiguity";
            period_reason = "manual_cycle_count_review";
        end

        issue_outcome = affected_system + "_data_loss";
        result.suspected_missing_boundary = ...
            result.suspected_missing_boundary || missing_boundary_diagnostic;
        marker_period = empty_missing_period_table;
        marker_resolved = false;
        if has_amplifier_interruptions && affected_system == "eeg"
            [amplifier_interruptions, marker_period, ...
                marker_resolved] = resolve_generic_amplifier_loss( ...
                    amplifier_interruptions, ...
                    start_anchor_event_index, end_anchor_event_index, ...
                    loss_prefix_count, loss_suffix_count, ...
                    eeg_chunk_i, edf_chunk_i, ...
                    next_edf_chunk_i, resolution_status, ...
                    eeg_event_table, eeg_Fs, eeg_chunk_report, ...
                    edf_event_table, edf_Fs, edf_chunk_report, ...
                    edf_edges);
            result.amplifier_interruptions = amplifier_interruptions;
        end
        if marker_resolved
            result.missing_periods = [ ...
                result.missing_periods; marker_period];
        else
            result.missing_periods = [result.missing_periods; ...
                make_missing_period( ...
                affected_system, start_anchor_event_index, ...
                end_anchor_event_index, affected_event_table, affected_Fs, ...
                period_reason, eeg_chunk_i, edf_chunk_i)];
        end
        result = record_problem( ...
            result, eeg_chunk_i, edf_chunk_i, eeg_status, edf_status, ...
            issue_outcome, resolution_status, ...
            next_eeg_chunk_i, next_edf_chunk_i);

        if isnan(next_eeg_chunk_i)
            result.requires_relock = true;
            result.stopped_reason = "unsupported_cycle_count_ambiguity";
            break
        end

        result.requires_relock = any( ...
            isnan(result.missing_periods.end_anchor_event_index));
        eeg_chunk_i = next_eeg_chunk_i;
        edf_chunk_i = next_edf_chunk_i;
        continue
    end

    if pair_matches
        next_eeg_chunk_i = eeg_chunk_i + 1;
        next_edf_chunk_i = edf_chunk_i + 1;
        result = record_problem( ...
            result, eeg_chunk_i, edf_chunk_i, eeg_status, edf_status, ...
            "shared_trigger_glitch", "resumed_same_offset", ...
            next_eeg_chunk_i, next_edf_chunk_i);
        eeg_chunk_i = next_eeg_chunk_i;
        edf_chunk_i = next_edf_chunk_i;
        continue
    end

    eeg_prefix_count = matching_prefix_count( ...
        eeg_edges, eeg_canonical_edges, interval_tolerance_sec);
    edf_prefix_count = matching_prefix_count( ...
        edf_edges, edf_canonical_edges, interval_tolerance_sec);
    shared_prefix_count = min(eeg_prefix_count, edf_prefix_count);

    eeg_start_anchor = anchor_after_prefix(eeg_edges, shared_prefix_count);
    edf_start_anchor = anchor_after_prefix(edf_edges, shared_prefix_count);

    result.requires_relock = true;
    result.stopped_reason = "divergent_noncanonical_chunks";
    result.missing_periods = [result.missing_periods; ...
        make_missing_period( ...
            "eeg", eeg_start_anchor, NaN, eeg_event_table, eeg_Fs, ...
            "divergent_noncanonical_chunks", eeg_chunk_i, edf_chunk_i); ...
        make_missing_period( ...
            "edf", edf_start_anchor, NaN, edf_event_table, edf_Fs, ...
            "divergent_noncanonical_chunks", eeg_chunk_i, edf_chunk_i)];
    result = record_problem( ...
        result, eeg_chunk_i, edf_chunk_i, eeg_status, edf_status, ...
        "both_systems_unusable", "requires_next_shared_chunk", NaN, NaN);
    break
end

if ~result.terminal_chunk_handled && result.stopped_reason == "" && ...
        (eeg_chunk_i > height(eeg_chunk_report) || ...
         edf_chunk_i > height(edf_chunk_report))
    error('match_triggers:TerminalRegionSkipped', ...
        ['A chunk-index jump passed the terminal region before its start ' ...
         'could be aligned. Manual terminal review is required.'])
end

if result.terminal_chunk_handled && isnan(result.first_problem_chunk)
    result.outcome = "all_nonterminal_chunks_match";
    result.resolution_status = "terminal_anchor_identified";
end

eeg_input.event_table = eeg_event_table;
edf_input.event_table = edf_event_table;
result.amplifier_interruptions = amplifier_interruptions;
if has_amplifier_interruptions
    disp('HD-EEG amplifier interruption handling:')
    disp(amplifier_interruptions(:, { ...
        'interruption_id', 'gap_group_index', ...
        'resolution_status', 'exclude_from_segments', ...
        'eeg_start_anchor_event_index', 'eeg_end_anchor_event_index', ...
        'edf_start_anchor_event_index', 'edf_end_anchor_event_index'}))
end
if plot_alignment
    figure_handle = plot_trigger_alignment(result, eeg_input, edf_input);
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% END OF MATCH_TRIGGERS (MAIN FUNCTION)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
end

%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% ADDITIONAL HELPER FUNCTIONS
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function validate_canonical_cycles( ...
    eeg_canonical_cycle, edf_canonical_cycle, interval_tolerance_sec)
%VALIDATE_CANONICAL_CYCLES Confirm that EEG and EDF cycles are equivalent.
%   VALIDATE_CANONICAL_CYCLES(EEG_CANONICAL_CYCLE, EDF_CANONICAL_CYCLE,
%   INTERVAL_TOLERANCE_SEC) requires both cycles to contain exactly 50
%   triggers with identical types and interval timing in the same order.

assert(istable(eeg_canonical_cycle) && istable(edf_canonical_cycle), ...
    'Canonical cycles must be tables.')
required_variables = ["type", "interval_to_next_sec"];
assert(all(ismember(required_variables, ...
    string(eeg_canonical_cycle.Properties.VariableNames))) && ...
    all(ismember(required_variables, ...
    string(edf_canonical_cycle.Properties.VariableNames))), ...
    'Canonical cycles must contain type and interval_to_next_sec variables.')
assert(isnumeric(interval_tolerance_sec) && ...
    isscalar(interval_tolerance_sec) && ...
    isfinite(interval_tolerance_sec) && interval_tolerance_sec >= 0, ...
    'interval_tolerance_sec must be a nonnegative finite scalar.')

expected_trigger_count = 50;
eeg_trigger_count = height(eeg_canonical_cycle);
edf_trigger_count = height(edf_canonical_cycle);
if eeg_trigger_count ~= expected_trigger_count || ...
        edf_trigger_count ~= expected_trigger_count
    error('validate_canonical_cycles:UnexpectedTriggerCount', ...
        ['Canonical cycles must each contain exactly %d triggers. ' ...
         'EEG contains %d and EDF contains %d.'], ...
        expected_trigger_count, eeg_trigger_count, edf_trigger_count)
end

eeg_type = strip(string(eeg_canonical_cycle.type(:)));
edf_type = strip(string(edf_canonical_cycle.type(:)));
assert(~any(ismissing(eeg_type)) && ~any(ismissing(edf_type)), ...
    'Canonical cycle trigger types must not contain missing values.')

type_mismatch_index = find(eeg_type ~= edf_type, 1, 'first');
if ~isempty(type_mismatch_index)
    error('validate_canonical_cycles:TriggerTypeMismatch', ...
        ['Canonical trigger types differ at row %d: ' ...
         'EEG is %s and EDF is %s.'], ...
        type_mismatch_index, eeg_type(type_mismatch_index), ...
        edf_type(type_mismatch_index))
end

assert(isnumeric(eeg_canonical_cycle.interval_to_next_sec) && ...
    isnumeric(edf_canonical_cycle.interval_to_next_sec), ...
    'Canonical cycle intervals must be numeric.')
eeg_interval_sec = double(eeg_canonical_cycle.interval_to_next_sec(:));
edf_interval_sec = double(edf_canonical_cycle.interval_to_next_sec(:));
assert(all(isfinite(eeg_interval_sec)) && all(isfinite(edf_interval_sec)), ...
    'Canonical cycle intervals must be finite.')

interval_error_sec = abs(eeg_interval_sec - edf_interval_sec);
comparison_scale = max([abs(eeg_interval_sec); abs(edf_interval_sec); 1]);
roundoff_tolerance_sec = 10 * eps(comparison_scale);
interval_mismatch_index = find( ...
    interval_error_sec > interval_tolerance_sec + roundoff_tolerance_sec, ...
    1, 'first');

if ~isempty(interval_mismatch_index)
    error('validate_canonical_cycles:IntervalMismatch', ...
        ['Canonical intervals differ at row %d by %.9g sec, exceeding ' ...
         'the %.9g sec tolerance.'], ...
        interval_mismatch_index, interval_error_sec(interval_mismatch_index), ...
        interval_tolerance_sec)
end

disp('EEG and EDF canonical cycles match.')

end

%%
function figure_handle = plot_trigger_alignment(result, eeg_input, edf_input)
%PLOT_TRIGGER_ALIGNMENT Plot original, shifted, and EDF trigger timelines.
%   FIGURE_HANDLE = PLOT_TRIGGER_ALIGNMENT(RESULT, EEG_INPUT, EDF_INPUT)
%   colors corresponding matched chunks identically across systems. Unmatched
%   chunks remain black. Striped intervals mark unsafe data between inferred
%   loss anchors and terminal padding or truncation implied by recording
%   lengths. Time is shown in hours on the EDF recording clock.

eeg_event_table = eeg_input.event_table;
edf_event_table = edf_input.event_table;
eeg_Fs = eeg_input.Fs;
edf_Fs = edf_input.trigger_Fs;

eeg_duration_hr = recording_duration_hr(eeg_input, "eeg");
edf_duration_hr = recording_duration_hr(edf_input, "edf");
eeg_time_hr = (double(eeg_event_table.latency) - 1) ./ eeg_Fs ./ 3600;
edf_time_hr = (double(edf_event_table.latency) - 1) ./ edf_Fs ./ 3600;
assert(eeg_duration_hr >= max(eeg_time_hr), ...
    'EEG recording duration ends before its last retained trigger.')
assert(edf_duration_hr >= max(edf_time_hr), ...
    'EDF recording duration ends before its last retained trigger.')

eeg_shift_hr = ( ...
    (result.edf_initial_anchor_latency - 1) ./ edf_Fs - ...
    (result.eeg_initial_anchor_latency - 1) ./ eeg_Fs) ./ 3600;
aligned_eeg_time_hr = eeg_time_hr + eeg_shift_hr;
aligned_eeg_start_hr = eeg_shift_hr;
aligned_eeg_end_hr = eeg_shift_hr + eeg_duration_hr;

[eeg_color, edf_color, terminal_color] = ...
    trigger_chunk_colors(result, eeg_input, edf_input);
aligned_eeg_color = eeg_color;
if result.terminal_chunk_handled && result.terminal_relation == "eeg_longer"
    first_truncated_trigger = result.eeg_terminal_anchor_event_index + 1;
    aligned_eeg_color(first_truncated_trigger:end, :) = 1;
end

figure_handle = figure('Color', 'w');
ax_original = subplot(3, 1, 1, 'Parent', figure_handle);
ax_aligned = subplot(3, 1, 2, 'Parent', figure_handle);
ax_edf = subplot(3, 1, 3, 'Parent', figure_handle);

initialize_timeline_axis( ...
    ax_original, 0, eeg_duration_hr, 'Original HD-EEG', ...
    'original_eeg_timeline');
initialize_timeline_axis( ...
    ax_aligned, aligned_eeg_start_hr, aligned_eeg_end_hr, ...
    'Aligned HD-EEG', 'aligned_eeg_timeline');
initialize_timeline_axis( ...
    ax_edf, 0, edf_duration_hr, 'Clinical EDF', 'edf_timeline');

plot_initial_padding(ax_aligned, aligned_eeg_start_hr);
plot_missing_periods( ...
    result.missing_periods, ax_original, ax_aligned, ax_edf, ...
    eeg_shift_hr, eeg_duration_hr, edf_duration_hr, eeg_Fs, edf_Fs);
plot_terminal_adjustment( ...
    result, ax_aligned, aligned_eeg_end_hr, edf_duration_hr, terminal_color);

plot_trigger_chunks( ...
    ax_original, eeg_time_hr, eeg_event_table, ...
    eeg_color, eeg_input.chunk_report);
plot_trigger_chunks( ...
    ax_aligned, aligned_eeg_time_hr, eeg_event_table, ...
    aligned_eeg_color, eeg_input.chunk_report);
plot_trigger_chunks( ...
    ax_edf, edf_time_hr, edf_event_table, ...
    edf_color, edf_input.chunk_report);

x_min = min([0, aligned_eeg_start_hr]);
x_max = max([eeg_duration_hr, aligned_eeg_end_hr, edf_duration_hr]);
x_margin = max((x_max - x_min) .* 0.01, eps(x_max));
xlim(ax_original, [x_min - x_margin, x_max + x_margin])
xlabel(ax_edf, 'Time on EDF clock (hours)')
linkaxes([ax_original, ax_aligned, ax_edf], 'x')
sgtitle(figure_handle, ...
    'Trigger alignment timeline (matching colors denote paired chunks)', ...
    'FontSize', 18)

end

%%
function plot_initial_padding(ax_aligned, aligned_eeg_start_hr)

start_tolerance_hr = 10 * eps(max(abs(aligned_eeg_start_hr), 1));
if aligned_eeg_start_hr <= start_tolerance_hr
    return
end

draw_interval_bars( ...
    ax_aligned, 0, aligned_eeg_start_hr, ...
    [0.6, 0.6, 0.6], 'initial_zero_padding');

end

%%
function duration_hr = recording_duration_hr(input, system)

if isfield(input, 'dur_hr')
    duration_hr = input.dur_hr;
elseif system == "eeg" && isfield(input, 'EEG') && ...
        isfield(input.EEG, 'pnts')
    duration_hr = double(input.EEG.pnts) ./ input.Fs ./ 3600;
elseif system == "edf" && isfield(input, 'DC_trace')
    duration_hr = numel(input.DC_trace) ./ input.trigger_Fs ./ 3600;
else
    error('plot_trigger_alignment:MissingRecordingDuration', ...
        ['%s recording duration is unavailable. Run extract_triggers first ' ...
         'or provide dur_hr.'], upper(system))
end

assert(isnumeric(duration_hr) && isscalar(duration_hr) && ...
    isfinite(duration_hr) && duration_hr > 0, ...
    'Recording durations must be positive finite scalars.')

end

%%
function [eeg_color, edf_color, terminal_color] = ...
    trigger_chunk_colors(result, eeg_input, edf_input)

eeg_color = zeros(height(eeg_input.event_table), 3);
edf_color = zeros(height(edf_input.event_table), 3);
terminal_color = [0, 0, 0];
history = result.comparison_history;
trusted_outcomes = [ ...
    "match", "partial_start_match", "shared_trigger_glitch", ...
    "eeg_shorter", "eeg_longer", "same_last_trigger"];
trusted_history_index = find(ismember(history.outcome, trusted_outcomes));
color_map = lines(numel(trusted_history_index));

for color_i = 1:numel(trusted_history_index)
    history_i = trusted_history_index(color_i);
    color = color_map(color_i, :);
    outcome = history.outcome(history_i);
    eeg_chunk_i = history.eeg_chunk_index(history_i);
    edf_chunk_i = history.edf_chunk_index(history_i);
    eeg_start = eeg_input.chunk_report.start_event_index(eeg_chunk_i);
    edf_start = edf_input.chunk_report.start_event_index(edf_chunk_i);

    is_partial_start = outcome == "partial_start_match";
    is_terminal = ismember( ...
        outcome, ["eeg_shorter", "eeg_longer", "same_last_trigger"]);
    if is_partial_start
        eeg_start = result.eeg_initial_anchor_event_index;
        edf_start = result.edf_initial_anchor_event_index;
        eeg_end = eeg_input.chunk_report.end_event_index(eeg_chunk_i);
        edf_end = edf_input.chunk_report.end_event_index(edf_chunk_i);
    elseif is_terminal
        eeg_end = result.eeg_terminal_anchor_event_index;
        edf_end = result.edf_terminal_anchor_event_index;
        terminal_color = color;
        if outcome == "eeg_shorter"
            edf_end = height(edf_input.event_table);
        end
    else
        eeg_end = eeg_input.chunk_report.end_event_index(eeg_chunk_i);
        edf_end = edf_input.chunk_report.end_event_index(edf_chunk_i);
    end

    eeg_color(eeg_start:eeg_end, :) = repmat( ...
        color, eeg_end - eeg_start + 1, 1);
    edf_color(edf_start:edf_end, :) = repmat( ...
        color, edf_end - edf_start + 1, 1);
end

end

%%
function initialize_timeline_axis(ax, start_hr, end_hr, title_text, tag)

hold(ax, 'on')
trigger_y_limits = [62.5, 64.5];
patch(ax, ...
    [start_hr, end_hr, end_hr, start_hr], ...
    [trigger_y_limits(1), trigger_y_limits(1), ...
     trigger_y_limits(2), trigger_y_limits(2)], ...
    [0.94, 0.94, 0.94], ...
    'EdgeColor', 'none', ...
    'Tag', 'recording_extent', ...
    'HandleVisibility', 'off')
set(ax, ...
    'Box', 'on', ...
    'FontSize', 14, ...
    'Layer', 'top', ...
    'Tag', tag, ...
    'YLim', trigger_y_limits, ...
    'YTick', [63, 64])
ax.InteractionOptions.DatatipsSupported = 'off';
title(ax, title_text, 'FontSize', 18)
ylabel(ax, 'Trigger type')

end

%%
function plot_trigger_chunks(ax, time_hr, event_table, color, chunk_report)

trigger_type = str2double(string(event_table.type));
assert(all(isfinite(trigger_type)), ...
    'Trigger types must be numeric strings for timeline plotting.')

for chunk_i = 1:height(chunk_report)
    event_rows = ( ...
        chunk_report.start_event_index(chunk_i): ...
        chunk_report.end_event_index(chunk_i))';
    chunk_color = color(event_rows, :);
    color_change = [true; any(diff(chunk_color, 1, 1) ~= 0, 2)];
    segment_start = find(color_change);
    segment_end = [segment_start(2:end) - 1; numel(event_rows)];

    for segment_i = 1:numel(segment_start)
        segment_rows = event_rows( ...
            segment_start(segment_i):segment_end(segment_i));
        segment_color = color(segment_rows(1), :);
        plot(ax, time_hr(segment_rows), trigger_type(segment_rows), '-o', ...
            'Color', segment_color, ...
            'LineWidth', 1, ...
            'MarkerSize', 4, ...
            'Tag', 'trigger_chunk', ...
            'UserData', chunk_i, ...
            'HandleVisibility', 'off')
    end
end

end

%%
function plot_missing_periods( ...
    missing_periods, ax_original, ax_aligned, ax_edf, ...
    eeg_shift_hr, eeg_duration_hr, edf_duration_hr, eeg_Fs, edf_Fs)

missing_color = [0.15, 0.15, 0.15];
for period_i = 1:height(missing_periods)
    if missing_periods.system(period_i) == "eeg"
        start_hr = ( ...
            missing_periods.start_anchor_latency(period_i) - 1) ./ ...
            eeg_Fs ./ 3600;
        end_hr = anchor_time_hr( ...
            missing_periods.end_anchor_latency(period_i), ...
            eeg_Fs, eeg_duration_hr);
        draw_interval_bars( ...
            ax_original, start_hr, end_hr, missing_color, 'unsafe_interval');
        draw_interval_bars( ...
            ax_aligned, start_hr + eeg_shift_hr, end_hr + eeg_shift_hr, ...
            missing_color, 'unsafe_interval');
    else
        start_hr = ( ...
            missing_periods.start_anchor_latency(period_i) - 1) ./ ...
            edf_Fs ./ 3600;
        end_hr = anchor_time_hr( ...
            missing_periods.end_anchor_latency(period_i), ...
            edf_Fs, edf_duration_hr);
        draw_interval_bars( ...
            ax_edf, start_hr, end_hr, missing_color, 'unsafe_interval');
    end
end

end

%%
function time_hr = anchor_time_hr(latency, Fs, recording_duration_hr)

if isnan(latency)
    time_hr = recording_duration_hr;
else
    time_hr = (latency - 1) ./ Fs ./ 3600;
end

end

%%
function plot_terminal_adjustment( ...
    result, ax_aligned, aligned_eeg_end_hr, edf_duration_hr, terminal_color)

if ~result.terminal_chunk_handled
    return
end

comparison_scale = max([abs(aligned_eeg_end_hr), abs(edf_duration_hr), 1]);
duration_tolerance_hr = 10 * eps(comparison_scale);
if aligned_eeg_end_hr < edf_duration_hr - duration_tolerance_hr
    draw_interval_bars( ...
        ax_aligned, aligned_eeg_end_hr, edf_duration_hr, ...
        terminal_color, 'terminal_zero_padding');
elseif aligned_eeg_end_hr > edf_duration_hr + duration_tolerance_hr
    draw_interval_bars( ...
        ax_aligned, edf_duration_hr, aligned_eeg_end_hr, ...
        [1, 1, 1], 'terminal_drop');
end

end

%%
function line_handle = draw_interval_bars( ...
    ax, start_hr, end_hr, color, tag)

line_handle = gobjects(0);
if ~isfinite(start_hr) || ~isfinite(end_hr) || end_hr <= start_hr
    return
end

bar_time = linspace(start_hr, end_hr, 14);
x = reshape([bar_time; bar_time; nan(size(bar_time))], [], 1);
y_limits = ylim(ax);
y_margin = 0.05 .* diff(y_limits);
y = reshape([ ...
    repmat(y_limits(1) + y_margin, size(bar_time)); ...
    repmat(y_limits(2) - y_margin, size(bar_time)); ...
    nan(size(bar_time))], [], 1);
line_handle = plot(ax, x, y, ...
    'Color', color, ...
    'LineWidth', 1, ...
    'Tag', tag, ...
    'HandleVisibility', 'off');

end

%%
function result = initialize_result

result = struct( ...
    'interval_tolerance_sec', NaN, ...
    'startup_mode', "legacy_startup", ...
    'matched_chunk_count', 0, ...
    'initial_matched_chunk_count', 0, ...
    'first_problem_chunk', NaN, ...
    'first_problem_eeg_chunk', NaN, ...
    'first_problem_edf_chunk', NaN, ...
    'eeg_status', "", ...
    'edf_status', "", ...
    'outcome', "", ...
    'resolution_status', "", ...
    'requires_relock', false, ...
    'suspected_missing_boundary', false, ...
    'initial_eeg_chunk_index', 1, ...
    'initial_edf_chunk_index', 1, ...
    'edf_leading_restart_inferred', false, ...
    'edf_pre_alignment_event_count', 0, ...
    'eeg_pre_alignment_event_count', 0, ...
    'initial_alignment_reason', "first_chunks_retained", ...
    'initial_cycle_offset_uncertain', false, ...
    'initial_canonical_interval_number', NaN, ...
    'initial_matching_interval_count', 0, ...
    'initial_matching_candidate_count', 0, ...
    'initial_matching_prefix_interval_count', 0, ...
    'initial_matching_suffix_interval_count', 0, ...
    'eeg_initial_anchor_event_index', NaN, ...
    'edf_initial_anchor_event_index', NaN, ...
    'eeg_initial_anchor_latency', NaN, ...
    'edf_initial_anchor_latency', NaN, ...
    'terminal_chunk_handled', false, ...
    'terminal_chunk_deferred', false, ...
    'terminal_relation', "", ...
    'terminal_later_action', "", ...
    'eeg_zero_padding_required', NaN, ...
    'eeg_terminal_chunk_indices', zeros(1, 0), ...
    'edf_terminal_chunk_indices', zeros(1, 0), ...
    'eeg_terminal_anchor_event_index', NaN, ...
    'edf_terminal_anchor_event_index', NaN, ...
    'eeg_terminal_anchor_latency', NaN, ...
    'edf_terminal_anchor_latency', NaN, ...
    'terminal_common_trigger_count', 0, ...
    'stopped_reason', "", ...
    'comparison_history', empty_history_table, ...
    'missing_periods', empty_missing_period_table);

end

%%
function [startup_mode, cycle_start_event_index] = ...
    classify_edf_startup(edf_input, event_count)

startup_mode = "legacy_startup";
cycle_start_event_index = 1;
if ~isfield(edf_input, 'validation_sequence_count')
    return
end

required_fields = { ...
    'validation_sequences', ...
    'pre_authoritative_validation_event_count'};
assert(all(isfield(edf_input, required_fields)), ...
    'match_triggers:InvalidStartupMetadata', ...
    'EDF validation metadata is incomplete.')

validation_sequence_count = edf_input.validation_sequence_count;
pre_alignment_event_count = ...
    edf_input.pre_authoritative_validation_event_count;
assert(isnumeric(validation_sequence_count) && ...
    isscalar(validation_sequence_count) && ...
    isfinite(validation_sequence_count) && ...
    validation_sequence_count >= 0 && ...
    validation_sequence_count == fix(validation_sequence_count) && ...
    istable(edf_input.validation_sequences) && ...
    height(edf_input.validation_sequences) == validation_sequence_count, ...
    'match_triggers:InvalidStartupMetadata', ...
    'EDF validation-sequence metadata is inconsistent.')
assert(isnumeric(pre_alignment_event_count) && ...
    isscalar(pre_alignment_event_count) && ...
    isfinite(pre_alignment_event_count) && ...
    pre_alignment_event_count >= 0 && ...
    pre_alignment_event_count == fix(pre_alignment_event_count), ...
    'match_triggers:InvalidStartupMetadata', ...
    'EDF pre-validation event count must be a nonnegative integer.')

if validation_sequence_count == 0
    assert(pre_alignment_event_count == 0, ...
        'match_triggers:InvalidStartupMetadata', ...
        'EDF without validation cannot have pre-validation events.')
    startup_mode = "no_validation";
    return
end

assert(pre_alignment_event_count < event_count, ...
    'match_triggers:InvalidStartupMetadata', ...
    'No regular EDF triggers remain after the final validation sequence.')
cycle_start_event_index = pre_alignment_event_count + 1;
if pre_alignment_event_count == 0
    startup_mode = "normal_validation_start";
else
    startup_mode = "restart_at_last_validation";
end

end

%%
function [canonical_cycle, repeat_count, chunk_report] = ...
    extract_cycle_subset( ...
        event_table, Fs, tolerance_sec, start_event_index)

subset_event_table = event_table(start_event_index:end, :);
[canonical_cycle, repeat_count, chunk_report] = ...
    extract_canonical_cycle(subset_event_table, Fs, tolerance_sec);
event_index_offset = start_event_index - 1;
chunk_report.start_event_index = ...
    chunk_report.start_event_index + event_index_offset;
chunk_report.end_event_index = ...
    chunk_report.end_event_index + event_index_offset;

end

%%
function validate_post_validation_restart( ...
    eeg_event_table, eeg_Fs, eeg_chunk_report, ...
    edf_event_table, edf_Fs, edf_chunk_report, tolerance_sec)

first_cycles_are_complete = ...
    eeg_chunk_report.status(1) == "match" && ...
    edf_chunk_report.status(1) == "match";
if first_cycles_are_complete
    eeg_edges = extract_chunk_edges( ...
        eeg_event_table, eeg_Fs, eeg_chunk_report, 1);
    edf_edges = extract_chunk_edges( ...
        edf_event_table, edf_Fs, edf_chunk_report, 1);
    first_cycles_are_complete = edges_match( ...
        eeg_edges, edf_edges, tolerance_sec);
end

if ~first_cycles_are_complete
    error('match_triggers:PostValidationCycleMismatch', ...
        ['The first complete EDF cycle after the final validation sequence ' ...
         'does not match HD-EEG cycle 1.'])
end

end

%%
function [result, eeg_anchor_event_index, edf_anchor_event_index] = ...
    resolve_partial_start( ...
        result, eeg_event_table, eeg_Fs, eeg_chunk_report, ...
        edf_event_table, edf_Fs, ...
        edf_chunk_report, edf_canonical_edges, tolerance_sec)

assert(height(edf_chunk_report) >= 2 && ...
    edf_chunk_report.status(1) == "partial_start", ...
    'match_triggers:InvalidPartialStart', ...
    'EDF partial start must precede an intact four-64 boundary.')
partial_event_index = ( ...
    edf_chunk_report.start_event_index(1): ...
    edf_chunk_report.end_event_index(1))';
if ~all(strip(string(edf_event_table.type(partial_event_index))) == "63")
    error('match_triggers:LateStartPrefixNotPure63', ...
        ['EDF triggers before the first intact four-64 boundary must all ' ...
         'be regular 63 triggers.'])
end

edf_partial_edges = extract_chunk_edges( ...
    edf_event_table, edf_Fs, edf_chunk_report, 1);
matching_interval_count = height(edf_partial_edges);
if matching_interval_count < 2
    error('match_triggers:LateStartInsufficientEvidence', ...
        ['At least two consecutive EDF intervals are required to establish ' ...
         'a partial-cycle initial alignment.'])
end

canonical_candidates = matching_sequence_starts( ...
    edf_partial_edges, edf_canonical_edges, tolerance_sec);
if isempty(canonical_candidates)
    error('match_triggers:LateStartCanonicalMismatch', ...
        ['The leading EDF intervals do not match a contiguous portion of ' ...
         'the canonical EDF cycle.'])
elseif numel(canonical_candidates) > 1
    error('match_triggers:LateStartAmbiguous', ...
        'The leading EDF intervals match multiple canonical cycle phases.')
end
canonical_start_interval = canonical_candidates(1);
if canonical_start_interval + matching_interval_count - 1 ~= ...
        height(edf_canonical_edges)
    error('match_triggers:LateStartNotCanonicalSuffix', ...
        ['The leading EDF intervals match the canonical cycle but do not ' ...
         'form its suffix through the next boundary.'])
end

if eeg_chunk_report.status(1) ~= "match"
    error('match_triggers:LateStartEegFirstCycleMismatch', ...
        'HD-EEG cycle 1 is not a complete canonical cycle.')
end
eeg_first_edges = extract_chunk_edges( ...
    eeg_event_table, eeg_Fs, eeg_chunk_report, 1);
eeg_candidates = matching_sequence_starts( ...
    edf_partial_edges, eeg_first_edges, tolerance_sec);
if isempty(eeg_candidates)
    error('match_triggers:LateStartEegFirstCycleMismatch', ...
        'The leading EDF intervals do not match HD-EEG cycle 1.')
elseif numel(eeg_candidates) > 1
    error('match_triggers:LateStartAmbiguous', ...
        'The leading EDF intervals match multiple phases in HD-EEG cycle 1.')
end
eeg_start_interval = eeg_candidates(1);
if eeg_start_interval ~= canonical_start_interval || ...
        eeg_start_interval + matching_interval_count - 1 ~= ...
            height(eeg_first_edges)
    error('match_triggers:LateStartPhaseDisagreement', ...
        ['Canonical EDF and actual HD-EEG cycle-1 evidence do not identify ' ...
         'the same suffix phase.'])
end

eeg_anchor_event_index = ...
    eeg_first_edges.source_event_index(eeg_start_interval);
edf_anchor_event_index = edf_partial_edges.source_event_index(1);
result.startup_mode = "partial_cycle_late_start";
result.initial_alignment_reason = "partial_cycle_late_start";
result.initial_cycle_offset_uncertain = true;
result.initial_canonical_interval_number = canonical_start_interval;
result.initial_matching_interval_count = matching_interval_count;
result.initial_matching_candidate_count = 1;
result.initial_matching_prefix_interval_count = 0;
result.initial_matching_suffix_interval_count = matching_interval_count;
result.comparison_history = [result.comparison_history; ...
    make_history_row( ...
        1, 1, eeg_chunk_report.status(1), edf_chunk_report.status(1), ...
        "partial_start_match", "initial_canonical_suffix_match", 2, 2)];

end

%%
function candidate_start = matching_sequence_starts( ...
    target_edges, reference_edges, tolerance_sec)

candidate_start = zeros(0, 1);
target_count = height(target_edges);
for start_i = 1:(height(reference_edges) - target_count + 1)
    comparison_edges = reference_edges( ...
        start_i:(start_i + target_count - 1), :);
    if edges_match(target_edges, comparison_edges, tolerance_sec)
        candidate_start(end + 1, 1) = start_i; %#ok<AGROW>
    end
end

end

%%
function [interruptions, has_interruptions] = ...
    initialize_amplifier_interruptions(eeg_input)

required_variables = [ ...
    "interruption_id", "pairing_status", ...
    "disconnect_raw_event_index", "disconnect_latency", ...
    "disconnect_event_text", ...
    "reconnect_raw_event_index", "reconnect_latency", ...
    "reconnect_event_text", ...
    "eeg_start_anchor_event_index", "eeg_start_anchor_latency", ...
    "eeg_end_anchor_event_index", "eeg_end_anchor_latency"];

if ~isfield(eeg_input, 'amplifier_interruptions')
    interruptions = table( ...
        zeros(0, 1), strings(0, 1), ...
        nan(0, 1), nan(0, 1), strings(0, 1), ...
        nan(0, 1), nan(0, 1), strings(0, 1), ...
        nan(0, 1), nan(0, 1), nan(0, 1), nan(0, 1), ...
        'VariableNames', cellstr(required_variables));
else
    interruptions = eeg_input.amplifier_interruptions;
    assert(istable(interruptions), ...
        'eeg_input.amplifier_interruptions must be a table.')
    assert(all(ismember(required_variables, ...
        string(interruptions.Properties.VariableNames))), ...
        ['eeg_input.amplifier_interruptions is missing one or more ' ...
         'required variables.'])
    assert(all(ismember(interruptions.pairing_status, ...
        ["paired"; "missing_reconnect"])), ...
        'Unsupported amplifier interruption pairing status.')
end

n_interruptions = height(interruptions);
interruptions.gap_group_index = zeros(n_interruptions, 1);
interruptions.resolution_status = ...
    repmat("not_reached", n_interruptions, 1);
interruptions.exclude_from_segments = false(n_interruptions, 1);
interruptions.edf_start_anchor_event_index = nan(n_interruptions, 1);
interruptions.edf_start_anchor_latency = nan(n_interruptions, 1);
interruptions.edf_end_anchor_event_index = nan(n_interruptions, 1);
interruptions.edf_end_anchor_latency = nan(n_interruptions, 1);

group_i = 0;
current_group_end = -Inf;
for interruption_i = 1:n_interruptions
    start_anchor = ...
        interruptions.eeg_start_anchor_event_index(interruption_i);
    end_anchor = ...
        interruptions.eeg_end_anchor_event_index(interruption_i);
    if isnan(start_anchor)
        interval_start = -Inf;
    else
        interval_start = start_anchor;
    end
    if interruptions.pairing_status(interruption_i) == ...
            "missing_reconnect" || isnan(end_anchor)
        interval_end = Inf;
    elseif isnan(start_anchor)
        interval_end = end_anchor;
    else
        interval_end = max(end_anchor, start_anchor + 1);
    end

    if group_i == 0 || interval_start > current_group_end
        group_i = group_i + 1;
        current_group_end = interval_end;
    else
        current_group_end = max(current_group_end, interval_end);
    end
    interruptions.gap_group_index(interruption_i) = group_i;
end

has_interruptions = n_interruptions > 0;

end

%%
function [result, interruptions, eeg_initial_anchor, ...
    edf_initial_anchor, eeg_event_table] = ...
    resolve_leading_amplifier_interruption( ...
        result, interruptions, eeg_initial_anchor, edf_initial_anchor, ...
        eeg_event_table, eeg_Fs, eeg_chunk_report, ...
        edf_event_table, edf_Fs, edf_chunk_report, edf_chunk_i, ...
        tolerance_sec)

leading_rows = find( ...
    isnan(interruptions.eeg_start_anchor_event_index) & ...
    interruptions.resolution_status == "not_reached");
if isempty(leading_rows)
    return
end

leading_groups = unique(interruptions.gap_group_index(leading_rows), ...
    'stable');
if numel(leading_groups) ~= 1
    error('match_triggers:MultipleLeadingAmplifierInterruptions', ...
        'Only one connected leading amplifier interruption is possible.')
end
group_rows = interruptions.gap_group_index == leading_groups;
end_anchor = max( ...
    interruptions.eeg_end_anchor_event_index(group_rows), [], 'omitnan');
if isempty(end_anchor) || isnan(end_anchor) || ...
        end_anchor >= height(eeg_event_table)
    error('match_triggers:UnanchoredLeadingAmplifierInterruption', ...
        ['A leading amplifier interruption has no complete post-reconnect ' ...
         'trigger interval. Initial alignment cannot be established.'])
end
if end_anchor <= eeg_initial_anchor
    interruptions.resolution_status(group_rows) = ...
        "before_initial_alignment";
    interruptions.exclude_from_segments(group_rows) = true;
    return
end
if end_anchor > eeg_chunk_report.end_event_index( ...
        result.initial_eeg_chunk_index)
    error('match_triggers:AmplifierCycleCountAmbiguity', ...
        ['A leading amplifier interruption reaches beyond the first ' ...
         'canonical cycle. Its EDF cycle placement is ambiguous.'])
end

event_offset = end_anchor - eeg_initial_anchor;
edf_end_anchor = edf_initial_anchor + event_offset;
if edf_end_anchor >= height(edf_event_table) || ...
        string(eeg_event_table.type(end_anchor)) ~= ...
        string(edf_event_table.type(edf_end_anchor))
    error('match_triggers:LeadingAmplifierRelockFailed', ...
        'The first post-reconnect trigger has no corresponding EDF anchor.')
end

eeg_edges = extract_chunk_edges( ...
    eeg_event_table, eeg_Fs, eeg_chunk_report, ...
    result.initial_eeg_chunk_index);
edf_edges = extract_chunk_edges( ...
    edf_event_table, edf_Fs, edf_chunk_report, edf_chunk_i);
eeg_confirm_i = find( ...
    eeg_edges.source_event_index == end_anchor, 1);
edf_confirm_i = find( ...
    edf_edges.source_event_index == edf_end_anchor, 1);
if isempty(eeg_confirm_i) || isempty(edf_confirm_i) || ...
        ~single_edge_matches( ...
            eeg_edges, eeg_confirm_i, edf_edges, edf_confirm_i, ...
            tolerance_sec)
    error('match_triggers:LeadingAmplifierRelockFailed', ...
        ['The first full post-reconnect trigger interval does not match ' ...
         'the corresponding EDF interval.'])
end

for interruption_i = find(group_rows)'
    interruptions.resolution_status(interruption_i) = ...
        "leading_relocked";
    interruptions.exclude_from_segments(interruption_i) = true;
    row_end_anchor = ...
        interruptions.eeg_end_anchor_event_index(interruption_i);
    if isfinite(row_end_anchor) && row_end_anchor > eeg_initial_anchor
        row_offset = row_end_anchor - eeg_initial_anchor;
        row_edf_end_anchor = edf_initial_anchor + row_offset;
        interruptions.edf_end_anchor_event_index(interruption_i) = ...
            row_edf_end_anchor;
        interruptions.edf_end_anchor_latency(interruption_i) = ...
            double(edf_event_table.latency(row_edf_end_anchor));
    end
end

eeg_initial_anchor = end_anchor;
edf_initial_anchor = edf_end_anchor;
eeg_event_table.is_pre_alignment(1:end_anchor - 1) = true;
result.initial_alignment_reason = "amplifier_reconnect";

end

%%
function interruptions = resolve_skipped_partial_start_interruptions( ...
    interruptions, eeg_initial_anchor, eeg_chunk_report, n_eeg_events)

unresolved_groups = unique(interruptions.gap_group_index( ...
    interruptions.resolution_status == "not_reached"), 'stable');
partial_chunk_end = eeg_chunk_report.end_event_index(1);

for group_i = unresolved_groups'
    group_rows = interruptions.gap_group_index == group_i;
    [start_anchor, end_anchor, is_leading] = amplifier_group_bounds( ...
        interruptions, group_i, n_eeg_events);
    if ~is_leading && isfinite(end_anchor) && ...
            end_anchor <= eeg_initial_anchor
        interruptions.resolution_status(group_rows) = ...
            "before_initial_alignment";
        interruptions.exclude_from_segments(group_rows) = true;
    elseif is_leading || ~isfinite(start_anchor) || ...
            start_anchor <= partial_chunk_end
        error('match_triggers:PartialStartAmplifierInterruption', ...
            ['An unresolved HD-EEG amplifier interruption overlaps the ' ...
             'matched partial first cycle. Its alignment cannot be ' ...
             'established automatically.'])
    end
end

end

%%
function [terminal_group_ids, interruptions] = ...
    terminal_amplifier_groups( ...
        interruptions, eeg_chunk_report, eeg_chunk_i, n_eeg_events)

terminal_group_ids = zeros(0, 1);
unresolved_groups = unique(interruptions.gap_group_index( ...
    interruptions.resolution_status == "not_reached"), 'stable');
chunk_start = eeg_chunk_report.start_event_index(eeg_chunk_i);
chunk_end = eeg_chunk_report.end_event_index(eeg_chunk_i);

for group_i = unresolved_groups'
    [start_anchor, end_anchor, is_leading, is_terminal] = ...
        amplifier_group_bounds(interruptions, group_i, n_eeg_events);
    if is_leading && is_terminal
        error('match_triggers:UnanchoredLeadingAmplifierInterruption', ...
            ['The EEG recording begins inside an amplifier interruption ' ...
             'and never establishes a post-reconnect interval.'])
    end
    if is_terminal && isfinite(start_anchor) && ...
            start_anchor >= chunk_start && start_anchor <= chunk_end
        terminal_group_ids(end + 1, 1) = group_i; %#ok<AGROW>
    elseif isfinite(end_anchor) && end_anchor < start_anchor
        error('match_triggers:InvalidAmplifierAnchors', ...
            'Amplifier interruption anchors occur out of order.')
    end
end

end

%%
function [result, eeg_event_table, edf_event_table, interruptions] = ...
    align_terminal_amplifier_loss( ...
        result, group_ids, interruptions, eeg_chunk_i, edf_chunk_i, ...
        eeg_event_table, eeg_Fs, eeg_chunk_report, ...
        edf_event_table, edf_Fs, edf_chunk_report, tolerance_sec)

start_anchor = Inf;
for group_i = group_ids'
    [group_start, ~] = amplifier_group_bounds( ...
        interruptions, group_i, height(eeg_event_table));
    start_anchor = min(start_anchor, group_start);
end

eeg_chunk_start = eeg_chunk_report.start_event_index(eeg_chunk_i);
edf_chunk_start = edf_chunk_report.start_event_index(edf_chunk_i);
event_offset = start_anchor - eeg_chunk_start;
edf_start_anchor = edf_chunk_start + event_offset;
if edf_start_anchor > height(edf_event_table) || ...
        string(eeg_event_table.type(start_anchor)) ~= ...
        string(edf_event_table.type(edf_start_anchor))
    error('match_triggers:TerminalAmplifierAnchorMismatch', ...
        'The last pre-disconnect EEG trigger has no corresponding EDF trigger.')
end

eeg_edges = extract_chunk_edges( ...
    eeg_event_table, eeg_Fs, eeg_chunk_report, eeg_chunk_i);
edf_edges = extract_chunk_edges( ...
    edf_event_table, edf_Fs, edf_chunk_report, edf_chunk_i);
prefix_edge_count = find( ...
    eeg_edges.source_event_index == start_anchor, 1) - 1;
if isempty(prefix_edge_count) || height(eeg_edges) ~= height(edf_edges)
    error('match_triggers:TerminalAmplifierAnchorMismatch', ...
        'The terminal amplifier interruption cannot be mapped to EDF safely.')
end
for edge_i = 1:prefix_edge_count
    if ~single_edge_matches( ...
            eeg_edges, edge_i, edf_edges, edge_i, tolerance_sec)
        error('match_triggers:TerminalAmplifierAnchorMismatch', ...
            ['EEG and EDF differ before the terminal amplifier ' ...
             'disconnect anchor.'])
    end
end

for group_i = group_ids'
    group_rows = interruptions.gap_group_index == group_i;
    for interruption_i = find(group_rows)'
        interruptions.resolution_status(interruption_i) = ...
            "terminal_eeg_loss";
        interruptions.exclude_from_segments(interruption_i) = true;
        row_start = ...
            interruptions.eeg_start_anchor_event_index(interruption_i);
        row_offset = row_start - eeg_chunk_start;
        row_edf_start = edf_chunk_start + row_offset;
        interruptions.edf_start_anchor_event_index(interruption_i) = ...
            row_edf_start;
        interruptions.edf_start_anchor_latency(interruption_i) = ...
            double(edf_event_table.latency(row_edf_start));
    end
end

result.missing_periods = [result.missing_periods; ...
    make_missing_period( ...
        "eeg", start_anchor, NaN, eeg_event_table, eeg_Fs, ...
        "amplifier_disconnect", eeg_chunk_i, edf_chunk_i)];
result = record_problem( ...
    result, eeg_chunk_i, edf_chunk_i, ...
    eeg_chunk_report.status(eeg_chunk_i), ...
    edf_chunk_report.status(edf_chunk_i), ...
    "eeg_data_loss", "terminal_eeg_loss", NaN, NaN);

eeg_event_table.is_terminal(start_anchor:end) = true;
edf_event_table.is_terminal(edf_start_anchor:end) = true;
eeg_event_table.is_terminal_alignment_anchor(start_anchor) = true;
edf_event_table.is_terminal_alignment_anchor(edf_start_anchor) = true;
result.terminal_chunk_handled = true;
result.terminal_chunk_deferred = true;
result.terminal_relation = "eeg_shorter";
result.terminal_later_action = "zero_pad_eeg";
result.eeg_zero_padding_required = true;
result.eeg_terminal_chunk_indices = ...
    eeg_chunk_i:height(eeg_chunk_report);
result.edf_terminal_chunk_indices = ...
    edf_chunk_i:height(edf_chunk_report);
result.eeg_terminal_anchor_event_index = start_anchor;
result.edf_terminal_anchor_event_index = edf_start_anchor;
result.eeg_terminal_anchor_latency = ...
    double(eeg_event_table.latency(start_anchor));
result.edf_terminal_anchor_latency = ...
    double(edf_event_table.latency(edf_start_anchor));
result.terminal_common_trigger_count = event_offset + 1;
result.requires_relock = false;
result.stopped_reason = "terminal_region_identified";

end

%%
function [result, interruptions, action] = ...
    resolve_amplifier_interruptions_in_chunk( ...
        result, interruptions, eeg_chunk_i, edf_chunk_i, ...
        eeg_event_table, eeg_Fs, eeg_chunk_report, eeg_edges, ...
        edf_event_table, edf_chunk_report, edf_edges, ...
        eeg_status, edf_status, tolerance_sec)

action = "none";
chunk_start = eeg_chunk_report.start_event_index(eeg_chunk_i);
chunk_end = eeg_chunk_report.end_event_index(eeg_chunk_i);
candidate_rows = ...
    (interruptions.resolution_status == "not_reached" & ...
     isfinite(interruptions.eeg_start_anchor_event_index) & ...
     interruptions.eeg_start_anchor_event_index >= chunk_start & ...
     interruptions.eeg_start_anchor_event_index <= chunk_end) | ...
    (eeg_chunk_i == 1 & ...
     interruptions.resolution_status == "leading_relocked") | ...
    (interruptions.resolution_status == "excluded_and_relocked" & ...
     isfinite(interruptions.eeg_start_anchor_event_index) & ...
     isfinite(interruptions.eeg_end_anchor_event_index) & ...
     interruptions.eeg_start_anchor_event_index < chunk_start & ...
     interruptions.eeg_end_anchor_event_index >= chunk_start);
group_ids = unique( ...
    interruptions.gap_group_index(candidate_rows), 'stable');
if isempty(group_ids)
    return
end

all_group_rows = ismember(interruptions.gap_group_index, group_ids);
group_end = max( ...
    interruptions.eeg_end_anchor_event_index(all_group_rows), [], ...
    'omitnan');
if isempty(group_end) || isnan(group_end) || ...
        ~any(edf_status == ["match", "partial_end"])
    interruptions.resolution_status(all_group_rows) = "manual_review";
    return
end
for group_i = group_ids'
    group_rows = interruptions.gap_group_index == group_i;
    if all(interruptions.resolution_status(group_rows) ~= "not_reached")
        continue
    end
    [group_start_anchor, group_end_anchor] = amplifier_group_bounds( ...
        interruptions, group_i, height(eeg_event_table));
    if isfinite(group_start_anchor) && isfinite(group_end_anchor) && ...
            group_end_anchor - group_start_anchor >= height(edf_edges)
        interruptions.resolution_status(all_group_rows) = "manual_review";
        result.missing_periods = [result.missing_periods; ...
            make_missing_period( ...
                "eeg", group_start_anchor, group_end_anchor, ...
                eeg_event_table, eeg_Fs, "manual_cycle_count_review", ...
                eeg_chunk_i, edf_chunk_i)];
        result = record_problem( ...
            result, eeg_chunk_i, edf_chunk_i, eeg_status, edf_status, ...
            "eeg_data_loss", "unsupported_cycle_count_ambiguity", ...
            NaN, NaN);
        result.requires_relock = true;
        result.stopped_reason = "unsupported_cycle_count_ambiguity";
        action = "stop";
        return
    end
end
if height(eeg_edges) ~= height(edf_edges) || ...
        ~isequal(eeg_edges.source_type, edf_edges.source_type) || ...
        ~isequal(eeg_edges.destination_type, edf_edges.destination_type)
    return
end

n_edges = height(eeg_edges);
edge_matches = false(n_edges, 1);
for edge_i = 1:n_edges
    edge_matches(edge_i) = single_edge_matches( ...
        eeg_edges, edge_i, edf_edges, edge_i, tolerance_sec);
end

marked_edge = false(n_edges, 1);
group_masks = cell(numel(group_ids), 1);
for group_offset = 1:numel(group_ids)
    group_i = group_ids(group_offset);
    group_rows = find(interruptions.gap_group_index == group_i);
    group_mask = false(n_edges, 1);
    for interruption_i = group_rows'
        start_anchor = ...
            interruptions.eeg_start_anchor_event_index(interruption_i);
        end_anchor = ...
            interruptions.eeg_end_anchor_event_index(interruption_i);
        if isnan(start_anchor)
            row_mask = ...
                eeg_edges.source_event_index < end_anchor;
        elseif end_anchor > start_anchor
            row_mask = ...
                eeg_edges.source_event_index >= start_anchor & ...
                eeg_edges.source_event_index < end_anchor;
        else
            row_mask = eeg_edges.source_event_index == start_anchor;
        end
        group_mask = group_mask | row_mask;
    end
    group_masks{group_offset} = group_mask;
    marked_edge = marked_edge | group_mask;
end

outside_mismatch = any(~edge_matches & ~marked_edge);
eeg_longer_mismatch = any( ...
    marked_edge & ~edge_matches & ...
    eeg_edges.interval_sec > edf_edges.interval_sec + tolerance_sec);
if outside_mismatch || eeg_longer_mismatch
    interruptions.resolution_status(all_group_rows) = "manual_review";
    return
end

excluded_group = false(numel(group_ids), 1);
for group_offset = 1:numel(group_ids)
    group_i = group_ids(group_offset);
    group_rows = interruptions.gap_group_index == group_i;
    group_mask = group_masks{group_offset};
    is_leading_group = all(isnan( ...
        interruptions.eeg_start_anchor_event_index(group_rows)));
    was_excluded = all(interruptions.resolution_status(group_rows) == ...
        "excluded_and_relocked");
    [group_start_anchor, group_end_anchor] = amplifier_group_bounds( ...
        interruptions, group_i, height(eeg_event_table));
    is_single_interval = isfinite(group_start_anchor) && ...
        isfinite(group_end_anchor) && ...
        group_end_anchor - group_start_anchor == 1;
    retained = ~was_excluded && ~is_leading_group && ...
        is_single_interval && ...
        all(edge_matches(group_mask));

    for interruption_i = find(group_rows)'
        start_anchor = ...
            interruptions.eeg_start_anchor_event_index(interruption_i);
        end_anchor = ...
            interruptions.eeg_end_anchor_event_index(interruption_i);
        [edf_end_anchor, end_anchor_mapped] = ...
            map_eeg_anchor_to_edf( ...
                end_anchor, eeg_chunk_i, edf_chunk_i, ...
                eeg_event_table, eeg_chunk_report, ...
                edf_event_table, edf_chunk_report);
        if ~end_anchor_mapped
            interruptions.resolution_status(all_group_rows) = ...
                "manual_review";
            action = "stop";
            result.requires_relock = true;
            result.stopped_reason = ...
                "unsupported_cycle_count_ambiguity";
            return
        end
        if isfinite(start_anchor)
            [edf_start_anchor, start_anchor_mapped] = ...
                map_eeg_anchor_to_edf( ...
                    start_anchor, eeg_chunk_i, edf_chunk_i, ...
                    eeg_event_table, eeg_chunk_report, ...
                    edf_event_table, edf_chunk_report);
            if ~start_anchor_mapped
                interruptions.resolution_status(all_group_rows) = ...
                    "manual_review";
                action = "stop";
                result.requires_relock = true;
                result.stopped_reason = ...
                    "unsupported_cycle_count_ambiguity";
                return
            end
            interruptions.edf_start_anchor_event_index(interruption_i) = ...
                edf_start_anchor;
            interruptions.edf_start_anchor_latency(interruption_i) = ...
                double(edf_event_table.latency(edf_start_anchor));
        end
        interruptions.edf_end_anchor_event_index(interruption_i) = ...
            edf_end_anchor;
        interruptions.edf_end_anchor_latency(interruption_i) = ...
            double(edf_event_table.latency(edf_end_anchor));
        if was_excluded
            interruptions.resolution_status(interruption_i) = ...
                "excluded_and_relocked";
            interruptions.exclude_from_segments(interruption_i) = true;
        elseif is_leading_group
            interruptions.resolution_status(interruption_i) = ...
                "leading_relocked";
            interruptions.exclude_from_segments(interruption_i) = true;
        elseif retained
            interruptions.resolution_status(interruption_i) = ...
                "retained_within_tolerance";
        else
            interruptions.resolution_status(interruption_i) = ...
                "excluded_and_relocked";
            interruptions.exclude_from_segments(interruption_i) = true;
        end
    end

    if ~retained
        excluded_group(group_offset) = true;
        if ~is_leading_group && ~was_excluded
            [start_anchor, end_anchor] = amplifier_group_bounds( ...
                interruptions, group_i, height(eeg_event_table));
            result.missing_periods = [result.missing_periods; ...
                make_missing_period( ...
                    "eeg", start_anchor, end_anchor, ...
                    eeg_event_table, eeg_Fs, "amplifier_disconnect", ...
                    eeg_chunk_i, edf_chunk_i)];
        end
    end
end

if any(excluded_group)
    result = record_problem( ...
        result, eeg_chunk_i, edf_chunk_i, eeg_status, edf_status, ...
        "eeg_data_loss", "resumed_same_offset", ...
        eeg_chunk_i + 1, edf_chunk_i + 1);
    result.requires_relock = false;
    action = "advance";
end

end

%%
function [edf_anchor, mapped] = map_eeg_anchor_to_edf( ...
    eeg_anchor, current_eeg_chunk_i, current_edf_chunk_i, ...
    eeg_event_table, eeg_chunk_report, edf_event_table, edf_chunk_report)

if isnan(eeg_anchor)
    edf_anchor = NaN;
    mapped = true;
    return
end

eeg_anchor_chunk_i = find( ...
    eeg_chunk_report.start_event_index <= eeg_anchor & ...
    eeg_chunk_report.end_event_index >= eeg_anchor, 1, 'first');
if isempty(eeg_anchor_chunk_i)
    edf_anchor = NaN;
    mapped = false;
    return
end

edf_anchor_chunk_i = current_edf_chunk_i + ...
    (eeg_anchor_chunk_i - current_eeg_chunk_i);
if edf_anchor_chunk_i < 1 || ...
        edf_anchor_chunk_i > height(edf_chunk_report)
    edf_anchor = NaN;
    mapped = false;
    return
end

event_offset = eeg_anchor - ...
    eeg_chunk_report.start_event_index(eeg_anchor_chunk_i);
edf_anchor = ...
    edf_chunk_report.start_event_index(edf_anchor_chunk_i) + event_offset;
mapped = edf_anchor <= edf_chunk_report.end_event_index(edf_anchor_chunk_i) && ...
    string(eeg_event_table.type(eeg_anchor)) == ...
        string(edf_event_table.type(edf_anchor));
if ~mapped
    edf_anchor = NaN;
end

end

%%
function [interruptions, missing_period, resolved] = ...
    resolve_generic_amplifier_loss( ...
        interruptions, inferred_start_anchor, inferred_end_anchor, ...
        prefix_count, suffix_count, eeg_chunk_i, edf_chunk_i, ...
        next_edf_chunk_i, resolution_status, ...
        eeg_event_table, eeg_Fs, eeg_chunk_report, ...
        edf_event_table, edf_Fs, edf_chunk_report, edf_edges)

missing_period = empty_missing_period_table;
resolved = false;
chunk_start = eeg_chunk_report.start_event_index(eeg_chunk_i);
chunk_end = eeg_chunk_report.end_event_index(eeg_chunk_i);
candidate_rows = ...
    interruptions.resolution_status == "not_reached" & ...
    isfinite(interruptions.eeg_start_anchor_event_index) & ...
    interruptions.eeg_start_anchor_event_index >= chunk_start & ...
    interruptions.eeg_start_anchor_event_index <= chunk_end;
group_ids = unique( ...
    interruptions.gap_group_index(candidate_rows), 'stable');
if isempty(group_ids)
    return
end

all_group_rows = ismember(interruptions.gap_group_index, group_ids);
if numel(group_ids) ~= 1 || ...
        resolution_status == "unsupported_cycle_count_ambiguity" || ...
        ~isfinite(next_edf_chunk_i) || suffix_count == 0
    interruptions.resolution_status(all_group_rows) = "manual_review";
    return
end

group_i = group_ids(1);
[start_anchor, end_anchor] = amplifier_group_bounds( ...
    interruptions, group_i, height(eeg_event_table));
if start_anchor ~= inferred_start_anchor || ...
        end_anchor ~= inferred_end_anchor
    interruptions.resolution_status(all_group_rows) = "manual_review";
    return
end

edf_start_anchor = anchor_after_prefix(edf_edges, prefix_count);
clean_suffix_chunk_i = next_edf_chunk_i - 1;
if clean_suffix_chunk_i < 1 || ...
        clean_suffix_chunk_i > height(edf_chunk_report)
    interruptions.resolution_status(all_group_rows) = "manual_review";
    return
end
clean_suffix_edges = extract_chunk_edges( ...
    edf_event_table, edf_Fs, edf_chunk_report, clean_suffix_chunk_i);
first_suffix_edge = height(clean_suffix_edges) - suffix_count + 1;
if first_suffix_edge < 1
    interruptions.resolution_status(all_group_rows) = "manual_review";
    return
end
edf_end_anchor = ...
    clean_suffix_edges.source_event_index(first_suffix_edge);

for interruption_i = find(all_group_rows)'
    interruptions.resolution_status(interruption_i) = ...
        "excluded_and_relocked";
    interruptions.exclude_from_segments(interruption_i) = true;
    interruptions.edf_start_anchor_event_index(interruption_i) = ...
        edf_start_anchor;
    interruptions.edf_start_anchor_latency(interruption_i) = ...
        double(edf_event_table.latency(edf_start_anchor));
    interruptions.edf_end_anchor_event_index(interruption_i) = ...
        edf_end_anchor;
    interruptions.edf_end_anchor_latency(interruption_i) = ...
        double(edf_event_table.latency(edf_end_anchor));
end

missing_period = make_missing_period( ...
    "eeg", start_anchor, end_anchor, eeg_event_table, eeg_Fs, ...
    "amplifier_disconnect", eeg_chunk_i, edf_chunk_i);
resolved = true;

end

%%
function [start_anchor, end_anchor, is_leading, is_terminal] = ...
    amplifier_group_bounds(interruptions, group_i, n_eeg_events)

group_rows = interruptions.gap_group_index == group_i;
start_values = interruptions.eeg_start_anchor_event_index(group_rows);
end_values = interruptions.eeg_end_anchor_event_index(group_rows);
start_anchor = min(start_values, [], 'omitnan');
end_anchor = max(end_values, [], 'omitnan');
is_leading = all(isnan(start_values));
is_terminal = any( ...
    interruptions.pairing_status(group_rows) == "missing_reconnect") || ...
    all(isnan(end_values));

if isempty(start_anchor)
    start_anchor = NaN;
end
if isempty(end_anchor)
    end_anchor = NaN;
end
if ~is_terminal && isfinite(end_anchor) && end_anchor >= n_eeg_events
    is_terminal = true;
end
if ~is_leading && isfinite(start_anchor) && isfinite(end_anchor) && ...
        end_anchor <= start_anchor
    end_anchor = start_anchor + 1;
end

end

%%
function [result, edf_chunk_i, edf_event_table] = ...
    resolve_initial_alignment( ...
        result, eeg_event_table, eeg_Fs, eeg_chunk_report, ...
        edf_event_table, edf_Fs, edf_canonical_edges, edf_chunk_report, ...
        tolerance_sec)

% T1...T50 label trigger positions within a cycle, not chunk numbers.
edf_chunk_i = 1;
if ~eeg_chunk_report.has_next_boundary(1) || ...
        ~edf_chunk_report.has_next_boundary(1)
    return
end

eeg_first_edges = extract_chunk_edges( ...
    eeg_event_table, eeg_Fs, eeg_chunk_report, 1);
edf_first_edges = extract_chunk_edges( ...
    edf_event_table, edf_Fs, edf_chunk_report, 1);
if edges_match(eeg_first_edges, edf_first_edges, tolerance_sec)
    return
end
if eeg_chunk_report.status(1) ~= "match"
    return
end

if edf_chunk_report.status(1) == "match"
    return
end

edf_first_trigger_count = edf_chunk_report.observed_trigger_count(1);
canonical_trigger_count = height(edf_canonical_edges);
if edf_first_trigger_count > canonical_trigger_count && ...
        edf_chunk_report.reason(1) == "suspected_missing_boundary" && ...
        edf_chunk_report.estimated_cycle_count(1) == 2
    % Missing boundary -- EDF chunk 1 contains parts of two EEG cycles.
    % EEG: [T1 ........ T50] [T1 ........ T50] [T1 ...]
    % EDF: [T1 ........ T50      T7 .... T50] [T1 ...]
    % Keep EEG1 <-> EDF1; the main loop skips the consumed EEG cycle.
    result.initial_alignment_reason = ...
        "edf_first_chunk_missing_boundary";
    result.initial_cycle_offset_uncertain = true;
    return
elseif edf_first_trigger_count >= canonical_trigger_count
    return
end

result.initial_cycle_offset_uncertain = true;

[~, ~, matching_prefix_count, matching_suffix_count] = ...
    locate_loss_anchors( ...
        edf_first_edges, edf_canonical_edges, tolerance_sec);
result.initial_matching_prefix_interval_count = matching_prefix_count;
result.initial_matching_suffix_interval_count = matching_suffix_count;
% Data loss within one cycle -- retain EEG1 <-> EDF1.
% EEG1: T1 T2 ... Tk  T(k+1) ...... T(m-1)  Tm ... T50
% EDF1: T1 T2 ... Tk  |------ missing ------|  Tm ... T50
%        matching prefix                         matching suffix
if matching_prefix_count > 0 && matching_suffix_count > 0
    result.initial_alignment_reason = "edf_first_chunk_bracketed_loss";
    return
end

% Trigger-box/HD-EEG restart -- shift EEG1 to a later EDF chunk.
% EEG1:                                T1 T2 ........ T50
% EDF1: T1 ... old/incomplete fragment | restart |
% EDFk:                                T1 T2 ........ T50
%                                      ^ new shared four-64 boundary
% Mark EDF events before EDFk as pre-alignment; start EEG1 <-> EDFk.
for candidate_chunk_i = 2:height(edf_chunk_report)
    if ~edf_chunk_report.has_next_boundary(candidate_chunk_i) || ...
            edf_chunk_report.status(candidate_chunk_i) ~= "match"
        continue
    end

    edf_candidate_edges = extract_chunk_edges( ...
        edf_event_table, edf_Fs, edf_chunk_report, candidate_chunk_i);
    if ~edges_match(eeg_first_edges, edf_candidate_edges, tolerance_sec)
        continue
    end

    % A bounded canonical candidate restarts at T1, the four-64 boundary.
    candidate_start_event_index = ...
        edf_chunk_report.start_event_index(candidate_chunk_i);
    edf_event_table.is_pre_alignment( ...
        1:candidate_start_event_index - 1) = true;
    edf_chunk_i = candidate_chunk_i;
    result.initial_edf_chunk_index = candidate_chunk_i;
    result.edf_leading_restart_inferred = true;
    result.edf_pre_alignment_event_count = ...
        candidate_start_event_index - 1;
    result.initial_alignment_reason = ...
        "edf_restart_at_t1_boundary";
    return
end

end

%%
function [result, eeg_event_table, edf_event_table] = ...
    finalize_terminal_amplifier_relock( ...
        result, eeg_chunk_i, edf_chunk_i, ...
        eeg_event_table, eeg_chunk_report, ...
        edf_event_table, edf_chunk_report)

eeg_start_event_index = ...
    eeg_chunk_report.start_event_index(eeg_chunk_i);
edf_start_event_index = ...
    edf_chunk_report.start_event_index(edf_chunk_i);
eeg_event_count = height(eeg_event_table) - eeg_start_event_index + 1;
edf_event_count = height(edf_event_table) - edf_start_event_index + 1;
if eeg_event_count ~= edf_event_count
    error('match_triggers:TerminalAmplifierRelockMismatch', ...
        ['The post-reconnect terminal regions contain different trigger ' ...
         'counts and cannot be closed automatically.'])
end

eeg_anchor_event_index = height(eeg_event_table);
edf_anchor_event_index = height(edf_event_table);
eeg_event_table.is_terminal(eeg_start_event_index:end) = true;
edf_event_table.is_terminal(edf_start_event_index:end) = true;
eeg_event_table.is_terminal_alignment_anchor( ...
    eeg_anchor_event_index) = true;
edf_event_table.is_terminal_alignment_anchor( ...
    edf_anchor_event_index) = true;

result.terminal_chunk_handled = true;
result.terminal_chunk_deferred = true;
result.terminal_relation = "same_last_trigger";
result.terminal_later_action = "undetermined_from_trigger_tables";
result.eeg_zero_padding_required = NaN;
result.eeg_terminal_chunk_indices = ...
    eeg_chunk_i:height(eeg_chunk_report);
result.edf_terminal_chunk_indices = ...
    edf_chunk_i:height(edf_chunk_report);
result.eeg_terminal_anchor_event_index = eeg_anchor_event_index;
result.edf_terminal_anchor_event_index = edf_anchor_event_index;
result.eeg_terminal_anchor_latency = ...
    double(eeg_event_table.latency(eeg_anchor_event_index));
result.edf_terminal_anchor_latency = ...
    double(edf_event_table.latency(edf_anchor_event_index));
result.terminal_common_trigger_count = eeg_event_count;
result.stopped_reason = "terminal_region_identified";

end

%%
function [result, eeg_event_table, edf_event_table] = ...
    align_terminal_region( ...
        result, eeg_chunk_i, edf_chunk_i, ...
        eeg_event_table, eeg_Fs, eeg_chunk_report, ...
        edf_event_table, edf_Fs, edf_chunk_report, tolerance_sec)

eeg_start_event_index = ...
    eeg_chunk_report.start_event_index(eeg_chunk_i);
edf_start_event_index = ...
    edf_chunk_report.start_event_index(edf_chunk_i);
eeg_terminal_event_indices = ...
    (eeg_start_event_index:height(eeg_event_table))';
edf_terminal_event_indices = ...
    (edf_start_event_index:height(edf_event_table))';

common_trigger_count = matching_terminal_prefix_count( ...
    eeg_event_table, eeg_Fs, eeg_terminal_event_indices, ...
    edf_event_table, edf_Fs, edf_terminal_event_indices, tolerance_sec);
shorter_trigger_count = min( ...
    numel(eeg_terminal_event_indices), ...
    numel(edf_terminal_event_indices));
if common_trigger_count < shorter_trigger_count
    error('match_triggers:TerminalCorrespondenceMismatch', ...
        ['EEG chunk %d and EDF chunk %d disagree at terminal trigger %d. ' ...
         'The final corresponding trigger cannot be identified safely.'], ...
        eeg_chunk_i, edf_chunk_i, common_trigger_count + 1)
end

eeg_anchor_event_index = ...
    eeg_terminal_event_indices(common_trigger_count);
edf_anchor_event_index = ...
    edf_terminal_event_indices(common_trigger_count);
eeg_remaining_trigger_count = numel(eeg_terminal_event_indices);
edf_remaining_trigger_count = numel(edf_terminal_event_indices);

if eeg_remaining_trigger_count < edf_remaining_trigger_count
    terminal_relation = "eeg_shorter";
    terminal_later_action = "zero_pad_eeg";
    eeg_zero_padding_required = true;
elseif eeg_remaining_trigger_count > edf_remaining_trigger_count
    terminal_relation = "eeg_longer";
    terminal_later_action = "match_edf_length_without_padding";
    eeg_zero_padding_required = false;
else
    terminal_relation = "same_last_trigger";
    terminal_later_action = "undetermined_from_trigger_tables";
    eeg_zero_padding_required = NaN;
end

eeg_event_table.is_terminal(eeg_start_event_index:end) = true;
edf_event_table.is_terminal(edf_start_event_index:end) = true;
eeg_event_table.is_terminal_alignment_anchor( ...
    eeg_anchor_event_index) = true;
edf_event_table.is_terminal_alignment_anchor( ...
    edf_anchor_event_index) = true;

result.terminal_chunk_handled = true;
% Padding or length matching of the raw EEG signal remains a later step.
result.terminal_chunk_deferred = true;
result.terminal_relation = terminal_relation;
result.terminal_later_action = terminal_later_action;
result.eeg_zero_padding_required = eeg_zero_padding_required;
result.eeg_terminal_chunk_indices = ...
    eeg_chunk_i:height(eeg_chunk_report);
result.edf_terminal_chunk_indices = ...
    edf_chunk_i:height(edf_chunk_report);
result.eeg_terminal_anchor_event_index = eeg_anchor_event_index;
result.edf_terminal_anchor_event_index = edf_anchor_event_index;
result.eeg_terminal_anchor_latency = ...
    double(eeg_event_table.latency(eeg_anchor_event_index));
result.edf_terminal_anchor_latency = ...
    double(edf_event_table.latency(edf_anchor_event_index));
result.terminal_common_trigger_count = common_trigger_count;
result.stopped_reason = "terminal_region_identified";
result.comparison_history = [result.comparison_history; ...
    make_history_row( ...
        eeg_chunk_i, edf_chunk_i, ...
        eeg_chunk_report.status(eeg_chunk_i), ...
        edf_chunk_report.status(edf_chunk_i), ...
        terminal_relation, "terminal_anchor_identified", NaN, NaN)];

end

%%
function prefix_count = matching_terminal_prefix_count( ...
    eeg_event_table, eeg_Fs, eeg_event_indices, ...
    edf_event_table, edf_Fs, edf_event_indices, tolerance_sec)

max_prefix_count = min(numel(eeg_event_indices), numel(edf_event_indices));
eeg_event_indices = eeg_event_indices(1:max_prefix_count);
edf_event_indices = edf_event_indices(1:max_prefix_count);
eeg_type = strip(string(eeg_event_table.type(eeg_event_indices)));
edf_type = strip(string(edf_event_table.type(edf_event_indices)));
eeg_latency = double(eeg_event_table.latency(eeg_event_indices));
edf_latency = double(edf_event_table.latency(edf_event_indices));
eeg_interval_sec = diff(eeg_latency) ./ eeg_Fs;
edf_interval_sec = diff(edf_latency) ./ edf_Fs;
comparison_scale = max([ ...
    abs(eeg_interval_sec), abs(edf_interval_sec), ...
    ones(size(eeg_interval_sec))], [], 2);
roundoff_tolerance_sec = 10 * eps(comparison_scale);

trigger_matches = eeg_type == edf_type;
trigger_matches(2:end) = trigger_matches(2:end) & ...
    abs(eeg_interval_sec - edf_interval_sec) <= ...
        tolerance_sec + roundoff_tolerance_sec;
first_mismatch = find(~trigger_matches, 1, 'first');
if isempty(first_mismatch)
    prefix_count = max_prefix_count;
else
    prefix_count = first_mismatch - 1;
end

end

%%
function result = record_problem( ...
    result, eeg_chunk_i, edf_chunk_i, eeg_status, edf_status, ...
    outcome, resolution_status, next_eeg_chunk_i, next_edf_chunk_i)

if isnan(result.first_problem_chunk)
    result.first_problem_chunk = eeg_chunk_i;
    result.first_problem_eeg_chunk = eeg_chunk_i;
    result.first_problem_edf_chunk = edf_chunk_i;
    result.eeg_status = eeg_status;
    result.edf_status = edf_status;
    result.outcome = outcome;
    result.resolution_status = resolution_status;
end
result.comparison_history = [result.comparison_history; ...
    make_history_row( ...
        eeg_chunk_i, edf_chunk_i, eeg_status, edf_status, ...
        outcome, resolution_status, next_eeg_chunk_i, next_edf_chunk_i)];

end

%%
function history_row = make_history_row( ...
    eeg_chunk_i, edf_chunk_i, eeg_status, edf_status, ...
    outcome, resolution_status, next_eeg_chunk_i, next_edf_chunk_i)

history_row = table( ...
    eeg_chunk_i, edf_chunk_i, eeg_status, edf_status, ...
    outcome, resolution_status, next_eeg_chunk_i, next_edf_chunk_i, ...
    'VariableNames', { ...
        'eeg_chunk_index', 'edf_chunk_index', 'eeg_status', 'edf_status', ...
        'outcome', 'resolution_status', ...
        'next_eeg_chunk_index', 'next_edf_chunk_index'});

end

%%
function history = empty_history_table

history = table( ...
    zeros(0, 1), zeros(0, 1), strings(0, 1), strings(0, 1), ...
    strings(0, 1), strings(0, 1), zeros(0, 1), zeros(0, 1), ...
    'VariableNames', { ...
        'eeg_chunk_index', 'edf_chunk_index', 'eeg_status', 'edf_status', ...
        'outcome', 'resolution_status', ...
        'next_eeg_chunk_index', 'next_edf_chunk_index'});

end

%%
function result = close_open_missing_periods( ...
    result, eeg_chunk_i, edf_chunk_i, ...
    eeg_event_table, eeg_Fs, eeg_chunk_report, ...
    edf_event_table, edf_Fs, edf_chunk_report)

open_period_i = find(isnan(result.missing_periods.end_anchor_event_index));
for period_i = open_period_i'
    if result.missing_periods.system(period_i) == "eeg"
        end_event_index = ...
            eeg_chunk_report.start_event_index(eeg_chunk_i);
        end_latency = double(eeg_event_table.latency(end_event_index));
        end_time_sec = (end_latency - 1) ./ eeg_Fs;
    else
        end_event_index = ...
            edf_chunk_report.start_event_index(edf_chunk_i);
        end_latency = double(edf_event_table.latency(end_event_index));
        end_time_sec = (end_latency - 1) ./ edf_Fs;
    end

    result.missing_periods.end_anchor_event_index(period_i) = end_event_index;
    result.missing_periods.end_anchor_latency(period_i) = end_latency;
    result.missing_periods.end_anchor_time_sec(period_i) = end_time_sec;
end
result.requires_relock = any( ...
    isnan(result.missing_periods.end_anchor_event_index));

end

%%
function edges = extract_chunk_edges(event_table, Fs, chunk_report, chunk_i)

start_event_index = chunk_report.start_event_index(chunk_i);
end_event_index = chunk_report.end_event_index(chunk_i);
event_index = (start_event_index:end_event_index)';

if chunk_report.has_next_boundary(chunk_i)
    assert(chunk_i < height(chunk_report), ...
        'A bounded chunk must have a following chunk boundary.')
    next_boundary_index = chunk_report.start_event_index(chunk_i + 1);
    source_event_index = event_index;
    destination_event_index = [event_index(2:end); next_boundary_index];
else
    source_event_index = event_index(1:end - 1);
    destination_event_index = event_index(2:end);
end

source_type = strip(string(event_table.type(source_event_index)));
destination_type = strip(string(event_table.type(destination_event_index)));
interval_sec = ( ...
    double(event_table.latency(destination_event_index)) - ...
    double(event_table.latency(source_event_index))) ./ Fs;

edges = table( ...
    source_type, destination_type, interval_sec, ...
    source_event_index, destination_event_index);

end

%%
function edges = extract_canonical_edges(canonical_cycle)

n_triggers = height(canonical_cycle);
source_event_index = (1:n_triggers)';
destination_event_index = [source_event_index(2:end); 1];
source_type = strip(string(canonical_cycle.type));
destination_type = source_type(destination_event_index);
interval_sec = double(canonical_cycle.interval_to_next_sec(:));

edges = table( ...
    source_type, destination_type, interval_sec, ...
    source_event_index, destination_event_index);

end

%%
function is_match = edges_match(first_edges, second_edges, tolerance_sec)

if height(first_edges) ~= height(second_edges) || ...
        ~isequal(first_edges.source_type, second_edges.source_type) || ...
        ~isequal(first_edges.destination_type, second_edges.destination_type)
    is_match = false;
    return
end

interval_error_sec = abs( ...
    first_edges.interval_sec - second_edges.interval_sec);
comparison_scale = max([ ...
    abs(first_edges.interval_sec); abs(second_edges.interval_sec); 1]);
roundoff_tolerance_sec = 10 * eps(comparison_scale);
is_match = all( ...
    interval_error_sec <= tolerance_sec + roundoff_tolerance_sec);

end

%%
function [start_anchor_event_index, end_anchor_event_index, ...
    prefix_count, suffix_count] = ...
    locate_loss_anchors(observed_edges, canonical_edges, tolerance_sec)

prefix_count = matching_prefix_count( ...
    observed_edges, canonical_edges, tolerance_sec);
start_anchor_event_index = anchor_after_prefix( ...
    observed_edges, prefix_count);

suffix_count = 0;
observed_i = height(observed_edges);
canonical_i = height(canonical_edges);
while observed_i > prefix_count && canonical_i >= 1 && ...
        single_edge_matches( ...
            observed_edges, observed_i, ...
            canonical_edges, canonical_i, tolerance_sec)
    suffix_count = suffix_count + 1;
    observed_i = observed_i - 1;
    canonical_i = canonical_i - 1;
end

if suffix_count == 0
    end_anchor_event_index = NaN;
else
    first_suffix_edge = height(observed_edges) - suffix_count + 1;
    end_anchor_event_index = ...
        observed_edges.source_event_index(first_suffix_edge);
    if end_anchor_event_index <= start_anchor_event_index
        error('match_triggers:OverlappingAnchors', ...
            'The inferred loss anchors overlap or occur out of order.')
    end
end

end

%%
function prefix_count = matching_prefix_count( ...
    observed_edges, canonical_edges, tolerance_sec)

prefix_count = 0;
max_prefix_count = min(height(observed_edges), height(canonical_edges));
while prefix_count < max_prefix_count && ...
        single_edge_matches( ...
            observed_edges, prefix_count + 1, ...
            canonical_edges, prefix_count + 1, tolerance_sec)
    prefix_count = prefix_count + 1;
end

end

%%
function event_index = anchor_after_prefix(edges, prefix_count)

assert(~isempty(edges), ...
    'A discrepant chunk must contain at least one trigger interval.')
if prefix_count < height(edges)
    event_index = edges.source_event_index(prefix_count + 1);
else
    event_index = edges.destination_event_index(end);
end

end

%%
function is_match = single_edge_matches( ...
    first_edges, first_i, second_edges, second_i, tolerance_sec)

types_match = ...
    first_edges.source_type(first_i) == second_edges.source_type(second_i) && ...
    first_edges.destination_type(first_i) == ...
        second_edges.destination_type(second_i);
comparison_scale = max([ ...
    abs(first_edges.interval_sec(first_i)), ...
    abs(second_edges.interval_sec(second_i)), 1]);
roundoff_tolerance_sec = 10 * eps(comparison_scale);
interval_matches = abs( ...
    first_edges.interval_sec(first_i) - ...
    second_edges.interval_sec(second_i)) <= ...
    tolerance_sec + roundoff_tolerance_sec;
is_match = types_match && interval_matches;

end

%%
function missing_period = make_missing_period( ...
    system, start_event_index, end_event_index, event_table, Fs, reason, ...
    eeg_chunk_i, edf_chunk_i)

start_latency = double(event_table.latency(start_event_index));
start_time_sec = (start_latency - 1) ./ Fs;

if isnan(end_event_index)
    end_latency = NaN;
    end_time_sec = NaN;
else
    end_latency = double(event_table.latency(end_event_index));
    end_time_sec = (end_latency - 1) ./ Fs;
end

missing_period = table( ...
    system, eeg_chunk_i, edf_chunk_i, start_event_index, end_event_index, ...
    start_latency, end_latency, start_time_sec, end_time_sec, reason, ...
    'VariableNames', { ...
        'system', 'eeg_chunk_index', 'edf_chunk_index', ...
        'start_anchor_event_index', 'end_anchor_event_index', ...
        'start_anchor_latency', 'end_anchor_latency', ...
        'start_anchor_time_sec', 'end_anchor_time_sec', 'reason'});

end

%%
function missing_periods = empty_missing_period_table

missing_periods = table( ...
    strings(0, 1), zeros(0, 1), zeros(0, 1), zeros(0, 1), ...
    zeros(0, 1), zeros(0, 1), zeros(0, 1), zeros(0, 1), ...
    zeros(0, 1), strings(0, 1), ...
    'VariableNames', { ...
        'system', 'eeg_chunk_index', 'edf_chunk_index', ...
        'start_anchor_event_index', 'end_anchor_event_index', ...
        'start_anchor_latency', 'end_anchor_latency', ...
        'start_anchor_time_sec', 'end_anchor_time_sec', 'reason'});

end

%%
function validate_system_inputs(eeg_input, edf_input)

assert(isstruct(eeg_input) && isscalar(eeg_input) && ...
    isstruct(edf_input) && isscalar(edf_input), ...
    'eeg_input and edf_input must be scalar structs.')
assert(all(isfield(eeg_input, {'event_table', 'Fs'})), ...
    'eeg_input must contain event_table and Fs fields.')
assert(all(isfield(edf_input, {'event_table', 'trigger_Fs'})), ...
    'edf_input must contain event_table and trigger_Fs fields.')
assert(istable(eeg_input.event_table) && istable(edf_input.event_table), ...
    'eeg_input.event_table and edf_input.event_table must be tables.')
assert(isnumeric(eeg_input.Fs) && isscalar(eeg_input.Fs) && ...
    isfinite(eeg_input.Fs) && eeg_input.Fs > 0 && ...
    isnumeric(edf_input.trigger_Fs) && isscalar(edf_input.trigger_Fs) && ...
    isfinite(edf_input.trigger_Fs) && edf_input.trigger_Fs > 0, ...
    'EEG Fs and EDF trigger_Fs must be positive finite scalars.')

end

%%
function validate_chunk_reports(eeg_chunk_report, edf_chunk_report)

assert(istable(eeg_chunk_report) && istable(edf_chunk_report), ...
    'Chunk reports must be tables.')
required_report_variables = [ ...
    "start_event_index", "end_event_index", "observed_trigger_count", ...
    "has_next_boundary", "estimated_cycle_count", "status", "reason"];
assert(all(ismember(required_report_variables, ...
    string(eeg_chunk_report.Properties.VariableNames))) && ...
    all(ismember(required_report_variables, ...
    string(edf_chunk_report.Properties.VariableNames))), ...
    'Chunk reports are missing variables required for trigger matching.')

end
