function [signalHeader_final, signalCell_final] = quantize_edf_data( ...
    signalHeader_all, signalCell_all)
%QUANTIZE_EDF_DATA Put clinical montage channels on one EDF voltage grid.
%   The physical range of E1, E2, M1, M2, and the eight grounded scalp
%   channels is changed to -1800 to 1800 uV. The preserved clinical E1,
%   E2, M1, and M2 data are quantized onto that new grid before the
%   quantized mastoids are added to the aligned scalp derivations.
%
%   The eight scalp signal cells are left unchanged here because
%   SUBSTITUTE_EEG_DATA overwrites them immediately afterward. All other
%   EDF signal headers and cells remain unchanged.

assert(isstruct(signalHeader_all) && iscell(signalCell_all), ...
    'quantize_edf_data:InvalidInputTypes', ...
    'EDF signal headers must be a struct array and signals a cell array.')
assert(numel(signalHeader_all) == numel(signalCell_all), ...
    'quantize_edf_data:SignalCountMismatch', ...
    'The EDF signal header and signal cell counts must match.')

shared_grid_channel_names = { ...
    'Fp1', 'Fp2', 'F3', 'F4', 'C3', 'C4', 'O1', 'O2', ...
    'E1', 'E2', 'M1', 'M2'};
quantized_channel_names = {'E1', 'E2', 'M1', 'M2'};
physical_min_uV = -1800;
physical_max_uV = 1800;

signal_labels = {signalHeader_all.signal_labels};
target_index = zeros(size(shared_grid_channel_names));
for channel_i = 1:numel(shared_grid_channel_names)
    channel_name = shared_grid_channel_names{channel_i};
    matching_index = find(strcmp(signal_labels, channel_name));
    if isempty(matching_index)
        error('quantize_edf_data:MissingEdfChannel', ...
            'Required EDF signal label not found: %s.', channel_name)
    elseif numel(matching_index) > 1
        error('quantize_edf_data:DuplicateEdfChannel', ...
            'EDF signal label occurs more than once: %s.', channel_name)
    end
    target_index(channel_i) = matching_index;
end

physical_dimension = strtrim( ...
    {signalHeader_all(target_index).physical_dimension});
assert(all(strcmp(physical_dimension, 'uV')), ...
    'quantize_edf_data:InvalidPhysicalDimension', ...
    'All shared-grid EDF channels must use uV as the physical dimension.')

digital_min = zeros(size(target_index));
digital_max = zeros(size(target_index));
for channel_i = 1:numel(target_index)
    edf_index = target_index(channel_i);
    channel_digital_min = signalHeader_all(edf_index).digital_min;
    channel_digital_max = signalHeader_all(edf_index).digital_max;
    valid_digital_limits = ...
        isnumeric(channel_digital_min) && ...
        isnumeric(channel_digital_max) && ...
        isreal(channel_digital_min) && ...
        isreal(channel_digital_max) && ...
        isscalar(channel_digital_min) && ...
        isscalar(channel_digital_max) && ...
        isfinite(channel_digital_min) && ...
        isfinite(channel_digital_max) && ...
        channel_digital_min == fix(channel_digital_min) && ...
        channel_digital_max == fix(channel_digital_max) && ...
        channel_digital_min >= double(intmin('int16')) && ...
        channel_digital_max <= double(intmax('int16')) && ...
        channel_digital_min < channel_digital_max;
    assert(valid_digital_limits, ...
        'quantize_edf_data:InvalidDigitalLimits', ...
        'Each shared-grid EDF channel must have valid int16 limits.')
    digital_min(channel_i) = double(channel_digital_min);
    digital_max(channel_i) = double(channel_digital_max);
end
assert(all(digital_min == digital_min(1)) && ...
    all(digital_max == digital_max(1)), ...
    'quantize_edf_data:InconsistentDigitalLimits', ...
    'All shared-grid EDF channels must use the same digital limits.')

signalHeader_final = signalHeader_all;
signalCell_final = signalCell_all;
for channel_i = 1:numel(target_index)
    edf_index = target_index(channel_i);
    signalHeader_final(edf_index).physical_min = physical_min_uV;
    signalHeader_final(edf_index).physical_max = physical_max_uV;
end

for channel_i = 1:numel(quantized_channel_names)
    edf_index = target_index(strcmp( ...
        shared_grid_channel_names, quantized_channel_names{channel_i}));
    signal_data = signalCell_all{edf_index};
    assert(isnumeric(signal_data) && isreal(signal_data) && ...
        isvector(signal_data) && all(isfinite(signal_data(:))), ...
        'quantize_edf_data:InvalidSignalData', ...
        'EDF signal %s must be a real numeric vector.', ...
        quantized_channel_names{channel_i})

    channel_digital_min = double( ...
        signalHeader_final(edf_index).digital_min);
    channel_digital_max = double( ...
        signalHeader_final(edf_index).digital_max);
    digital_data = ...
        (double(signal_data) - physical_min_uV) / ...
        (physical_max_uV - physical_min_uV);
    digital_data = round( ...
        digital_data * ...
        (channel_digital_max - channel_digital_min) + ...
        channel_digital_min);
    digital_data = min(max( ...
        digital_data, channel_digital_min), channel_digital_max);
    quantized_data = ...
        (digital_data - channel_digital_min) / ...
        (channel_digital_max - channel_digital_min);
    quantized_data = ...
        quantized_data * ...
        (physical_max_uV - physical_min_uV) + physical_min_uV;
    signalCell_final{edf_index} = reshape( ...
        quantized_data, size(signal_data));
end

end
