function resampled_eeg_segment_data = resample_eeg_segments( ...
    eeg_segment_data, matched_segments, edf_input, plot_sanity_check)
%RESAMPLE_EEG_SEGMENTS Resample HD-EEG segments onto the EDF scalp clock.
%   The EDF time axis is the reference. Each segment's effective HD-EEG
%   sampling rate is calculated from its EEG sample span and its duration
%   on the EDF clock. Each channel is converted to double, mean-centered,
%   and zero-phase high-pass filtered with an 80-dB stopband at 0.15 Hz
%   and a 0.30-Hz passband edge. A low-pass-scaled Kaiser-windowed sinc
%   resampler then applies the 120-Hz passband / 128-Hz stopband
%   antialiasing response while evaluating the signal directly on the
%   exact EDF scalp sample grid.
%   RESAMPLE_EEG_SEGMENTS(..., PLOT_SANITY_CHECK) creates a 5-by-2 trace
%   comparison using the middle 30 seconds of the first 10 minutes, plus a
%   Welch-spectrum figure for each matched segment. These plots include
%   only the 10 EDF scalp and mastoid channels, not auxiliary VEOGL data.

if nargin < 4
    plot_sanity_check = false;
end

edf_Fs = edf_input.Fs;
edf_trigger_Fs = edf_input.trigger_Fs;
aligned_eeg_channel_names = string( ...
    edf_input.aligned_eeg_channel_names);

assert(exist('buttord', 'file') == 2 && ...
    exist('butter', 'file') == 2 && ...
    exist('zp2sos', 'file') == 2 && ...
    exist('filtfilt', 'file') == 2 && ...
    exist('kaiserord', 'file') == 2 && ...
    exist('kaiser', 'file') == 2, ...
    'resample_eeg_segments:MissingSignalProcessingToolbox', ...
    ['The Signal Processing Toolbox must be on the MATLAB path before ' ...
    'resampling.'])

n_segments = height(matched_segments);
assert(numel(eeg_segment_data) == n_segments, ...
    'resample_eeg_segments:SegmentCountMismatch', ...
    'The EEG cell array must contain one entry per matched segment.')

scalp_samples_per_trigger_sample = edf_Fs / edf_trigger_Fs;
ratio_tolerance = 10 * eps(max(abs( ...
    scalp_samples_per_trigger_sample), 1));
assert(abs(scalp_samples_per_trigger_sample - ...
    round(scalp_samples_per_trigger_sample)) <= ratio_tolerance, ...
    'resample_eeg_segments:NonintegerEdfRateRatio', ...
    ['The EDF scalp sampling rate must be an integer multiple of the ' ...
    'EDF trigger sampling rate.'])

resampled_eeg_segment_data = cell(n_segments, 1);

for segment_i = 1:n_segments
    assert(size(eeg_segment_data{segment_i}, 1) == ...
        numel(aligned_eeg_channel_names), ...
        'resample_eeg_segments:ChannelCountMismatch', ...
        ['EEG segment %d must contain one row per aligned EEG channel ' ...
        'name.'], segment_i)

    eeg_sample_span = double( ...
        matched_segments.eeg_end_sample(segment_i) - ...
        matched_segments.eeg_start_sample(segment_i));
    assert(size(eeg_segment_data{segment_i}, 2) == eeg_sample_span + 1, ...
        'resample_eeg_segments:UnexpectedEegSegmentLength', ...
        'EEG segment %d does not match its reported sample bounds.', ...
        segment_i)

    edf_trigger_sample_span = double( ...
        matched_segments.edf_end_sample(segment_i) - ...
        matched_segments.edf_start_sample(segment_i));
    edf_duration_sec = edf_trigger_sample_span / edf_trigger_Fs;
    effective_hd_eeg_Fs = eeg_sample_span / edf_duration_sec;

    target_sample_span = edf_trigger_sample_span * ...
        scalp_samples_per_trigger_sample;
    target_span_tolerance = 10 * eps(max(abs(target_sample_span), 1));
    assert(abs(target_sample_span - round(target_sample_span)) <= ...
        target_span_tolerance, ...
        'resample_eeg_segments:NonintegerTargetSampleSpan', ...
        'EDF segment %d does not map to an integer scalp sample span.', ...
        segment_i)
    expected_sample_count = round(target_sample_span) + 1;

    % 1. Convert every channel to double before filtering and resampling.
    processed_eeg_segment = double(eeg_segment_data{segment_i});

    % 2. Mean-center each channel to remove its constant (DC) offset.
    processed_eeg_segment = processed_eeg_segment - ...
        mean(processed_eeg_segment, 2);

    % 3. Apply the 80-dB zero-phase high-pass (0.15-Hz stop, 0.30-Hz pass).
    processed_eeg_segment = apply_eeg_highpass_filter( ...
        processed_eeg_segment, effective_hd_eeg_Fs);

    % 4. Apply integrated anti-aliasing and sample on the exact EDF grid.
    resampled_segment = resample_with_antialiasing_kaiser_sinc( ...
        processed_eeg_segment, eeg_sample_span, ...
        round(target_sample_span), effective_hd_eeg_Fs, edf_Fs);

    assert(size(resampled_segment, 2) == expected_sample_count, ...
        'resample_eeg_segments:UnexpectedResampledLength', ...
        ['Resampled EEG segment %d contains %d samples; the matched EDF ' ...
        'scalp interval requires %d samples.'], ...
        segment_i, size(resampled_segment, 2), expected_sample_count)
    resampled_eeg_segment_data{segment_i} = resampled_segment;

    if plot_sanity_check
        output_time_sec = (0:(expected_sample_count - 1))' / edf_Fs;
        plot_context_sample_span = min( ...
            round(10 * 60 * edf_Fs), expected_sample_count - 1);
        trace_sample_span = min( ...
            round(30 * edf_Fs), plot_context_sample_span);
        first_output_plot_sample = floor( ...
            (plot_context_sample_span - trace_sample_span) / 2);
        last_output_plot_sample = ...
            first_output_plot_sample + trace_sample_span;
        trace_start_sec = first_output_plot_sample / edf_Fs;
        trace_end_sec = last_output_plot_sample / edf_Fs;
        first_input_plot_sample = max(0, floor( ...
            trace_start_sec * effective_hd_eeg_Fs));
        last_input_plot_sample = min(eeg_sample_span, ceil( ...
            trace_end_sec * effective_hd_eeg_Fs));
        % Apply the same Kaiser anti-aliasing response on the unchanged
        % input grid so the trace comparison isolates resampling effects.
        antialiased_eeg_segment = apply_antialiasing_filter( ...
            processed_eeg_segment, eeg_sample_span, ...
            first_input_plot_sample, last_input_plot_sample, ...
            effective_hd_eeg_Fs, edf_Fs);
        input_time_sec = ...
            (first_input_plot_sample:last_input_plot_sample)' / ...
            effective_hd_eeg_Fs;
        plot_resampling_sanity_checks( ...
            antialiased_eeg_segment, ...
            resampled_eeg_segment_data{segment_i}, ...
            input_time_sec, output_time_sec, ...
            trace_start_sec, trace_end_sec, ...
            aligned_eeg_channel_names, edf_Fs, segment_i)
    end
end

assert(numel(resampled_eeg_segment_data) == height(matched_segments), ...
    'Resampling did not return one HD-EEG cell per matched segment.')

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% END OF RESAMPLE_EEG_SEGMENTS (MAIN FUNCTION)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
end

%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% ADDITIONAL HELPER FUNCTIONS
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function resampled_data = resample_with_antialiasing_kaiser_sinc( ...
    data, input_sample_span, output_sample_span, ...
    effective_hd_eeg_Fs, edf_Fs)

[normalized_cutoff, kernel_offset, kernel_window] = ...
    design_antialiasing_kaiser_sinc(effective_hd_eeg_Fs, edf_Fs);
output_block_size = 4096;
resampled_data = zeros( ...
    size(data, 1), output_sample_span + 1, 'double');

for first_output_index = 0:output_block_size:output_sample_span
    output_index = (first_output_index:min( ...
        first_output_index + output_block_size - 1, ...
        output_sample_span))';
    source_position = output_index * ...
        double(input_sample_span) / double(output_sample_span);
    if output_index(1) == 0
        source_position(1) = 0;
    end
    if output_index(end) == output_sample_span
        source_position(end) = input_sample_span;
    end

    % Center on the nearest input sample, keeping every fractional delay
    % within one-half sample of the center of the fixed Kaiser window.
    source_center = round(source_position);
    fractional_position = source_position - source_center;
    distance_from_target = fractional_position - kernel_offset;
    % This is the antialiasing low-pass and fractional-delay interpolator
    % in one kernel. NORMALIZED_CUTOFF scales both the sinc argument and
    % its amplitude; omitting that scaling would instead interpolate the
    % full input bandwidth and would alias frequencies above 128 Hz.
    interpolation_weight = normalized_cutoff * ...
        sinc(normalized_cutoff * distance_from_target) .* ...
        kernel_window;
    interpolation_weight = interpolation_weight ./ ...
        sum(interpolation_weight, 2);

    source_index = source_center + kernel_offset;
    source_index = reflect_sample_index( ...
        source_index, input_sample_span) + 1;

    for channel_i = 1:size(data, 1)
        source_sample = reshape( ...
            data(channel_i, source_index(:)), size(source_index));
        resampled_data(channel_i, output_index + 1) = ...
            sum(source_sample .* interpolation_weight, 2)';
    end
end

end

%%
function filtered_data = apply_antialiasing_filter( ...
    data, input_sample_span, first_output_sample, last_output_sample, ...
    effective_hd_eeg_Fs, edf_Fs)

[normalized_cutoff, kernel_offset, kernel_window] = ...
    design_antialiasing_kaiser_sinc(effective_hd_eeg_Fs, edf_Fs);
filter_weight = normalized_cutoff * ...
    sinc(-normalized_cutoff * kernel_offset) .* kernel_window;
filter_weight = filter_weight / sum(filter_weight);

% Compute only the input-grid samples shown in the trace plot. Reflecting
% against the full segment span makes these samples identical to evaluating
% the resampling kernel at the corresponding integer input positions.
padded_sample_index = (first_output_sample + kernel_offset(1)): ...
    (last_output_sample + kernel_offset(end));
padded_sample_index = reflect_sample_index( ...
    padded_sample_index, input_sample_span) + 1;
filtered_data = conv2( ...
    data(:, padded_sample_index), fliplr(filter_weight), 'valid');

end

%%
function [normalized_cutoff, kernel_offset, kernel_window] = ...
    design_antialiasing_kaiser_sinc(effective_hd_eeg_Fs, edf_Fs)

passband_Hz = 120;
stopband_Hz = edf_Fs / 2;
attenuation_dB = 80;
deviation = 10 ^ (-attenuation_dB / 20);

assert(passband_Hz < stopband_Hz && ...
    stopband_Hz < effective_hd_eeg_Fs / 2, ...
    'resample_eeg_segments:InvalidAntialiasingBand', ...
    ['The antialiasing passband must end below the EDF Nyquist ' ...
    'frequency, which must be below the effective HD-EEG Nyquist.'])

% KAISERORD sets the transition width, ripple, and Kaiser beta. Making the
% order even gives an integer half-length for the symmetric kernel. At
% approximately 500 Hz this produces a 315-tap kernel centered
% at 124 Hz between the requested 120-Hz and 128-Hz band edges.
[filter_order, normalized_cutoff, kaiser_beta] = kaiserord( ...
    [passband_Hz stopband_Hz], [1 0], ...
    [deviation deviation], effective_hd_eeg_Fs);
filter_order = filter_order + mod(filter_order, 2);
half_kernel_length = filter_order / 2;
kernel_offset = -half_kernel_length:half_kernel_length;
kernel_window = kaiser(filter_order + 1, kaiser_beta)';

end

%%
function reflected_index = reflect_sample_index( ...
    zero_based_index, sample_span)

reflection_period = 2 * sample_span;
reflected_index = mod(zero_based_index, reflection_period);
is_reflected = reflected_index > sample_span;
reflected_index(is_reflected) = ...
    reflection_period - reflected_index(is_reflected);

end

%%
function plot_resampling_sanity_checks( ...
    antialiased_input_segment, resampled_segment, ...
    input_time_sec, resampled_time_sec, ...
    trace_start_sec, trace_end_sec, ...
    aligned_eeg_channel_names, edf_Fs, segment_i)

plot_channel_names = [ ...
    "Fp1", "Fp2", "F3", "F4", "C3", ...
    "C4", "O1", "O2", "M1", "M2"];
[has_channel, channel_index] = ismember( ...
    lower(plot_channel_names), lower(aligned_eeg_channel_names));
if ~all(has_channel)
    missing_names = strjoin(plot_channel_names(~has_channel), ', ');
    error('resample_eeg_segments:MissingPlotChannel', ...
        'Required sanity-plot channel(s) not found: %s.', missing_names)
end

plot_time_trace_comparison( ...
    antialiased_input_segment(channel_index, :), ...
    resampled_segment(channel_index, :), ...
    input_time_sec, resampled_time_sec, ...
    trace_start_sec, trace_end_sec, ...
    plot_channel_names, segment_i)
plot_welch_spectra( ...
    resampled_segment(channel_index, :), ...
    plot_channel_names, edf_Fs, segment_i)

end

%%
function plot_time_trace_comparison( ...
    antialiased_input_segment, resampled_segment, ...
    input_time_sec, resampled_time_sec, ...
    trace_start_sec, trace_end_sec, channel_names, segment_i)

use_input = input_time_sec >= trace_start_sec & ...
    input_time_sec <= trace_end_sec;
use_resampled = resampled_time_sec >= trace_start_sec & ...
    resampled_time_sec <= trace_end_sec;
input_color = [0, 0.4470, 0.7410];
resampled_color = [0.8500, 0.3250, 0.0980];

figure_handle = figure( ...
    'Name', sprintf('Resampling trace comparison - segment %d', segment_i), ...
    'Tag', 'resample_time_trace_comparison', ...
    'Color', 'w');
axes_handles = gobjects(numel(channel_names), 1);

for channel_i = 1:numel(channel_names)
    axes_handles(channel_i) = subplot( ...
        5, 2, channel_i, 'Parent', figure_handle);
    plot(axes_handles(channel_i), ...
        input_time_sec(use_input), ...
        antialiased_input_segment(channel_i, use_input), ...
        'Color', input_color, 'LineWidth', 1.25, ...
        'DisplayName', ...
        'Mean-centered + high-pass + anti-alias-filtered input')
    hold(axes_handles(channel_i), 'on')
    plot(axes_handles(channel_i), ...
        resampled_time_sec(use_resampled), ...
        resampled_segment(channel_i, use_resampled), ...
        'Color', resampled_color, 'LineWidth', 0.75, ...
        'DisplayName', 'Resampled')
    hold(axes_handles(channel_i), 'off')
    title(axes_handles(channel_i), channel_names(channel_i))
    set(axes_handles(channel_i), 'FontSize', 10)
    grid(axes_handles(channel_i), 'on')

    if mod(channel_i, 2) == 1
        ylabel(axes_handles(channel_i), 'Amplitude')
    end
    if channel_i >= 9
        xlabel(axes_handles(channel_i), 'EDF time (sec)')
    end
end

legend(axes_handles(1), 'show', 'Location', 'best')
linkaxes(axes_handles, 'x')
xlim(axes_handles(1), [trace_start_sec, trace_end_sec])
sgtitle(figure_handle, sprintf( ...
    ['Anti-alias-filtered input and resampled HD-EEG: segment %d, ' ...
    '%.1f-%.1f sec'], ...
    segment_i, trace_start_sec, trace_end_sec), 'FontSize', 16)

end

%%
function plot_welch_spectra( ...
    resampled_segment, channel_names, edf_Fs, segment_i)

window_samples = min(round(4 * edf_Fs), size(resampled_segment, 2));
welch_window = hamming(window_samples, 'periodic');
overlap_samples = floor(window_samples / 2);
nfft = max(256, 2 ^ nextpow2(window_samples));
line_colors = lines(numel(channel_names));

figure_handle = figure( ...
    'Name', sprintf('Resampled Welch spectra - segment %d', segment_i), ...
    'Tag', 'resample_welch_spectra', ...
    'Color', 'w');
ax = axes('Parent', figure_handle, 'Tag', 'resample_welch_spectrum_axes');
hold(ax, 'on')

for channel_i = 1:numel(channel_names)
    [power_density, frequency] = pwelch( ...
        double(resampled_segment(channel_i, :)), ...
        welch_window, overlap_samples, nfft, edf_Fs);
    plot(ax, frequency, ...
        10 * log10(max(power_density, realmin('double'))), ...
        'Color', line_colors(channel_i, :), ...
        'LineWidth', 1, ...
        'DisplayName', channel_names(channel_i))
end

hold(ax, 'off')
set(ax, 'FontSize', 14)
xlim(ax, [0, edf_Fs / 2])
xlabel(ax, 'Frequency (Hz)')
ylabel(ax, 'Power/frequency (dB/Hz)')
title(ax, sprintf( ...
    'Welch spectra of resampled HD-EEG: segment %d', segment_i), ...
    'FontSize', 18)
legend(ax, 'show', 'Location', 'best', 'NumColumns', 2)
grid(ax, 'on')

end
