function figure_handle = sanity_check_eog( ...
    aligned_eeg_data, aligned_eeg_channel_names, ...
    signalHeader_all, signalCell_all, edf_Fs)
%SANITY_CHECK_EOG Compare aligned HD-EEG and clinical EDF EOG signals.
%   VEOGL is referenced to the HD-EEG M2 analog (RD6). The three clinical EDF
%   EOG traces are reconstructed from the original direct E1, E2, M1, and M2
%   rows, without using stored montage rows or changing SIGNALCELL_ALL.

assert(iscell(aligned_eeg_channel_names) && ...
    all(cellfun(@ischar, aligned_eeg_channel_names)), ...
    'sanity_check_eog:InvalidChannelNames', ...
    'Aligned EEG channel names must be a cell array of text.')
aligned_eeg_channel_names = aligned_eeg_channel_names(:).';
assert(size(aligned_eeg_data, 1) == ...
    numel(aligned_eeg_channel_names), ...
    'sanity_check_eog:ChannelCountMismatch', ...
    ['Each row of the aligned EEG data must correspond to one aligned ' ...
     'EEG channel name.'])
assert(numel(unique(aligned_eeg_channel_names)) == ...
    numel(aligned_eeg_channel_names), ...
    'sanity_check_eog:DuplicateAlignedChannel', ...
    'Aligned EEG channel names must be unique.')
assert(isscalar(edf_Fs) && isfinite(edf_Fs) && edf_Fs > 0, ...
    'sanity_check_eog:InvalidSamplingRate', ...
    'The EDF sampling rate must be a positive finite scalar.')
assert(isstruct(signalHeader_all) && iscell(signalCell_all), ...
    'sanity_check_eog:InvalidEdfInputs', ...
    'The EDF signal headers must be a struct array and signals a cell array.')
assert(numel(signalHeader_all) == numel(signalCell_all), ...
    'sanity_check_eog:SignalCountMismatch', ...
    'The EDF signal header and signal cell counts must match.')

hd_source_names = {'VEOGL', 'M2'};
[has_hd_source, hd_source_index] = ismember( ...
    hd_source_names, aligned_eeg_channel_names);
if ~all(has_hd_source)
    error('sanity_check_eog:MissingAlignedChannel', ...
        'Required aligned EEG channel not found: %s.', ...
        strjoin(hd_source_names(~has_hd_source), ', '))
end

direct_channel_names = {'E1', 'E2', 'M1', 'M2'};
signal_labels = {signalHeader_all.signal_labels};
direct_channel_index = zeros(size(direct_channel_names));

for channel_i = 1:numel(direct_channel_names)
    matching_index = find(strcmp( ...
        signal_labels, direct_channel_names{channel_i}));
    if isempty(matching_index)
        error('sanity_check_eog:MissingDirectChannel', ...
            'Required direct EDF signal not found: %s.', ...
            direct_channel_names{channel_i})
    elseif numel(matching_index) > 1
        error('sanity_check_eog:DuplicateDirectChannel', ...
            'Direct EDF signal occurs more than once: %s.', ...
            direct_channel_names{channel_i})
    end
    direct_channel_index(channel_i) = matching_index;
end

n_samples = size(aligned_eeg_data, 2);
assert(n_samples > 1, ...
    'sanity_check_eog:InsufficientSamples', ...
    'The aligned EOG signals must contain at least two samples.')
direct_data = zeros(numel(direct_channel_names), n_samples);
samples_in_record = zeros(size(direct_channel_names));
for channel_i = 1:numel(direct_channel_index)
    direct_signal = signalCell_all{direct_channel_index(channel_i)};
    assert(isnumeric(direct_signal) && isreal(direct_signal) && ...
        isvector(direct_signal) && all(isfinite(direct_signal(:))), ...
        'sanity_check_eog:InvalidDirectSignal', ...
        'Direct EDF signal %s must be a finite real numeric vector.', ...
        direct_channel_names{channel_i})
    assert(numel(direct_signal) == n_samples, ...
        'sanity_check_eog:SampleCountMismatch', ...
        ['Direct EDF signal %s must have the same sample ' ...
         'count as the zero-padded HD-EEG data.'], ...
        direct_channel_names{channel_i})
    direct_data(channel_i, :) = double(direct_signal(:).');

    channel_samples_in_record = ...
        signalHeader_all(direct_channel_index(channel_i)).samples_in_record;
    assert(isnumeric(channel_samples_in_record) && ...
        isreal(channel_samples_in_record) && ...
        isscalar(channel_samples_in_record) && ...
        isfinite(channel_samples_in_record) && ...
        channel_samples_in_record > 0, ...
        'sanity_check_eog:InvalidDirectSamplingRate', ...
        ['Direct EDF signal %s must have a positive finite ' ...
         'samples_in_record value.'], direct_channel_names{channel_i})
    samples_in_record(channel_i) = double(channel_samples_in_record);
end
assert(all(samples_in_record == samples_in_record(1)), ...
    'sanity_check_eog:DirectSamplingRateMismatch', ...
    'Direct EDF signals E1, E2, M1, and M2 must share a sampling rate.')

hd_source_data = double(aligned_eeg_data(hd_source_index, :));
assert(all(isfinite(hd_source_data(:))), ...
    'sanity_check_eog:InvalidAlignedSignal', ...
    'Aligned VEOGL and M2 signals must contain only finite values.')
hd_veogl_m2 = hd_source_data(1, :) - hd_source_data(2, :);
e1_data = direct_data(1, :);
e2_data = direct_data(2, :);
m1_data = direct_data(3, :);
m2_data = direct_data(4, :);
plot_data = { ...
    hd_veogl_m2, ...
    e2_data - m1_data, ...
    e1_data - m2_data, ...
    e2_data - m2_data};
plot_titles = { ...
    'HD-EEG VEOGL:M2 (VEOGL - RD6)', ...
    'Clinical EDF E2:M1 (E2 - M1)', ...
    'Clinical EDF E1:M2 (E1 - M2)', ...
    'Clinical EDF E2:M2 (E2 - M2)'};
display_names = { ...
    'HD-EEG VEOGL:M2', ...
    'Clinical EDF E2:M1', ...
    'Clinical EDF E1:M2', ...
    'Clinical EDF E2:M2'};
time_hours = (0:(n_samples - 1)) / (edf_Fs * 3600);

figure_handle = figure('Color', 'w');
axes_handles = gobjects(4, 1);

for channel_i = 1:4
    axes_handles(channel_i) = subplot( ...
        4, 1, channel_i, 'Parent', figure_handle);
    plot(axes_handles(channel_i), time_hours, ...
        plot_data{channel_i}(:).', ...
        'LineWidth', 0.75, ...
        'DisplayName', display_names{channel_i})
    axes_handles(channel_i).InteractionOptions.DatatipsSupported = 'off';
    title(axes_handles(channel_i), plot_titles{channel_i})
    ylabel(axes_handles(channel_i), 'Voltage (\muV)')
    grid(axes_handles(channel_i), 'on')
end

xlabel(axes_handles(end), 'Time on EDF clock (hours)')
linkaxes(axes_handles, 'xy')
ylim(axes_handles(1), [-1500, 1500])
xlim(axes_handles(1), [time_hours(1), time_hours(end)])
sgtitle(figure_handle, ...
    'HD-EEG and clinical EOG alignment sanity check', ...
    'FontSize', 16)
set(axes_handles, 'Tag', 'sanity_check_eog_axes')

end
