function figure_handle = sanity_check_EOG( ...
    aligned_eeg_data, aligned_eeg_channel_names, ...
    signalHeader_final, signalCell_final, edf_Fs)
%SANITY_CHECK_EOG Compare aligned HD-EEG and clinical EOG signals.
%   VEOGL is referenced to the HD-EEG M2 analog (RD6). The resulting
%   zero-padded signal is plotted with the three requested clinical EDF EOG
%   signals without changing SIGNALCELL_FINAL.

assert(iscell(aligned_eeg_channel_names) && ...
    all(cellfun(@ischar, aligned_eeg_channel_names)), ...
    'sanity_check_EOG:InvalidChannelNames', ...
    'Aligned EEG channel names must be a cell array of text.')
aligned_eeg_channel_names = aligned_eeg_channel_names(:).';
assert(size(aligned_eeg_data, 1) == ...
    numel(aligned_eeg_channel_names), ...
    'sanity_check_EOG:ChannelCountMismatch', ...
    ['Each row of the aligned EEG data must correspond to one aligned ' ...
     'EEG channel name.'])
assert(numel(unique(aligned_eeg_channel_names)) == ...
    numel(aligned_eeg_channel_names), ...
    'sanity_check_EOG:DuplicateAlignedChannel', ...
    'Aligned EEG channel names must be unique.')
assert(isscalar(edf_Fs) && isfinite(edf_Fs) && edf_Fs > 0, ...
    'sanity_check_EOG:InvalidSamplingRate', ...
    'The EDF sampling rate must be a positive finite scalar.')
assert(numel(signalHeader_final) == numel(signalCell_final), ...
    'sanity_check_EOG:SignalCountMismatch', ...
    'The EDF signal header and signal cell counts must match.')

hd_source_names = {'VEOGL', 'M2'};
[has_hd_source, hd_source_index] = ismember( ...
    hd_source_names, aligned_eeg_channel_names);
if ~all(has_hd_source)
    error('sanity_check_EOG:MissingAlignedChannel', ...
        'Required aligned EEG channel not found: %s.', ...
        strjoin(hd_source_names(~has_hd_source), ', '))
end

clinical_channel_names = {'E2:M1', 'E1:M2', 'E2:M2'};
signal_labels = {signalHeader_final.signal_labels};
clinical_channel_index = zeros(size(clinical_channel_names));

for channel_i = 1:numel(clinical_channel_names)
    matching_index = find(strcmp( ...
        signal_labels, clinical_channel_names{channel_i}));
    if isempty(matching_index)
        error('sanity_check_EOG:MissingClinicalChannel', ...
            'Required clinical EDF signal not found: %s.', ...
            clinical_channel_names{channel_i})
    elseif numel(matching_index) > 1
        error('sanity_check_EOG:DuplicateClinicalChannel', ...
            'Clinical EDF signal occurs more than once: %s.', ...
            clinical_channel_names{channel_i})
    end
    clinical_channel_index(channel_i) = matching_index;
end

n_samples = size(aligned_eeg_data, 2);
assert(n_samples > 1, ...
    'sanity_check_EOG:InsufficientSamples', ...
    'The aligned EOG signals must contain at least two samples.')
for channel_i = 1:numel(clinical_channel_index)
    clinical_signal = signalCell_final{ ...
        clinical_channel_index(channel_i)};
    assert(isvector(clinical_signal) && ...
        numel(clinical_signal) == n_samples, ...
        'sanity_check_EOG:SampleCountMismatch', ...
        ['Clinical EDF signal %s must be a vector with the same sample ' ...
         'count as the zero-padded HD-EEG data.'], ...
        clinical_channel_names{channel_i})
end

hd_veogl_m2 = ...
    aligned_eeg_data(hd_source_index(1), :) - ...
    aligned_eeg_data(hd_source_index(2), :);
plot_data = cell(1, 4);
plot_data{1} = hd_veogl_m2;
for channel_i = 1:numel(clinical_channel_index)
    plot_data{channel_i + 1} = signalCell_final{ ...
        clinical_channel_index(channel_i)};
end
plot_titles = { ...
    'HD-EEG VEOGL:M2 (VEOGL - RD6)', ...
    'Clinical E2:M1', ...
    'Clinical E1:M2', ...
    'Clinical E2:M2'};
display_names = { ...
    'HD-EEG VEOGL:M2', ...
    'Clinical E2:M1', ...
    'Clinical E1:M2', ...
    'Clinical E2:M2'};
time_hours = (0:(n_samples - 1)) / (edf_Fs * 3600);

figure_handle = figure( ...
    'Name', 'EOG alignment sanity check', ...
    'Tag', 'sanity_check_EOG', ...
    'Color', 'w');
axes_handles = gobjects(4, 1);

for channel_i = 1:4
    axes_handles(channel_i) = subplot( ...
        4, 1, channel_i, 'Parent', figure_handle);
    plot(axes_handles(channel_i), time_hours, ...
        plot_data{channel_i}(:).', ...
        'LineWidth', 0.75, ...
        'DisplayName', display_names{channel_i})
    axes_handles(channel_i).InteractionOptions.DatatipsSupported = 'off';
    title(axes_handles(channel_i), plot_titles{channel_i})
    ylabel(axes_handles(channel_i), 'Voltage (\muV)')
    grid(axes_handles(channel_i), 'on')
end

xlabel(axes_handles(end), 'Time on EDF clock (hours)')
linkaxes(axes_handles, 'xy')
ylim(axes_handles(1), [-1500, 1500])
xlim(axes_handles(1), [time_hours(1), time_hours(end)])
sgtitle(figure_handle, ...
    'HD-EEG and clinical EOG alignment sanity check', ...
    'FontSize', 16)
set(axes_handles, 'Tag', 'sanity_check_EOG_axes')

end
