function [signalCell_final, figure_handle, percent_outside_bounds] = ...
    substitute_eeg_data( ...
    aligned_eeg_data, aligned_eeg_channel_names, ...
    edf_eeg_channel_names, signalHeader_all, signalCell_all, ...
    matched_sample_mask, plot_sanity_check)
%SUBSTITUTE_EEG_DATA Prepare final direct EDF channels from aligned HD-EEG.
%   The clinical pathway is selected internally from direct M1 and M2 samples
%   within MATCHED_SAMPLE_MASK by FAULTY_CLINICAL_DETECTION.
%
%   In the normal clinical pathway, each of the eight PSG EEG channels is
%   replaced with aligned HD active - aligned HD mastoid + the corresponding
%   clinical mastoid. Clinical E1, E2, M1, and M2 remain unchanged.
%
%   In the faulty clinical pathway, the eight PSG EEG channels are replaced
%   with their aligned HD active signals, and the direct clinical channels
%   are replaced as E1 <- VEOGL, E2 <- aligned Fp2 (HD source R1),
%   M1 <- aligned M1 (LD6), and M2 <- aligned M2 (RD6).
%
%   The unchanged EDF headers are validated as one compatible direct-channel
%   grid. Bounds percentages use only MATCHED_SAMPLE_MASK. The function
%   errors when any channel exceeds its bounds in more than 1% of matched
%   samples; otherwise, the optional sanity figure plots every sample in all
%   12 final output EDF channels. SIGNALCELL_ALL remains unchanged; the
%   substituted channel collection is returned as SIGNALCELL_FINAL.

if nargin < 7
    plot_sanity_check = true;
end
figure_handle = gobjects(0);

assert(isstruct(signalHeader_all) && iscell(signalCell_all), ...
    'substitute_eeg_data:InvalidInputTypes', ...
    'EDF signal headers must be a struct array and signals a cell array.')
assert(numel(signalHeader_all) == numel(signalCell_all), ...
    'substitute_eeg_data:SignalCountMismatch', ...
    'The EDF signal header and signal cell counts must match.')
assert(iscell(edf_eeg_channel_names) && ...
    all(cellfun(@ischar, edf_eeg_channel_names)), ...
    'substitute_eeg_data:InvalidChannelNames', ...
    'EDF EEG channel names must be provided as a cell array of text.')
assert(iscell(aligned_eeg_channel_names) && ...
    all(cellfun(@ischar, aligned_eeg_channel_names)), ...
    'substitute_eeg_data:InvalidAlignedChannelNames', ...
    'Aligned EEG channel names must be provided as a cell array of text.')
assert(isnumeric(aligned_eeg_data) && isreal(aligned_eeg_data), ...
    'substitute_eeg_data:InvalidAlignedData', ...
    'Aligned EEG data must be a real numeric array.')
assert(islogical(matched_sample_mask) && isvector(matched_sample_mask), ...
    'substitute_eeg_data:InvalidMatchedMask', ...
    'The matched-sample mask must be a logical vector.')
assert(islogical(plot_sanity_check) && isscalar(plot_sanity_check), ...
    'substitute_eeg_data:InvalidPlotFlag', ...
    'The sanity-check plot flag must be a logical scalar.')

edf_eeg_channel_names = edf_eeg_channel_names(:).';
aligned_eeg_channel_names = aligned_eeg_channel_names(:).';
matched_sample_mask = matched_sample_mask(:).';
assert(size(aligned_eeg_data, 1) == numel(aligned_eeg_channel_names), ...
    'substitute_eeg_data:ChannelCountMismatch', ...
    ['Each row of the aligned EEG data must correspond to one name in ' ...
    'aligned_eeg_channel_names.'])
assert(size(aligned_eeg_data, 2) == numel(matched_sample_mask), ...
    'substitute_eeg_data:MatchedMaskLengthMismatch', ...
    ['The matched-sample mask must have the same length as the aligned ' ...
    'EEG data.'])
assert(any(matched_sample_mask), ...
    'substitute_eeg_data:EmptyMatchedMask', ...
    'The matched-sample mask must contain at least one matched sample.')
assert(numel(unique(edf_eeg_channel_names)) == ...
    numel(edf_eeg_channel_names), ...
    'substitute_eeg_data:DuplicateEegChannel', ...
    'EDF EEG channel names must be unique.')
assert(numel(unique(aligned_eeg_channel_names)) == ...
    numel(aligned_eeg_channel_names), ...
    'substitute_eeg_data:DuplicateAlignedEegChannel', ...
    'Aligned EEG channel names must be unique.')

psg_eeg_channel_names = { ...
    'Fp1', 'Fp2', 'F3', 'F4', 'C3', 'C4', 'O1', 'O2'};
mastoid_channel_names = { ...
    'M2', 'M1', 'M2', 'M1', 'M2', 'M1', 'M2', 'M1'};
replacement_target_names = {'M1', 'M2', 'E1', 'E2'};
direct_channel_names = [psg_eeg_channel_names, replacement_target_names];

[has_psg_eeg_channel, ~] = ismember( ...
    psg_eeg_channel_names, edf_eeg_channel_names);
assert(numel(edf_eeg_channel_names) == numel(psg_eeg_channel_names) && ...
    all(has_psg_eeg_channel), ...
    'substitute_eeg_data:InvalidEdfEegChannels', ...
    ['EDF EEG channel names must contain exactly Fp1, Fp2, F3, F4, ' ...
    'C3, C4, O1, and O2.'])

% The same 11 aligned rows support both clinical pathways. If the clinical
% signals are faulty, E1 reuses VEOGL and E2 reuses Fp2 (HD source R1).
required_aligned_names = [ ...
    psg_eeg_channel_names, {'M1', 'M2', 'VEOGL'}];
[has_aligned_source, aligned_source_index] = ismember( ...
    required_aligned_names, aligned_eeg_channel_names);
if ~all(has_aligned_source)
    error('substitute_eeg_data:MissingEegChannel', ...
        'Required aligned EEG source channel(s) not found: %s.', ...
        strjoin(required_aligned_names(~has_aligned_source), ', '))
end

signal_labels = {signalHeader_all.signal_labels};
direct_signal_index = resolve_unique_edf_channels( ...
    signal_labels, direct_channel_names);
validate_direct_channel_headers( ...
    signalHeader_all, direct_signal_index, direct_channel_names)

n_samples = numel(matched_sample_mask);
for channel_i = 1:numel(direct_channel_names)
    signal_index = direct_signal_index(channel_i);
    signal_data = signalCell_all{signal_index};
    assert(isnumeric(signal_data) && isreal(signal_data) && ...
        isvector(signal_data) && numel(signal_data) == n_samples, ...
        'substitute_eeg_data:SampleCountMismatch', ...
        ['EDF signal %s must be a real numeric vector with the same ' ...
        'sample count as the aligned EEG data.'], ...
        direct_channel_names{channel_i})
end

clinical_system_faulty = faulty_clinical_detection( ...
    signalHeader_all, signalCell_all, matched_sample_mask);

aligned_psg_eeg_index = aligned_source_index( ...
    1:numel(psg_eeg_channel_names));
aligned_m1_index = aligned_source_index(strcmp(required_aligned_names, 'M1'));
aligned_m2_index = aligned_source_index(strcmp(required_aligned_names, 'M2'));
aligned_veogl_index = aligned_source_index( ...
    strcmp(required_aligned_names, 'VEOGL'));
aligned_mastoid_index = zeros(size(mastoid_channel_names));
aligned_mastoid_index(strcmp(mastoid_channel_names, 'M1')) = ...
    aligned_m1_index;
aligned_mastoid_index(strcmp(mastoid_channel_names, 'M2')) = ...
    aligned_m2_index;
signalCell_final = signalCell_all;

if clinical_system_faulty
    for channel_i = 1:numel(psg_eeg_channel_names)
        edf_index = direct_signal_index(channel_i);
        signalCell_final{edf_index} = reshape( ...
            aligned_eeg_data(aligned_psg_eeg_index(channel_i), :), ...
            size(signalCell_final{edf_index}));
    end

    replacement_aligned_index = [ ...
        aligned_m1_index, aligned_m2_index, ...
        aligned_veogl_index, aligned_psg_eeg_index(2)];
    for channel_i = 1:numel(replacement_target_names)
        edf_index = direct_signal_index(strcmp( ...
            direct_channel_names, replacement_target_names{channel_i}));
        signalCell_final{edf_index} = reshape( ...
            aligned_eeg_data(replacement_aligned_index(channel_i), :), ...
            size(signalCell_final{edf_index}));
    end
else
    for channel_i = 1:numel(psg_eeg_channel_names)
        clinical_mastoid_index = direct_signal_index(strcmp( ...
            direct_channel_names, mastoid_channel_names{channel_i}));
        clinical_mastoid_data = reshape( ...
            signalCell_all{clinical_mastoid_index}, 1, []);
        substituted_data = ...
            aligned_eeg_data(aligned_psg_eeg_index(channel_i), :) - ...
            aligned_eeg_data(aligned_mastoid_index(channel_i), :) + ...
            clinical_mastoid_data;
        edf_index = direct_signal_index(channel_i);
        signalCell_final{edf_index} = reshape( ...
            substituted_data, size(signalCell_final{edf_index}));
    end
end

physical_min_uV = double( ...
    signalHeader_all(direct_signal_index(1)).physical_min);
physical_max_uV = double( ...
    signalHeader_all(direct_signal_index(1)).physical_max);
percent_outside_bounds = zeros(numel(direct_channel_names), 1);
for channel_i = 1:numel(direct_channel_names)
    channel_data = double(reshape( ...
        signalCell_final{direct_signal_index(channel_i)}, 1, []));
    assert(all(isfinite(channel_data)), ...
        'substitute_eeg_data:NonfiniteSignalData', ...
        'Final EDF signal %s contains NaN or Inf.', ...
        direct_channel_names{channel_i})
    matched_data = channel_data(matched_sample_mask);
    percent_outside_bounds(channel_i) = 100 * nnz( ...
        matched_data < physical_min_uV | ...
        matched_data > physical_max_uV) / numel(matched_data);
end

output_derivation = build_output_derivations(clinical_system_faulty);
matched_sample_count = nnz(matched_sample_mask);
matched_coverage_percent = 100 * matched_sample_count / n_samples;
bounds_report = table( ...
    string(direct_channel_names(:)), ...
    output_derivation, ...
    repmat(physical_min_uV, numel(direct_channel_names), 1), ...
    repmat(physical_max_uV, numel(direct_channel_names), 1), ...
    round(percent_outside_bounds, 3), ...
    'VariableNames', { ...
    'EDFChannel', 'OutputDerivation', ...
    'PhysicalMin (uV)', 'PhysicalMax (uV)', ...
    'PercentOutsideBoundsWithinMatchedSamples (%)'});
fprintf(['\nFinal output EDF channel bounds report ' ...
    '(matched samples only: %d/%d, %.3f%% coverage)\n'], ...
    matched_sample_count, n_samples, matched_coverage_percent)
disp(bounds_report, false)

outside_bounds_index = find(percent_outside_bounds > 1);
if ~isempty(outside_bounds_index)
    outside_bounds_details = arrayfun( ...
        @(channel_i) sprintf('%s=%.6f%%', ...
        direct_channel_names{channel_i}, ...
        percent_outside_bounds(channel_i)), ...
        outside_bounds_index, 'UniformOutput', false);
    error('substitute_eeg_data:OutputOutsidePhysicalBounds', ...
        ['Final output EDF channel(s) exceeded their physical bounds in ' ...
        'more than 1%% of matched samples: %s.'], ...
        strjoin(outside_bounds_details, ', '))
end

if plot_sanity_check
    figure_handle = plot_substitution_sanity_check( ...
        signalCell_final(direct_signal_index), direct_channel_names, ...
        physical_min_uV, physical_max_uV);
end

end


function signal_index = resolve_unique_edf_channels( ...
    signal_labels, required_channel_names)

signal_index = zeros(size(required_channel_names));
for channel_i = 1:numel(required_channel_names)
    matching_index = find(strcmp( ...
        signal_labels, required_channel_names{channel_i}));
    if isempty(matching_index)
        error('substitute_eeg_data:MissingEdfChannel', ...
            'Required EDF signal label not found: %s.', ...
            required_channel_names{channel_i})
    elseif numel(matching_index) > 1
        error('substitute_eeg_data:DuplicateEdfChannel', ...
            'EDF signal label occurs more than once: %s.', ...
            required_channel_names{channel_i})
    end
    signal_index(channel_i) = matching_index;
end

end


function validate_direct_channel_headers( ...
    signal_headers, signal_index, channel_names)

physical_dimension = strtrim( ...
    {signal_headers(signal_index).physical_dimension});
assert(all(strcmp(physical_dimension, 'uV')), ...
    'substitute_eeg_data:InvalidPhysicalDimension', ...
    'All direct EDF channels must use uV as the physical dimension.')

samples_in_record = double( ...
    [signal_headers(signal_index).samples_in_record]);
assert(all(isfinite(samples_in_record)) && ...
    all(samples_in_record > 0) && ...
    all(samples_in_record == fix(samples_in_record)) && ...
    all(samples_in_record == samples_in_record(1)), ...
    'substitute_eeg_data:InconsistentSamplingRates', ...
    ['All direct EDF channels must use the same positive integer ' ...
    'samples-per-record value.'])

physical_min = zeros(size(signal_index));
physical_max = zeros(size(signal_index));
digital_min = zeros(size(signal_index));
digital_max = zeros(size(signal_index));
for channel_i = 1:numel(signal_index)
    header = signal_headers(signal_index(channel_i));
    physical_min(channel_i) = validate_physical_limit( ...
        header.physical_min, channel_names{channel_i}, 'minimum');
    physical_max(channel_i) = validate_physical_limit( ...
        header.physical_max, channel_names{channel_i}, 'maximum');
    assert(physical_min(channel_i) < physical_max(channel_i), ...
        'substitute_eeg_data:InvalidPhysicalLimits', ...
        'EDF signal %s must have increasing physical limits.', ...
        channel_names{channel_i})
    [digital_min(channel_i), digital_max(channel_i)] = ...
        validate_digital_limits(header, channel_names{channel_i});
end

assert(all(physical_min == physical_min(1)) && ...
    all(physical_max == physical_max(1)), ...
    'substitute_eeg_data:InconsistentPhysicalLimits', ...
    'All direct EDF channels must use the same physical limits.')
assert(all(digital_min == digital_min(1)) && ...
    all(digital_max == digital_max(1)), ...
    'substitute_eeg_data:InconsistentDigitalLimits', ...
    'All direct EDF channels must use the same digital limits.')

end


function value = validate_physical_limit(value, channel_name, limit_name)

assert(isnumeric(value) && isreal(value) && isscalar(value) && ...
    isfinite(value), ...
    'substitute_eeg_data:InvalidPhysicalLimits', ...
    'EDF signal %s must have a finite numeric physical %s.', ...
    channel_name, limit_name)
value = double(value);

end


function [digital_min, digital_max] = validate_digital_limits( ...
    signal_header, channel_name)

digital_min = signal_header.digital_min;
digital_max = signal_header.digital_max;
valid_limits = ...
    isnumeric(digital_min) && isnumeric(digital_max) && ...
    isreal(digital_min) && isreal(digital_max) && ...
    isscalar(digital_min) && isscalar(digital_max) && ...
    isfinite(digital_min) && isfinite(digital_max) && ...
    digital_min == fix(digital_min) && digital_max == fix(digital_max) && ...
    digital_min >= double(intmin('int16')) && ...
    digital_max <= double(intmax('int16')) && ...
    digital_min < digital_max;
assert(valid_limits, ...
    'substitute_eeg_data:InvalidDigitalLimits', ...
    'EDF signal %s must have valid int16 digital limits.', channel_name)
digital_min = double(digital_min);
digital_max = double(digital_max);

end


function output_derivation = build_output_derivations( ...
    clinical_system_faulty)

if clinical_system_faulty
    output_derivation = [ ...
        "Aligned Fp1"; ...
        "Aligned Fp2"; ...
        "Aligned F3"; ...
        "Aligned F4"; ...
        "Aligned C3"; ...
        "Aligned C4"; ...
        "Aligned O1"; ...
        "Aligned O2"; ...
        "Aligned M1"; ...
        "Aligned M2"; ...
        "Aligned VEOGL"; ...
        "Aligned Fp2"];
else
    output_derivation = [ ...
        "Aligned Fp1 - Aligned M2 + Clinical M2"; ...
        "Aligned Fp2 - Aligned M1 + Clinical M1"; ...
        "Aligned F3 - Aligned M2 + Clinical M2"; ...
        "Aligned F4 - Aligned M1 + Clinical M1"; ...
        "Aligned C3 - Aligned M2 + Clinical M2"; ...
        "Aligned C4 - Aligned M1 + Clinical M1"; ...
        "Aligned O1 - Aligned M2 + Clinical M2"; ...
        "Aligned O2 - Aligned M1 + Clinical M1"; ...
        "Clinical M1"; ...
        "Clinical M2"; ...
        "Clinical E1"; ...
        "Clinical E2"];
end

end


function figure_handle = plot_substitution_sanity_check( ...
    output_signal_cells, channel_names, ...
    physical_min_uV, physical_max_uV)

line_colors = lines(numel(channel_names));
figure_handle = figure('Color', 'w');
ax = axes( ...
    'Parent', figure_handle, ...
    'Tag', 'substitute_eeg_data_sanity_axes');
hold(ax, 'on')

for channel_i = 1:numel(channel_names)
    plot(ax, output_signal_cells{channel_i}, ...
        'Color', line_colors(channel_i, :), ...
        'LineWidth', 1, ...
        'DisplayName', channel_names{channel_i})
end
ax.InteractionOptions.DatatipsSupported = 'off';

yline(ax, physical_max_uV, ':k', ...
    'LineWidth', 1.25, ...
    'HandleVisibility', 'off', ...
    'Tag', 'substitute_eeg_data_upper_clip_bound');
yline(ax, physical_min_uV, ':k', ...
    'LineWidth', 1.25, ...
    'HandleVisibility', 'off', ...
    'Tag', 'substitute_eeg_data_lower_clip_bound');
hold(ax, 'off')

set(ax, 'FontSize', 14)
ylim(ax, [physical_min_uV - 500, physical_max_uV + 500])
xlabel(ax, 'EDF sample index')
ylabel(ax, 'Voltage (\muV)')
title(ax, ...
    'Final output EDF channels before clinical montage referencing', ...
    'FontSize', 18)
legend(ax, 'show', 'Location', 'best', 'NumColumns', 2)
grid(ax, 'on')

end
