function signalCell_all = substitute_eeg_data( ...
    final_eeg_data, edf_eeg_channel_names, ...
    aligned_eeg_channel_names, ...
    signalHeader_all, signalCell_all, plot_sanity_check)
%SUBSTITUTE_EEG_DATA Prepare grounded EDF scalp signals from aligned HD-EEG.
%   Each of the eight grounded scalp channels is replaced with its aligned
%   HD-EEG signal minus the aligned HD-EEG mastoid plus the requantized
%   clinical EDF mastoid. When the clinical montage subtracts that same
%   clinical mastoid, the displayed signal is the intended HD-EEG
%   derivation. Clinical E1, E2, M1, M2, and all montage-generated EDF
%   signal cells remain unchanged by this function.
%
%   SUBSTITUTE_EEG_DATA(..., PLOT_SANITY_CHECK) reports the percentage of
%   prepared samples outside the physical limits in SIGNALHEADER_ALL and,
%   by default, plots all eight prepared scalp signals with those limits
%   marked. Set PLOT_SANITY_CHECK to false to suppress the figure.

if nargin < 6
    plot_sanity_check = true;
end

assert(numel(signalHeader_all) == numel(signalCell_all), ...
    'substitute_eeg_data:SignalCountMismatch', ...
    'The EDF signal header and signal cell counts must match.')
assert(iscell(edf_eeg_channel_names) && ...
    all(cellfun(@ischar, edf_eeg_channel_names)), ...
    'substitute_eeg_data:InvalidChannelNames', ...
    'EDF EEG channel names must be provided as a cell array of text.')
assert(iscell(aligned_eeg_channel_names) && ...
    all(cellfun(@ischar, aligned_eeg_channel_names)), ...
    'substitute_eeg_data:InvalidAlignedChannelNames', ...
    'Aligned EEG channel names must be provided as a cell array of text.')

edf_eeg_channel_names = edf_eeg_channel_names(:).';
aligned_eeg_channel_names = aligned_eeg_channel_names(:).';
assert(size(final_eeg_data, 1) == numel(aligned_eeg_channel_names), ...
    'substitute_eeg_data:ChannelCountMismatch', ...
    ['Each row of the final EEG data must correspond to one name in ' ...
     'aligned_eeg_channel_names.'])
assert(numel(unique(edf_eeg_channel_names)) == ...
    numel(edf_eeg_channel_names), ...
    'substitute_eeg_data:DuplicateEegChannel', ...
    'EDF EEG channel names must be unique.')
assert(numel(unique(aligned_eeg_channel_names)) == ...
    numel(aligned_eeg_channel_names), ...
    'substitute_eeg_data:DuplicateAlignedEegChannel', ...
    'Aligned EEG channel names must be unique.')
assert(islogical(plot_sanity_check) && isscalar(plot_sanity_check), ...
    'substitute_eeg_data:InvalidPlotFlag', ...
    'The sanity-check plot flag must be a logical scalar.')

% These montage labels define the mastoid rule and report labels only.
% Their EDF signal cells are never substitution targets.
referenced_channel_names = { ...
    'Fp1:M2', 'Fp2:M1', 'F3:M2', 'F4:M1', ...
    'C3:M2', 'C4:M1', 'O1:M2', 'O2:M1'};
reference_rule_active_names = { ...
    'Fp1', 'Fp2', 'F3', 'F4', 'C3', 'C4', 'O1', 'O2'};
reference_rule_mastoid_names = { ...
    'M2', 'M1', 'M2', 'M1', 'M2', 'M1', 'M2', 'M1'};

[has_reference_rule, reference_rule_index] = ismember( ...
    edf_eeg_channel_names, reference_rule_active_names);
assert(numel(edf_eeg_channel_names) == ...
    numel(reference_rule_active_names) && all(has_reference_rule), ...
    'substitute_eeg_data:InvalidEdfEegChannels', ...
    ['EDF EEG channel names must contain exactly Fp1, Fp2, F3, F4, ' ...
     'C3, C4, O1, and O2.'])

active_channel_names = edf_eeg_channel_names;
reference_channel_names = ...
    reference_rule_mastoid_names(reference_rule_index);
referenced_channel_names = ...
    referenced_channel_names(reference_rule_index);

[has_active, active_index] = ismember( ...
    active_channel_names, aligned_eeg_channel_names);
[has_reference, reference_index] = ismember( ...
    reference_channel_names, aligned_eeg_channel_names);
if ~all(has_active) || ~all(has_reference)
    missing_channel_names = [ ...
        active_channel_names(~has_active), ...
        reference_channel_names(~has_reference)];
    error('substitute_eeg_data:MissingEegChannel', ...
        'Required EEG source channel(s) not found: %s.', ...
        strjoin(unique(missing_channel_names, 'stable'), ', '))
end

signal_labels = {signalHeader_all.signal_labels};
signal_labels = signal_labels(:).';
clinical_reference_channel_names = ...
    unique(reference_channel_names, 'stable');
target_channel_names = [ ...
    active_channel_names, clinical_reference_channel_names];
target_index = zeros(size(target_channel_names));

for channel_i = 1:numel(target_channel_names)
    matching_index = find(strcmp( ...
        signal_labels, target_channel_names{channel_i}));
    if isempty(matching_index)
        error('substitute_eeg_data:MissingEdfChannel', ...
            'Required EDF signal label not found: %s.', ...
            target_channel_names{channel_i})
    elseif numel(matching_index) > 1
        error('substitute_eeg_data:DuplicateEdfChannel', ...
            'EDF signal label occurs more than once: %s.', ...
            target_channel_names{channel_i})
    end

    target_index(channel_i) = matching_index;
    assert(isvector(signalCell_all{matching_index}) && ...
        numel(signalCell_all{matching_index}) == ...
            size(final_eeg_data, 2), ...
        'substitute_eeg_data:SampleCountMismatch', ...
        ['EDF signal %s must have the same sample count as the final ' ...
         'EEG data.'], target_channel_names{channel_i})
end

n_scalp_channels = numel(active_channel_names);
physical_min_values = double( ...
    [signalHeader_all(target_index).physical_min]);
physical_max_values = double( ...
    [signalHeader_all(target_index).physical_max]);
assert(all(isfinite(physical_min_values)) && ...
    all(isfinite(physical_max_values)) && ...
    all(physical_min_values < physical_max_values), ...
    'substitute_eeg_data:InvalidPhysicalLimits', ...
    'The substituted scalp and clinical mastoid limits must be valid.')
assert(all(physical_min_values == physical_min_values(1)) && ...
    all(physical_max_values == physical_max_values(1)), ...
    'substitute_eeg_data:InconsistentPhysicalLimits', ...
    ['The substituted scalp and clinical mastoid channels must share ' ...
     'physical limits.'])
physical_min_uV = physical_min_values(1);
physical_max_uV = physical_max_values(1);
[~, clinical_reference_position] = ismember( ...
    reference_channel_names, clinical_reference_channel_names);
clinical_reference_index = target_index( ...
    n_scalp_channels + clinical_reference_position);
percent_outside_bounds = zeros(n_scalp_channels, 1);

for channel_i = 1:n_scalp_channels
    clinical_reference_data = reshape( ...
        signalCell_all{clinical_reference_index(channel_i)}, 1, []);

    %%%%%%%%%% HD Active - HD Mastoid Analog + Clinical Mastoid %%%%%%
    substituted_data = ...
        final_eeg_data(active_index(channel_i), :) - ...
        final_eeg_data(reference_index(channel_i), :) + ...
        clinical_reference_data;
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

    edf_index = target_index(channel_i);
    signalCell_all{edf_index} = reshape( ...
        substituted_data, size(signalCell_all{edf_index}));
    percent_outside_bounds(channel_i) = 100 * sum( ...
        substituted_data < physical_min_uV | ...
        substituted_data > physical_max_uV) / numel(substituted_data);
end

clipping_report = table( ...
    string(active_channel_names(:)), ...
    string(referenced_channel_names(:)), ...
    round(percent_outside_bounds, 3), ...
    'VariableNames', { ...
        'EDFChannel', 'ClinicalMontage', 'PercentOutsideBounds (%)'});
fprintf( ...
    '\nEDF scalp substitution clipping report (%g to %g uV)\n', ...
    physical_min_uV, physical_max_uV)
disp(clipping_report)

if plot_sanity_check
    plot_substitution_sanity_check( ...
        signalCell_all(target_index(1:n_scalp_channels)), ...
        active_channel_names, ...
        physical_min_uV, physical_max_uV)
end

end

%%
function plot_substitution_sanity_check( ...
    substituted_signal_cells, channel_names, ...
    physical_min_uV, physical_max_uV)

line_colors = lines(numel(channel_names));
figure_handle = figure( ...
    'Name', 'EDF scalp substitution sanity check', ...
    'Tag', 'substitute_eeg_data_sanity_check', ...
    'Color', 'w');
ax = axes( ...
    'Parent', figure_handle, ...
    'Tag', 'substitute_eeg_data_sanity_axes');
hold(ax, 'on')

for channel_i = 1:numel(channel_names)
    plot(ax, substituted_signal_cells{channel_i}, ...
        'Color', line_colors(channel_i, :), ...
        'LineWidth', 1, ...
        'DisplayName', channel_names{channel_i})
end

yline(ax, physical_max_uV, ':k', ...
    'LineWidth', 1.25, ...
    'HandleVisibility', 'off', ...
    'Tag', 'substitute_eeg_data_upper_clip_bound');
yline(ax, physical_min_uV, ':k', ...
    'LineWidth', 1.25, ...
    'HandleVisibility', 'off', ...
    'Tag', 'substitute_eeg_data_lower_clip_bound');
hold(ax, 'off')

set(ax, 'FontSize', 14)
ylim(ax, [physical_min_uV-500, physical_max_uV+500])
xlabel(ax, 'EDF sample index')
ylabel(ax, 'Voltage (\muV)')
title(ax, ...
    'Grounded EDF scalp substitutions before clinical montage referencing', ...
    'FontSize', 18)
legend(ax, 'show', 'Location', 'best', 'NumColumns', 2)
grid(ax, 'on')

end
