function signalCell_final = substitute_eeg_data( ...
    final_eeg_data, edf_eeg_channel_names, ...
    aligned_eeg_channel_names, ...
    signalHeader_all, signalCell_all)
%SUBSTITUTE_EEG_DATA Replace EDF EEG signals with aligned HD-EEG data.
%   Direct channels are matched by label. Contralaterally referenced
%   channels are constructed as active electrode minus mastoid reference.

assert(numel(signalHeader_all) == numel(signalCell_all), ...
    'substitute_eeg_data:SignalCountMismatch', ...
    'The EDF signal header and signal cell counts must match.')
assert(iscell(edf_eeg_channel_names) && ...
    all(cellfun(@ischar, edf_eeg_channel_names)), ...
    'substitute_eeg_data:InvalidChannelNames', ...
    'EDF EEG channel names must be provided as a cell array of text.')
assert(iscell(aligned_eeg_channel_names) && ...
    all(cellfun(@ischar, aligned_eeg_channel_names)), ...
    'substitute_eeg_data:InvalidAlignedChannelNames', ...
    'Aligned EEG channel names must be provided as a cell array of text.')

edf_eeg_channel_names = edf_eeg_channel_names(:).';
aligned_eeg_channel_names = aligned_eeg_channel_names(:).';
assert(size(final_eeg_data, 1) == numel(aligned_eeg_channel_names), ...
    'substitute_eeg_data:ChannelCountMismatch', ...
    ['Each row of the final EEG data must correspond to one name in ' ...
     'aligned_eeg_channel_names.'])
assert(numel(unique(edf_eeg_channel_names)) == ...
    numel(edf_eeg_channel_names), ...
    'substitute_eeg_data:DuplicateEegChannel', ...
    'EDF EEG channel names must be unique.')
assert(numel(unique(aligned_eeg_channel_names)) == ...
    numel(aligned_eeg_channel_names), ...
    'substitute_eeg_data:DuplicateAlignedEegChannel', ...
    'Aligned EEG channel names must be unique.')

[has_edf_channel, edf_channel_index] = ismember( ...
    edf_eeg_channel_names, aligned_eeg_channel_names);
assert(all(has_edf_channel), ...
    'Every EDF EEG channel must be present in the aligned EEG data.')

referenced_channel_names = { ...
    'Fp1:M2', 'Fp2:M1', 'F3:M2', 'F4:M1', ...
    'C3:M2', 'C4:M1', 'O1:M2', 'O2:M1'};
active_channel_names = { ...
    'Fp1', 'Fp2', 'F3', 'F4', 'C3', 'C4', 'O1', 'O2'};
reference_channel_names = { ...
    'M2', 'M1', 'M2', 'M1', 'M2', 'M1', 'M2', 'M1'};

[has_active, active_index] = ismember( ...
    active_channel_names, aligned_eeg_channel_names);
[has_reference, reference_index] = ismember( ...
    reference_channel_names, aligned_eeg_channel_names);
if ~all(has_active) || ~all(has_reference)
    missing_channel_names = [ ...
        active_channel_names(~has_active), ...
        reference_channel_names(~has_reference)];
    error('substitute_eeg_data:MissingEegChannel', ...
        'Required EEG source channel(s) not found: %s.', ...
        strjoin(unique(missing_channel_names, 'stable'), ', '))
end

signal_labels = {signalHeader_all.signal_labels};
signal_labels = signal_labels(:).';
target_channel_names = [ ...
    edf_eeg_channel_names, referenced_channel_names];
target_index = zeros(size(target_channel_names));

for channel_i = 1:numel(target_channel_names)
    matching_index = find(strcmp( ...
        signal_labels, target_channel_names{channel_i}));
    if isempty(matching_index)
        error('substitute_eeg_data:MissingEdfChannel', ...
            'Required EDF signal label not found: %s.', ...
            target_channel_names{channel_i})
    elseif numel(matching_index) > 1
        error('substitute_eeg_data:DuplicateEdfChannel', ...
            'EDF signal label occurs more than once: %s.', ...
            target_channel_names{channel_i})
    end

    target_index(channel_i) = matching_index;
    assert(isvector(signalCell_all{matching_index}) && ...
        numel(signalCell_all{matching_index}) == ...
            size(final_eeg_data, 2), ...
        'substitute_eeg_data:SampleCountMismatch', ...
        ['EDF signal %s must have the same sample count as the final ' ...
         'EEG data.'], target_channel_names{channel_i})
end

signalCell_final = signalCell_all;
n_direct_channels = numel(edf_eeg_channel_names);

for channel_i = 1:n_direct_channels
    edf_index = target_index(channel_i);
    signalCell_final{edf_index} = reshape( ...
        final_eeg_data(edf_channel_index(channel_i), :), ...
        size(signalCell_all{edf_index}));
end

for channel_i = 1:numel(referenced_channel_names)
    referenced_data = ...
        final_eeg_data(active_index(channel_i), :) - ...
        final_eeg_data(reference_index(channel_i), :);
    edf_index = target_index(n_direct_channels + channel_i);
    signalCell_final{edf_index} = reshape( ...
        referenced_data, size(signalCell_all{edf_index}));
end

end
